const fs = require('fs');
const path = require('path');
const { PROJECT_ROOT } = require('../utils/helpers');

function generateSharedIndex(data) {
  console.log('\n--- Generating Shared index.ts (Step 1.5) ---');
  const constants = data.constants || {};
  
  let content = `/**
 * @file index.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-parameters/ (formerly camera-parameters.yaml)
 * 
 * To add, edit, or remove default values, modify the YAML files and run:
 *   npm run codegen
 */

`;

  for (const [key, value] of Object.entries(constants)) {
    let formattedValue = value;
    if (typeof value === 'string') {
      formattedValue = `"${value}"`;
    }
    content += `export const ${key} = ${formattedValue};\n`;
  }
  
  content += `\nexport * from './hardwareConfig';\n`;
  
  const indexPath = path.resolve(PROJECT_ROOT, 'packages/shared/src/index.ts');
  fs.writeFileSync(indexPath, content, 'utf8');
  console.log(`Successfully updated: packages/shared/src/index.ts`);
}

module.exports = {
  generateSharedIndex
};
