#include "CameraStateManager.h"
#include <algorithm>
#include <cmath>

CameraStateManager::CameraStateManager() {
    auto initial = std::make_shared<RenderState>();
    
    // @@GEN_DEFAULTS_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    initial->renderParams.saturation = 1.0f;
    initial->renderParams.contrast = 1.0f;
    initial->renderParams.grainIntensity = 0.0f;
    initial->renderParams.grainChroma = 0.0f;
    initial->renderParams.grainSize = 1.0f;
    initial->renderParams.grainSpeed = 20.0f;
    initial->renderParams.vignetteIntensity = 0.0f;
    initial->renderParams.chromaShift = 0.0f;
    initial->renderParams.whiteBalance = 5000.0f;
    initial->renderParams.tint = 0.0f;
    initial->renderParams.bloomIntensity = 0.0f;
    initial->renderParams.chromaticAberration = 0.0f;
    initial->renderParams.chromaShiftDirection = 0.0f;
    initial->renderParams.sharpening = 0.0f;
    initial->renderParams.satRed = 50.0f;
    initial->renderParams.satOrange = 50.0f;
    initial->renderParams.satYellow = 50.0f;
    initial->renderParams.satGreen = 50.0f;
    initial->renderParams.satCyan = 50.0f;
    initial->renderParams.satBlue = 50.0f;
    initial->renderParams.satPurple = 50.0f;
    initial->renderParams.satMagenta = 50.0f;
    initial->renderParams.aberrationInvert = 0.0f;
    initial->renderParams.boundMagentaRed = 350.0f;
    initial->renderParams.boundRedOrange = 40.0f;
    initial->renderParams.boundOrangeYellow = 70.0f;
    initial->renderParams.boundYellowGreen = 110.0f;
    initial->renderParams.boundGreenCyan = 170.0f;
    initial->renderParams.boundCyanBlue = 230.0f;
    initial->renderParams.boundBluePurple = 280.0f;
    initial->renderParams.boundPurpleMagenta = 315.0f;
    initial->renderParams.grainRoughness = 0.0f;
    initial->renderParams.panelY = 1.0f;
    initial->renderParams.grainEnabled = 0.0f;
    initial->renderParams.bloomEnabled = 0.0f;
    initial->renderParams.blackLevel = 0.0f;
    initial->renderParams.highlights = 1.0f;
    initial->renderParams.pivot = 0.5f;
    initial->renderParams.contrastAuto = 1.0f;
    initial->renderParams.blackLevelAuto = 1.0f;
    initial->renderParams.highlightsAuto = 1.0f;
    initial->renderParams.pivotAuto = 1.0f;
    initial->renderParams.pixelationFactor = 1.0f;
    initial->renderParams.tapeJitter = 0.0f;
    initial->renderParams.scanlines = 0.0f;
    initial->renderParams.chromaShiftInvert = 0.0f;
    initial->renderParams.hue = 0.0f;
    initial->renderParams.hueRed = 0.0f;
    initial->renderParams.hueOrange = 0.0f;
    initial->renderParams.hueYellow = 0.0f;
    initial->renderParams.hueGreen = 0.0f;
    initial->renderParams.hueCyan = 0.0f;
    initial->renderParams.hueBlue = 0.0f;
    initial->renderParams.huePurple = 0.0f;
    initial->renderParams.hueMagenta = 0.0f;
    initial->renderParams.scanlinesHorizontal = 1.0f;
    initial->renderParams.scanlinesMode = 0.0f;
    initial->renderParams.scanlinesDensity = 800.0f;
    initial->renderParams.lensDistortion = 0.0f;
    // @@GEN_DEFAULTS_END@@
    
    std::atomic_store(&m_activeState, initial);
}

void CameraStateManager::clampState(RenderState& state) const {
    // @@GEN_CLAMPING_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    state.renderParams.saturation = std::isnan(state.renderParams.saturation) ? 1.0f : std::clamp(state.renderParams.saturation, 0.0000f, 2.0000f);
    state.renderParams.contrast = std::isnan(state.renderParams.contrast) ? 1.0f : std::clamp(state.renderParams.contrast, 0.0000f, 2.0000f);
    state.renderParams.grainIntensity = std::isnan(state.renderParams.grainIntensity) ? 0.0f : std::clamp(state.renderParams.grainIntensity, 0.0000f, 2.0000f);
    state.renderParams.vignetteIntensity = std::isnan(state.renderParams.vignetteIntensity) ? 0.0f : std::clamp(state.renderParams.vignetteIntensity, 0.0000f, 1.0000f);
    state.renderParams.chromaShift = std::isnan(state.renderParams.chromaShift) ? 0.0f : std::clamp(state.renderParams.chromaShift, 0.0000f, 1.0000f);
    state.renderParams.whiteBalance = std::isnan(state.renderParams.whiteBalance) ? 5000.0f : std::clamp(state.renderParams.whiteBalance, 2000.0000f, 10000.0000f);
    state.renderParams.tint = std::isnan(state.renderParams.tint) ? 0.0f : std::clamp(state.renderParams.tint, -100.0000f, 100.0000f);
    state.renderParams.bloomIntensity = std::isnan(state.renderParams.bloomIntensity) ? 0.0f : std::clamp(state.renderParams.bloomIntensity, 0.0000f, 9999.0000f);
    state.renderParams.chromaticAberration = std::isnan(state.renderParams.chromaticAberration) ? 0.0f : std::clamp(state.renderParams.chromaticAberration, 0.0000f, 1.0000f);
    state.renderParams.sharpening = std::isnan(state.renderParams.sharpening) ? 0.0f : std::clamp(state.renderParams.sharpening, 0.0000f, 1.0000f);
    state.renderParams.blackLevel = std::isnan(state.renderParams.blackLevel) ? 0.0f : std::clamp(state.renderParams.blackLevel, -0.5000f, 0.5000f);
    state.renderParams.highlights = std::isnan(state.renderParams.highlights) ? 1.0f : std::clamp(state.renderParams.highlights, 0.0000f, 2.0000f);
    state.renderParams.pivot = std::isnan(state.renderParams.pivot) ? 0.5f : std::clamp(state.renderParams.pivot, 0.0000f, 1.0000f);
    state.renderParams.pixelationFactor = std::isnan(state.renderParams.pixelationFactor) ? 1.0f : std::clamp(state.renderParams.pixelationFactor, 1.0000f, 16.0000f);
    state.renderParams.tapeJitter = std::isnan(state.renderParams.tapeJitter) ? 0.0f : std::clamp(state.renderParams.tapeJitter, 0.0000f, 1.0000f);
    state.renderParams.scanlines = std::isnan(state.renderParams.scanlines) ? 0.0f : std::clamp(state.renderParams.scanlines, 0.0000f, 1.0000f);
    state.renderParams.hue = std::isnan(state.renderParams.hue) ? 0.0f : std::clamp(state.renderParams.hue, -180.0000f, 180.0000f);
    state.renderParams.lensDistortion = std::isnan(state.renderParams.lensDistortion) ? 0.0f : std::clamp(state.renderParams.lensDistortion, -1.0000f, 1.0000f);
    // @@GEN_CLAMPING_END@@

    switch (state.resolutionSetting) {
        case 0: state.targetResolution = 2160.0f; break;
        case 1: state.targetResolution = 1440.0f; break;
        case 2: state.targetResolution = 1080.0f; break;
        case 3: state.targetResolution = 720.0f; break;
        case 4: state.targetResolution = 480.0f; break;
        case 5: state.targetResolution = 360.0f; break;
        case 6: state.targetResolution = 240.0f; break;
        case 7: state.targetResolution = 144.0f; break;
        default: state.targetResolution = 1080.0f; break;
    }
}
