#pragma once

#include "HybridNitroCameraConfigurationSpec.hpp"

namespace margelo::nitro::grovkornet {

class HybridNitroCameraConfiguration : public HybridNitroCameraConfigurationSpec {
public:
    HybridNitroCameraConfiguration();
    virtual ~HybridNitroCameraConfiguration() override = default;

public:
    // @@GEN_PROPERTIES_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    double getSaturation() override;
    void setSaturation(double value) override;
    double getContrast() override;
    void setContrast(double value) override;
    double getGrainIntensity() override;
    void setGrainIntensity(double value) override;
    double getGrainChroma() override;
    void setGrainChroma(double value) override;
    double getGrainSize() override;
    void setGrainSize(double value) override;
    double getGrainSpeed() override;
    void setGrainSpeed(double value) override;
    double getVignetteIntensity() override;
    void setVignetteIntensity(double value) override;
    double getChromaShift() override;
    void setChromaShift(double value) override;
    double getTemperature() override;
    void setTemperature(double value) override;
    double getTint() override;
    void setTint(double value) override;
    double getBloomIntensity() override;
    void setBloomIntensity(double value) override;
    double getChromaticAberration() override;
    void setChromaticAberration(double value) override;
    double getChromaShiftDirection() override;
    void setChromaShiftDirection(double value) override;
    double getSharpening() override;
    void setSharpening(double value) override;
    double getSatRed() override;
    void setSatRed(double value) override;
    double getSatOrange() override;
    void setSatOrange(double value) override;
    double getSatYellow() override;
    void setSatYellow(double value) override;
    double getSatGreen() override;
    void setSatGreen(double value) override;
    double getSatCyan() override;
    void setSatCyan(double value) override;
    double getSatBlue() override;
    void setSatBlue(double value) override;
    double getSatPurple() override;
    void setSatPurple(double value) override;
    double getSatMagenta() override;
    void setSatMagenta(double value) override;
    bool getAberrationInvert() override;
    void setAberrationInvert(bool value) override;
    double getBoundMagentaRed() override;
    void setBoundMagentaRed(double value) override;
    double getBoundRedOrange() override;
    void setBoundRedOrange(double value) override;
    double getBoundOrangeYellow() override;
    void setBoundOrangeYellow(double value) override;
    double getBoundYellowGreen() override;
    void setBoundYellowGreen(double value) override;
    double getBoundGreenCyan() override;
    void setBoundGreenCyan(double value) override;
    double getBoundCyanBlue() override;
    void setBoundCyanBlue(double value) override;
    double getBoundBluePurple() override;
    void setBoundBluePurple(double value) override;
    double getBoundPurpleMagenta() override;
    void setBoundPurpleMagenta(double value) override;
    double getGrainRoughness() override;
    void setGrainRoughness(double value) override;
    double getPanelY() override;
    void setPanelY(double value) override;
    bool getGrainEnabled() override;
    void setGrainEnabled(bool value) override;
    bool getBloomEnabled() override;
    void setBloomEnabled(bool value) override;
    double getBlackLevel() override;
    void setBlackLevel(double value) override;
    double getHighlights() override;
    void setHighlights(double value) override;
    double getPivot() override;
    void setPivot(double value) override;
    bool getContrastAuto() override;
    void setContrastAuto(bool value) override;
    bool getBlackLevelAuto() override;
    void setBlackLevelAuto(bool value) override;
    bool getHighlightsAuto() override;
    void setHighlightsAuto(bool value) override;
    bool getPivotAuto() override;
    void setPivotAuto(bool value) override;
    double getPixelationFactor() override;
    void setPixelationFactor(double value) override;
    double getTapeJitter() override;
    void setTapeJitter(double value) override;
    double getScanlines() override;
    void setScanlines(double value) override;
    bool getChromaShiftInvert() override;
    void setChromaShiftInvert(bool value) override;
    double getHue() override;
    void setHue(double value) override;
    double getHueRed() override;
    void setHueRed(double value) override;
    double getHueOrange() override;
    void setHueOrange(double value) override;
    double getHueYellow() override;
    void setHueYellow(double value) override;
    double getHueGreen() override;
    void setHueGreen(double value) override;
    double getHueCyan() override;
    void setHueCyan(double value) override;
    double getHueBlue() override;
    void setHueBlue(double value) override;
    double getHuePurple() override;
    void setHuePurple(double value) override;
    double getHueMagenta() override;
    void setHueMagenta(double value) override;
    bool getScanlinesHorizontal() override;
    void setScanlinesHorizontal(bool value) override;
    double getScanlinesMode() override;
    void setScanlinesMode(double value) override;
    double getScanlinesDensity() override;
    void setScanlinesDensity(double value) override;
    double getLensDistortion() override;
    void setLensDistortion(double value) override;
    double getHalationIntensity() override;
    void setHalationIntensity(double value) override;
    bool getHalationEnabled() override;
    void setHalationEnabled(bool value) override;
    double getHalationThreshold() override;
    void setHalationThreshold(double value) override;
    double getBloomThreshold() override;
    void setBloomThreshold(double value) override;
    double getChromaBleed() override;
    void setChromaBleed(double value) override;
    double getDeviceOrientation() override;
    void setDeviceOrientation(double value) override;
    // @@GEN_PROPERTIES_END@@
};

} // namespace margelo::nitro::grovkornet
