#include "HybridNitroCameraConfiguration.hpp"
#include "state/CameraStateManager.h"
#include <algorithm>

namespace margelo::nitro::grovkornet {

HybridNitroCameraConfiguration::HybridNitroCameraConfiguration() : HybridObject(TAG) {}

// @@GEN_PROPERTIES_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
double HybridNitroCameraConfiguration::getSaturation() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.saturation;
}

void HybridNitroCameraConfiguration::setSaturation(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.saturation = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getContrast() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.contrast;
}

void HybridNitroCameraConfiguration::setContrast(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.contrast = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getGrainIntensity() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainIntensity;
}

void HybridNitroCameraConfiguration::setGrainIntensity(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainIntensity = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getGrainChroma() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainChroma;
}

void HybridNitroCameraConfiguration::setGrainChroma(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainChroma = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getGrainSize() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainSize;
}

void HybridNitroCameraConfiguration::setGrainSize(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainSize = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getGrainSpeed() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainSpeed;
}

void HybridNitroCameraConfiguration::setGrainSpeed(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainSpeed = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getVignetteIntensity() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.vignetteIntensity;
}

void HybridNitroCameraConfiguration::setVignetteIntensity(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.vignetteIntensity = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getChromaShift() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.chromaShift;
}

void HybridNitroCameraConfiguration::setChromaShift(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.chromaShift = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getTemperature() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.temperature;
}

void HybridNitroCameraConfiguration::setTemperature(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.temperature = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getTint() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.tint;
}

void HybridNitroCameraConfiguration::setTint(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.tint = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBloomIntensity() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.bloomIntensity;
}

void HybridNitroCameraConfiguration::setBloomIntensity(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.bloomIntensity = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getChromaticAberration() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.chromaticAberration;
}

void HybridNitroCameraConfiguration::setChromaticAberration(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.chromaticAberration = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getChromaShiftDirection() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.chromaShiftDirection;
}

void HybridNitroCameraConfiguration::setChromaShiftDirection(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.chromaShiftDirection = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSharpening() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.sharpening;
}

void HybridNitroCameraConfiguration::setSharpening(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.sharpening = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatRed() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satRed;
}

void HybridNitroCameraConfiguration::setSatRed(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satRed = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatOrange() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satOrange;
}

void HybridNitroCameraConfiguration::setSatOrange(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satOrange = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatYellow() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satYellow;
}

void HybridNitroCameraConfiguration::setSatYellow(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satYellow = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatGreen() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satGreen;
}

void HybridNitroCameraConfiguration::setSatGreen(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satGreen = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatCyan() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satCyan;
}

void HybridNitroCameraConfiguration::setSatCyan(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satCyan = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatBlue() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satBlue;
}

void HybridNitroCameraConfiguration::setSatBlue(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satBlue = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatPurple() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satPurple;
}

void HybridNitroCameraConfiguration::setSatPurple(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satPurple = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getSatMagenta() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.satMagenta;
}

void HybridNitroCameraConfiguration::setSatMagenta(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.satMagenta = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getAberrationInvert() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.aberrationInvert > 0.5f;
}

void HybridNitroCameraConfiguration::setAberrationInvert(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.aberrationInvert = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getBoundMagentaRed() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundMagentaRed;
}

void HybridNitroCameraConfiguration::setBoundMagentaRed(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundMagentaRed = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundRedOrange() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundRedOrange;
}

void HybridNitroCameraConfiguration::setBoundRedOrange(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundRedOrange = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundOrangeYellow() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundOrangeYellow;
}

void HybridNitroCameraConfiguration::setBoundOrangeYellow(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundOrangeYellow = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundYellowGreen() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundYellowGreen;
}

void HybridNitroCameraConfiguration::setBoundYellowGreen(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundYellowGreen = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundGreenCyan() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundGreenCyan;
}

void HybridNitroCameraConfiguration::setBoundGreenCyan(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundGreenCyan = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundCyanBlue() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundCyanBlue;
}

void HybridNitroCameraConfiguration::setBoundCyanBlue(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundCyanBlue = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundBluePurple() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundBluePurple;
}

void HybridNitroCameraConfiguration::setBoundBluePurple(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundBluePurple = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBoundPurpleMagenta() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.boundPurpleMagenta;
}

void HybridNitroCameraConfiguration::setBoundPurpleMagenta(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.boundPurpleMagenta = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getGrainRoughness() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainRoughness;
}

void HybridNitroCameraConfiguration::setGrainRoughness(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainRoughness = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getPanelY() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.panelY;
}

void HybridNitroCameraConfiguration::setPanelY(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.panelY = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getGrainEnabled() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.grainEnabled > 0.5f;
}

void HybridNitroCameraConfiguration::setGrainEnabled(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.grainEnabled = value ? 1.0f : 0.0f;
});
}

bool HybridNitroCameraConfiguration::getBloomEnabled() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.bloomEnabled > 0.5f;
}

void HybridNitroCameraConfiguration::setBloomEnabled(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.bloomEnabled = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getBlackLevel() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.blackLevel;
}

void HybridNitroCameraConfiguration::setBlackLevel(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.blackLevel = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHighlights() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.highlights;
}

void HybridNitroCameraConfiguration::setHighlights(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.highlights = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getPivot() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.pivot;
}

void HybridNitroCameraConfiguration::setPivot(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.pivot = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getContrastAuto() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.contrastAuto > 0.5f;
}

void HybridNitroCameraConfiguration::setContrastAuto(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.contrastAuto = value ? 1.0f : 0.0f;
});
}

bool HybridNitroCameraConfiguration::getBlackLevelAuto() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.blackLevelAuto > 0.5f;
}

void HybridNitroCameraConfiguration::setBlackLevelAuto(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.blackLevelAuto = value ? 1.0f : 0.0f;
});
}

bool HybridNitroCameraConfiguration::getHighlightsAuto() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.highlightsAuto > 0.5f;
}

void HybridNitroCameraConfiguration::setHighlightsAuto(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.highlightsAuto = value ? 1.0f : 0.0f;
});
}

bool HybridNitroCameraConfiguration::getPivotAuto() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.pivotAuto > 0.5f;
}

void HybridNitroCameraConfiguration::setPivotAuto(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.pivotAuto = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getPixelationFactor() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.pixelationFactor;
}

void HybridNitroCameraConfiguration::setPixelationFactor(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.pixelationFactor = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getTapeJitter() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.tapeJitter;
}

void HybridNitroCameraConfiguration::setTapeJitter(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.tapeJitter = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getScanlines() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.scanlines;
}

void HybridNitroCameraConfiguration::setScanlines(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.scanlines = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getChromaShiftInvert() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.chromaShiftInvert > 0.5f;
}

void HybridNitroCameraConfiguration::setChromaShiftInvert(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.chromaShiftInvert = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getHue() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hue;
}

void HybridNitroCameraConfiguration::setHue(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hue = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueRed() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueRed;
}

void HybridNitroCameraConfiguration::setHueRed(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueRed = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueOrange() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueOrange;
}

void HybridNitroCameraConfiguration::setHueOrange(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueOrange = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueYellow() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueYellow;
}

void HybridNitroCameraConfiguration::setHueYellow(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueYellow = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueGreen() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueGreen;
}

void HybridNitroCameraConfiguration::setHueGreen(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueGreen = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueCyan() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueCyan;
}

void HybridNitroCameraConfiguration::setHueCyan(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueCyan = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueBlue() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueBlue;
}

void HybridNitroCameraConfiguration::setHueBlue(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueBlue = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHuePurple() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.huePurple;
}

void HybridNitroCameraConfiguration::setHuePurple(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.huePurple = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHueMagenta() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.hueMagenta;
}

void HybridNitroCameraConfiguration::setHueMagenta(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.hueMagenta = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getScanlinesHorizontal() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.scanlinesHorizontal > 0.5f;
}

void HybridNitroCameraConfiguration::setScanlinesHorizontal(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.scanlinesHorizontal = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getScanlinesMode() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.scanlinesMode;
}

void HybridNitroCameraConfiguration::setScanlinesMode(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.scanlinesMode = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getScanlinesDensity() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.scanlinesDensity;
}

void HybridNitroCameraConfiguration::setScanlinesDensity(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.scanlinesDensity = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getLensDistortion() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.lensDistortion;
}

void HybridNitroCameraConfiguration::setLensDistortion(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.lensDistortion = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getHalationIntensity() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.halationIntensity;
}

void HybridNitroCameraConfiguration::setHalationIntensity(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.halationIntensity = static_cast<float>(value);
});
}

bool HybridNitroCameraConfiguration::getHalationEnabled() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.halationEnabled > 0.5f;
}

void HybridNitroCameraConfiguration::setHalationEnabled(bool value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.halationEnabled = value ? 1.0f : 0.0f;
});
}

double HybridNitroCameraConfiguration::getHalationThreshold() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.halationThreshold;
}

void HybridNitroCameraConfiguration::setHalationThreshold(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.halationThreshold = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getBloomThreshold() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.bloomThreshold;
}

void HybridNitroCameraConfiguration::setBloomThreshold(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.bloomThreshold = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getChromaBleed() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.chromaBleed;
}

void HybridNitroCameraConfiguration::setChromaBleed(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.chromaBleed = static_cast<float>(value);
});
}

double HybridNitroCameraConfiguration::getDeviceOrientation() {
    return CameraStateManager::getInstance().getActiveState()->renderParams.deviceOrientation;
}

void HybridNitroCameraConfiguration::setDeviceOrientation(double value) {
    CameraStateManager::getInstance().updateStateField([=](RenderState& state) {
    state.renderParams.deviceOrientation = static_cast<float>(value);
});
}
// @@GEN_PROPERTIES_END@@

} // namespace margelo::nitro::grovkornet
