import { useMemo } from 'react';
import { useFilmStore } from '../model/useFilmStore';
import { getNitroConfig } from '../model/getNitroConfig';
import { updateSharedValue } from '@shared/lib/reanimated/safeUpdate';
import { useSharedValue } from 'react-native-reanimated';

export const useFilmWorklets = () => {
  const config = getNitroConfig();

  // @@GEN_WORKLET_FLAGS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  const hasWarnedNaN_noiseReductionMode = useSharedValue(false);
  const hasWarnedNaN_saturation = useSharedValue(false);
  const hasWarnedNaN_contrast = useSharedValue(false);
  const hasWarnedNaN_grainIntensity = useSharedValue(false);
  const hasWarnedNaN_grainChroma = useSharedValue(false);
  const hasWarnedNaN_grainSize = useSharedValue(false);
  const hasWarnedNaN_grainSpeed = useSharedValue(false);
  const hasWarnedNaN_vignetteIntensity = useSharedValue(false);
  const hasWarnedNaN_chromaShift = useSharedValue(false);
  const hasWarnedNaN_temperature = useSharedValue(false);
  const hasWarnedNaN_tint = useSharedValue(false);
  const hasWarnedNaN_bloomIntensity = useSharedValue(false);
  const hasWarnedNaN_chromaticAberration = useSharedValue(false);
  const hasWarnedNaN_chromaShiftDirection = useSharedValue(false);
  const hasWarnedNaN_sharpening = useSharedValue(false);
  const hasWarnedNaN_satRed = useSharedValue(false);
  const hasWarnedNaN_satOrange = useSharedValue(false);
  const hasWarnedNaN_satYellow = useSharedValue(false);
  const hasWarnedNaN_satGreen = useSharedValue(false);
  const hasWarnedNaN_satCyan = useSharedValue(false);
  const hasWarnedNaN_satBlue = useSharedValue(false);
  const hasWarnedNaN_satPurple = useSharedValue(false);
  const hasWarnedNaN_satMagenta = useSharedValue(false);
  const hasWarnedNaN_boundMagentaRed = useSharedValue(false);
  const hasWarnedNaN_boundRedOrange = useSharedValue(false);
  const hasWarnedNaN_boundOrangeYellow = useSharedValue(false);
  const hasWarnedNaN_boundYellowGreen = useSharedValue(false);
  const hasWarnedNaN_boundGreenCyan = useSharedValue(false);
  const hasWarnedNaN_boundCyanBlue = useSharedValue(false);
  const hasWarnedNaN_boundBluePurple = useSharedValue(false);
  const hasWarnedNaN_boundPurpleMagenta = useSharedValue(false);
  const hasWarnedNaN_grainRoughness = useSharedValue(false);
  const hasWarnedNaN_blackLevel = useSharedValue(false);
  const hasWarnedNaN_highlights = useSharedValue(false);
  const hasWarnedNaN_pivot = useSharedValue(false);
  const hasWarnedNaN_pixelationFactor = useSharedValue(false);
  const hasWarnedNaN_tapeJitter = useSharedValue(false);
  const hasWarnedNaN_scanlines = useSharedValue(false);
  const hasWarnedNaN_hue = useSharedValue(false);
  const hasWarnedNaN_hueRed = useSharedValue(false);
  const hasWarnedNaN_hueOrange = useSharedValue(false);
  const hasWarnedNaN_hueYellow = useSharedValue(false);
  const hasWarnedNaN_hueGreen = useSharedValue(false);
  const hasWarnedNaN_hueCyan = useSharedValue(false);
  const hasWarnedNaN_hueBlue = useSharedValue(false);
  const hasWarnedNaN_huePurple = useSharedValue(false);
  const hasWarnedNaN_hueMagenta = useSharedValue(false);
  const hasWarnedNaN_scanlinesMode = useSharedValue(false);
  const hasWarnedNaN_scanlinesDensity = useSharedValue(false);
  // @@GEN_WORKLET_FLAGS_END@@

  return useMemo(() => {
    const film = useFilmStore.getState();

    // @@GEN_WORKLETS_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        const updateNoiseReductionMode = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_noiseReductionMode.value) {
            hasWarnedNaN_noiseReductionMode.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'noiseReductionMode'`);
          }
          return;
        }
        updateSharedValue(film.noiseReductionMode, value);
        };

        const updateNoiseReductionAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.noiseReductionAuto, value);
        };

        const updateTemperatureAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.temperatureAuto, value);
        };

        const updateIsSelfieCamera = (value: boolean) => {
        'worklet';
        updateSharedValue(film.isSelfieCamera, value);
        };

        const updateSaturation = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_saturation.value) {
            hasWarnedNaN_saturation.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'saturation'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.saturation, safeValue);
        config.saturation = safeValue;
        };

        const updateContrast = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_contrast.value) {
            hasWarnedNaN_contrast.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'contrast'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.contrast, safeValue);
        config.contrast = safeValue;
        updateSharedValue(film.contrastAuto, false);
        config.contrastAuto = false;
        };

        const updateGrainIntensity = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_grainIntensity.value) {
            hasWarnedNaN_grainIntensity.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'grainIntensity'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.grainIntensity, safeValue);
        config.grainIntensity = safeValue;
        updateSharedValue(film.grainEnabled, safeValue > 0);
        config.grainEnabled = safeValue > 0;
        };

        const updateGrainChroma = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_grainChroma.value) {
            hasWarnedNaN_grainChroma.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'grainChroma'`);
          }
          return;
        }
        updateSharedValue(film.grainChroma, value);
        config.grainChroma = value;
        };

        const updateGrainSize = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_grainSize.value) {
            hasWarnedNaN_grainSize.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'grainSize'`);
          }
          return;
        }
        updateSharedValue(film.grainSize, value);
        config.grainSize = value;
        };

        const updateGrainSpeed = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_grainSpeed.value) {
            hasWarnedNaN_grainSpeed.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'grainSpeed'`);
          }
          return;
        }
        updateSharedValue(film.grainSpeed, value);
        config.grainSpeed = value;
        };

        const updateVignetteIntensity = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_vignetteIntensity.value) {
            hasWarnedNaN_vignetteIntensity.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'vignetteIntensity'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 1.0);
        updateSharedValue(film.vignetteIntensity, safeValue);
        config.vignetteIntensity = safeValue;
        };

        const updateChromaShift = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_chromaShift.value) {
            hasWarnedNaN_chromaShift.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'chromaShift'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.chromaShift, safeValue);
        config.chromaShift = safeValue;
        };

        const updateTemperature = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_temperature.value) {
            hasWarnedNaN_temperature.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'temperature'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 2000.0), 10000.0);
        updateSharedValue(film.temperature, safeValue);
        config.whiteBalance = safeValue;
        updateSharedValue(film.temperatureAuto, false);
        };

        const updateTint = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_tint.value) {
            hasWarnedNaN_tint.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'tint'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, -100.0), 100.0);
        updateSharedValue(film.tint, safeValue);
        config.tint = safeValue;
        updateSharedValue(film.temperatureAuto, false);
        };

        const updateBloomIntensity = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_bloomIntensity.value) {
            hasWarnedNaN_bloomIntensity.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'bloomIntensity'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 9999.0);
        updateSharedValue(film.bloomIntensity, safeValue);
        config.bloomIntensity = safeValue;
        updateSharedValue(film.bloomEnabled, safeValue > 0);
        config.bloomEnabled = safeValue > 0;
        };

        const updateChromaticAberration = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_chromaticAberration.value) {
            hasWarnedNaN_chromaticAberration.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'chromaticAberration'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.chromaticAberration, safeValue);
        config.chromaticAberration = safeValue;
        };

        const updateChromaShiftDirection = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_chromaShiftDirection.value) {
            hasWarnedNaN_chromaShiftDirection.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'chromaShiftDirection'`);
          }
          return;
        }
        updateSharedValue(film.chromaShiftDirection, value);
        config.chromaShiftDirection = value;
        };

        const updateSharpening = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_sharpening.value) {
            hasWarnedNaN_sharpening.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'sharpening'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 1.0);
        updateSharedValue(film.sharpening, safeValue);
        config.sharpening = safeValue;
        };

        const updateSatRed = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satRed.value) {
            hasWarnedNaN_satRed.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satRed'`);
          }
          return;
        }
        updateSharedValue(film.satRed, value);
        config.satRed = value;
        };

        const updateSatOrange = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satOrange.value) {
            hasWarnedNaN_satOrange.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satOrange'`);
          }
          return;
        }
        updateSharedValue(film.satOrange, value);
        config.satOrange = value;
        };

        const updateSatYellow = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satYellow.value) {
            hasWarnedNaN_satYellow.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satYellow'`);
          }
          return;
        }
        updateSharedValue(film.satYellow, value);
        config.satYellow = value;
        };

        const updateSatGreen = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satGreen.value) {
            hasWarnedNaN_satGreen.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satGreen'`);
          }
          return;
        }
        updateSharedValue(film.satGreen, value);
        config.satGreen = value;
        };

        const updateSatCyan = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satCyan.value) {
            hasWarnedNaN_satCyan.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satCyan'`);
          }
          return;
        }
        updateSharedValue(film.satCyan, value);
        config.satCyan = value;
        };

        const updateSatBlue = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satBlue.value) {
            hasWarnedNaN_satBlue.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satBlue'`);
          }
          return;
        }
        updateSharedValue(film.satBlue, value);
        config.satBlue = value;
        };

        const updateSatPurple = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satPurple.value) {
            hasWarnedNaN_satPurple.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satPurple'`);
          }
          return;
        }
        updateSharedValue(film.satPurple, value);
        config.satPurple = value;
        };

        const updateSatMagenta = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_satMagenta.value) {
            hasWarnedNaN_satMagenta.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'satMagenta'`);
          }
          return;
        }
        updateSharedValue(film.satMagenta, value);
        config.satMagenta = value;
        };

        const updateAberrationInvert = (value: boolean) => {
        'worklet';
        updateSharedValue(film.aberrationInvert, value);
        config.aberrationInvert = value;
        };

        const updateBoundMagentaRed = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundMagentaRed.value) {
            hasWarnedNaN_boundMagentaRed.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundMagentaRed'`);
          }
          return;
        }
        updateSharedValue(film.boundMagentaRed, value);
        config.boundMagentaRed = value;
        };

        const updateBoundRedOrange = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundRedOrange.value) {
            hasWarnedNaN_boundRedOrange.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundRedOrange'`);
          }
          return;
        }
        updateSharedValue(film.boundRedOrange, value);
        config.boundRedOrange = value;
        };

        const updateBoundOrangeYellow = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundOrangeYellow.value) {
            hasWarnedNaN_boundOrangeYellow.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundOrangeYellow'`);
          }
          return;
        }
        updateSharedValue(film.boundOrangeYellow, value);
        config.boundOrangeYellow = value;
        };

        const updateBoundYellowGreen = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundYellowGreen.value) {
            hasWarnedNaN_boundYellowGreen.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundYellowGreen'`);
          }
          return;
        }
        updateSharedValue(film.boundYellowGreen, value);
        config.boundYellowGreen = value;
        };

        const updateBoundGreenCyan = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundGreenCyan.value) {
            hasWarnedNaN_boundGreenCyan.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundGreenCyan'`);
          }
          return;
        }
        updateSharedValue(film.boundGreenCyan, value);
        config.boundGreenCyan = value;
        };

        const updateBoundCyanBlue = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundCyanBlue.value) {
            hasWarnedNaN_boundCyanBlue.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundCyanBlue'`);
          }
          return;
        }
        updateSharedValue(film.boundCyanBlue, value);
        config.boundCyanBlue = value;
        };

        const updateBoundBluePurple = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundBluePurple.value) {
            hasWarnedNaN_boundBluePurple.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundBluePurple'`);
          }
          return;
        }
        updateSharedValue(film.boundBluePurple, value);
        config.boundBluePurple = value;
        };

        const updateBoundPurpleMagenta = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_boundPurpleMagenta.value) {
            hasWarnedNaN_boundPurpleMagenta.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'boundPurpleMagenta'`);
          }
          return;
        }
        updateSharedValue(film.boundPurpleMagenta, value);
        config.boundPurpleMagenta = value;
        };

        const updateGrainRoughness = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_grainRoughness.value) {
            hasWarnedNaN_grainRoughness.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'grainRoughness'`);
          }
          return;
        }
        updateSharedValue(film.grainRoughness, value);
        config.grainRoughness = value;
        };

        const updateGrainEnabled = (value: boolean) => {
        'worklet';
        updateSharedValue(film.grainEnabled, value);
        config.grainEnabled = value;
        };

        const updateBloomEnabled = (value: boolean) => {
        'worklet';
        updateSharedValue(film.bloomEnabled, value);
        config.bloomEnabled = value;
        };

        const updateBlackLevel = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_blackLevel.value) {
            hasWarnedNaN_blackLevel.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'blackLevel'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, -0.5), 0.5);
        updateSharedValue(film.blackLevel, safeValue);
        config.blackLevel = safeValue;
        updateSharedValue(film.blackLevelAuto, false);
        config.blackLevelAuto = false;
        };

        const updateHighlights = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_highlights.value) {
            hasWarnedNaN_highlights.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'highlights'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 2.0);
        updateSharedValue(film.highlights, safeValue);
        config.highlights = safeValue;
        updateSharedValue(film.highlightsAuto, false);
        config.highlightsAuto = false;
        };

        const updatePivot = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_pivot.value) {
            hasWarnedNaN_pivot.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'pivot'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 1.0);
        updateSharedValue(film.pivot, safeValue);
        config.pivot = safeValue;
        updateSharedValue(film.pivotAuto, false);
        config.pivotAuto = false;
        };

        const updateContrastAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.contrastAuto, value);
        config.contrastAuto = value;
        };

        const updateBlackLevelAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.blackLevelAuto, value);
        config.blackLevelAuto = value;
        };

        const updateHighlightsAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.highlightsAuto, value);
        config.highlightsAuto = value;
        };

        const updatePivotAuto = (value: boolean) => {
        'worklet';
        updateSharedValue(film.pivotAuto, value);
        config.pivotAuto = value;
        };

        const updatePixelationFactor = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_pixelationFactor.value) {
            hasWarnedNaN_pixelationFactor.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'pixelationFactor'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 1.0), 16.0);
        updateSharedValue(film.pixelationFactor, safeValue);
        config.pixelationFactor = safeValue;
        };

        const updateTapeJitter = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_tapeJitter.value) {
            hasWarnedNaN_tapeJitter.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'tapeJitter'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 1.0);
        updateSharedValue(film.tapeJitter, safeValue);
        config.tapeJitter = safeValue;
        };

        const updateScanlines = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_scanlines.value) {
            hasWarnedNaN_scanlines.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'scanlines'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, 0.0), 1.0);
        updateSharedValue(film.scanlines, safeValue);
        config.scanlines = safeValue;
        };

        const updateChromaShiftInvert = (value: boolean) => {
        'worklet';
        updateSharedValue(film.chromaShiftInvert, value);
        config.chromaShiftInvert = value;
        };

        const updateHue = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hue.value) {
            hasWarnedNaN_hue.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hue'`);
          }
          return;
        }
        const safeValue = Math.min(Math.max(value, -180.0), 180.0);
        updateSharedValue(film.hue, safeValue);
        config.hue = safeValue;
        };

        const updateHueRed = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueRed.value) {
            hasWarnedNaN_hueRed.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueRed'`);
          }
          return;
        }
        updateSharedValue(film.hueRed, value);
        config.hueRed = value;
        };

        const updateHueOrange = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueOrange.value) {
            hasWarnedNaN_hueOrange.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueOrange'`);
          }
          return;
        }
        updateSharedValue(film.hueOrange, value);
        config.hueOrange = value;
        };

        const updateHueYellow = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueYellow.value) {
            hasWarnedNaN_hueYellow.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueYellow'`);
          }
          return;
        }
        updateSharedValue(film.hueYellow, value);
        config.hueYellow = value;
        };

        const updateHueGreen = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueGreen.value) {
            hasWarnedNaN_hueGreen.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueGreen'`);
          }
          return;
        }
        updateSharedValue(film.hueGreen, value);
        config.hueGreen = value;
        };

        const updateHueCyan = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueCyan.value) {
            hasWarnedNaN_hueCyan.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueCyan'`);
          }
          return;
        }
        updateSharedValue(film.hueCyan, value);
        config.hueCyan = value;
        };

        const updateHueBlue = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueBlue.value) {
            hasWarnedNaN_hueBlue.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueBlue'`);
          }
          return;
        }
        updateSharedValue(film.hueBlue, value);
        config.hueBlue = value;
        };

        const updateHuePurple = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_huePurple.value) {
            hasWarnedNaN_huePurple.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'huePurple'`);
          }
          return;
        }
        updateSharedValue(film.huePurple, value);
        config.huePurple = value;
        };

        const updateHueMagenta = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_hueMagenta.value) {
            hasWarnedNaN_hueMagenta.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'hueMagenta'`);
          }
          return;
        }
        updateSharedValue(film.hueMagenta, value);
        config.hueMagenta = value;
        };

        const updateScanlinesHorizontal = (value: boolean) => {
        'worklet';
        updateSharedValue(film.scanlinesHorizontal, value);
        config.scanlinesHorizontal = value;
        };

        const updateScanlinesMode = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_scanlinesMode.value) {
            hasWarnedNaN_scanlinesMode.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'scanlinesMode'`);
          }
          return;
        }
        updateSharedValue(film.scanlinesMode, value);
        config.scanlinesMode = value;
        };

        const updateScanlinesDensity = (value: number) => {
        'worklet';
        if (isNaN(value)) {
          if (__DEV__ && !hasWarnedNaN_scanlinesDensity.value) {
            hasWarnedNaN_scanlinesDensity.value = true;
            console.warn(`[Camera Codegen Warning]: NaN value intercepted for parameter 'scanlinesDensity'`);
          }
          return;
        }
        updateSharedValue(film.scanlinesDensity, value);
        config.scanlinesDensity = value;
        };
    // @@GEN_WORKLETS_END@@

    return {
      // @@GEN_WORKLET_EXPORTS_START@@
      // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
      // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
      // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
      updateNoiseReductionMode,
            updateNoiseReductionAuto,
            updateTemperatureAuto,
            updateIsSelfieCamera,
            updateSaturation,
            updateContrast,
            updateGrainIntensity,
            updateGrainChroma,
            updateGrainSize,
            updateGrainSpeed,
            updateVignetteIntensity,
            updateChromaShift,
            updateTemperature,
            updateTint,
            updateBloomIntensity,
            updateChromaticAberration,
            updateChromaShiftDirection,
            updateSharpening,
            updateSatRed,
            updateSatOrange,
            updateSatYellow,
            updateSatGreen,
            updateSatCyan,
            updateSatBlue,
            updateSatPurple,
            updateSatMagenta,
            updateAberrationInvert,
            updateBoundMagentaRed,
            updateBoundRedOrange,
            updateBoundOrangeYellow,
            updateBoundYellowGreen,
            updateBoundGreenCyan,
            updateBoundCyanBlue,
            updateBoundBluePurple,
            updateBoundPurpleMagenta,
            updateGrainRoughness,
            updateGrainEnabled,
            updateBloomEnabled,
            updateBlackLevel,
            updateHighlights,
            updatePivot,
            updateContrastAuto,
            updateBlackLevelAuto,
            updateHighlightsAuto,
            updatePivotAuto,
            updatePixelationFactor,
            updateTapeJitter,
            updateScanlines,
            updateChromaShiftInvert,
            updateHue,
            updateHueRed,
            updateHueOrange,
            updateHueYellow,
            updateHueGreen,
            updateHueCyan,
            updateHueBlue,
            updateHuePurple,
            updateHueMagenta,
            updateScanlinesHorizontal,
            updateScanlinesMode,
            updateScanlinesDensity,
      // @@GEN_WORKLET_EXPORTS_END@@
    };
  }, []);
};
