import { useMemo } from 'react';
import { useShallow } from 'zustand/shallow';
import { useFilmStore } from '../model/useFilmStore';
import { useFilmWorklets } from './useFilmWorklets';
import { ParameterControlData } from '@shared/lib/parameter/types';
import { 
  DEFAULT_SATURATION,
  DEFAULT_GRAIN_INTENSITY,
  DEFAULT_VIGNETTE_INTENSITY,
  DEFAULT_CHROMA_SHIFT,
  DEFAULT_BLOOM_INTENSITY,
  DEFAULT_CHROMATIC_ABERRATION,
  DEFAULT_SHARPENING,
  DEFAULT_PIXELATION_FACTOR,
  DEFAULT_TAPE_JITTER,
  DEFAULT_SCANLINES,
  DEFAULT_HUE
} from '@grovkornet/shared';

export type FilmParameterType =
  // @@GEN_PARAMETER_TYPES_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  | 'saturation'
  | 'contrast'
  | 'grain'
  | 'vignette'
  | 'chroma_shift'
  | 'temperature'
  | 'tint'
  | 'bloom'
  | 'chromatic_aberration'
  | 'sharpening'
  | 'blackLevel'
  | 'highlights'
  | 'pivot'
  | 'pixelation'
  | 'tape_jitter'
  | 'scanlines'
  | 'hue'
// @@GEN_PARAMETER_TYPES_END@@
  ;

type SelectedFilmState = ReturnType<typeof useFilmStore.getState>;

export const useFilmParameterControlData = (
  parameter: FilmParameterType
): ParameterControlData => {
  const film = useFilmStore(
    useShallow((s) => {
      switch (parameter) {
        // @@GEN_STORE_SELECTION_START@@
        // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
        // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
        // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
                case 'saturation':
                  return {
                    saturation: s.saturation,
                    setSaturation: s.setSaturation
                  };
                case 'contrast':
                  return {
                    contrast: s.contrast,
                    setContrast: s.setContrast,
                    contrastAuto: s.contrastAuto,
                    setContrastAuto: s.setContrastAuto,
                    setPivotAuto: s.setPivotAuto
                  };
                case 'grain':
                  return {
                    grainIntensity: s.grainIntensity,
                    setGrainIntensity: s.setGrainIntensity
                  };
                case 'vignette':
                  return {
                    vignetteIntensity: s.vignetteIntensity,
                    setVignetteIntensity: s.setVignetteIntensity
                  };
                case 'chroma_shift':
                  return {
                    chromaShift: s.chromaShift,
                    setChromaShift: s.setChromaShift
                  };
                case 'temperature':
                  return {
                    temperature: s.temperature,
                    setTemperature: s.setTemperature,
                    temperatureAuto: s.temperatureAuto,
                    setTemperatureAuto: s.setTemperatureAuto
                  };
                case 'tint':
                  return {
                    tint: s.tint,
                    setTint: s.setTint,
                    temperatureAuto: s.temperatureAuto,
                    setTemperatureAuto: s.setTemperatureAuto
                  };
                case 'bloom':
                  return {
                    bloomIntensity: s.bloomIntensity,
                    setBloomIntensity: s.setBloomIntensity
                  };
                case 'chromatic_aberration':
                  return {
                    chromaticAberration: s.chromaticAberration,
                    setChromaticAberration: s.setChromaticAberration
                  };
                case 'sharpening':
                  return {
                    sharpening: s.sharpening,
                    setSharpening: s.setSharpening
                  };
                case 'blackLevel':
                  return {
                    blackLevel: s.blackLevel,
                    setBlackLevel: s.setBlackLevel,
                    blackLevelAuto: s.blackLevelAuto,
                    setBlackLevelAuto: s.setBlackLevelAuto
                  };
                case 'highlights':
                  return {
                    highlights: s.highlights,
                    setHighlights: s.setHighlights,
                    highlightsAuto: s.highlightsAuto,
                    setHighlightsAuto: s.setHighlightsAuto
                  };
                case 'pivot':
                  return {
                    pivot: s.pivot,
                    setPivot: s.setPivot,
                    pivotAuto: s.pivotAuto,
                    setPivotAuto: s.setPivotAuto
                  };
                case 'pixelation':
                  return {
                    pixelationFactor: s.pixelationFactor,
                    setPixelationFactor: s.setPixelationFactor
                  };
                case 'tape_jitter':
                  return {
                    tapeJitter: s.tapeJitter,
                    setTapeJitter: s.setTapeJitter
                  };
                case 'scanlines':
                  return {
                    scanlines: s.scanlines,
                    setScanlines: s.setScanlines
                  };
                case 'hue':
                  return {
                    hue: s.hue,
                    setHue: s.setHue
                  };
        // @@GEN_STORE_SELECTION_END@@
        default:
          return {};
      }
    })
  ) as unknown as SelectedFilmState;

  const filmWorklets = useFilmWorklets();

  return useMemo((): ParameterControlData => {
    switch (parameter) {
      // @@GEN_CONTROL_CASES_START@@
      // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
      // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
      // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
            case 'saturation':
              return {
                value: film.saturation,
                minValue: 0.0,
                maxValue: 2.0,
                centerValue: 1.0,
                onChange: film.setSaturation,
                onUpdateWorklet: filmWorklets.updateSaturation,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setSaturation(DEFAULT_SATURATION),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'contrast':
              return {
                value: film.contrast,
                minValue: 0.0,
                maxValue: 2.0,
                centerValue: 1.0,
                onChange: film.setContrast,
                onUpdateWorklet: filmWorklets.updateContrast,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => {
                  film.setContrastAuto(true);
                },
                onResetGroup: () => {
                  film.setContrastAuto(true);
                  film.setPivotAuto(true);
                },
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round(((v  -1) * 100));
                  return rounded > 0 ? `+${rounded}` : `${rounded}`;
                }
              };
            case 'grain':
              return {
                value: film.grainIntensity,
                minValue: 0.0,
                maxValue: 2.0,
                onChange: film.setGrainIntensity,
                onUpdateWorklet: filmWorklets.updateGrainIntensity,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setGrainIntensity(DEFAULT_GRAIN_INTENSITY),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'vignette':
              return {
                value: film.vignetteIntensity,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setVignetteIntensity,
                onUpdateWorklet: filmWorklets.updateVignetteIntensity,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setVignetteIntensity(DEFAULT_VIGNETTE_INTENSITY),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'chroma_shift':
              return {
                value: film.chromaShift,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setChromaShift,
                onUpdateWorklet: filmWorklets.updateChromaShift,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setChromaShift(DEFAULT_CHROMA_SHIFT),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'temperature':
              return {
                value: film.temperature,
                minValue: 2000.0,
                maxValue: 10000.0,
                onChange: film.setTemperature,
                onUpdateWorklet: filmWorklets.updateTemperature,
                isAuto: film.temperatureAuto,
                hideValueInAuto: true,
                autoValueText: 'AWB',
                onReset: () => film.setTemperatureAuto(true),
                onToggleAuto: film.setTemperatureAuto,
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round(v)}K`;
                }
              };
            case 'tint':
              return {
                value: film.tint,
                minValue: -100.0,
                maxValue: 100.0,
                centerValue: 0.0,
                onChange: film.setTint,
                onUpdateWorklet: filmWorklets.updateTint,
                isAuto: film.temperatureAuto,
                hideValueInAuto: true,
                autoValueText: 'AWB',
                onReset: () => film.setTemperatureAuto(true),
                onToggleAuto: film.setTemperatureAuto,
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round(v);
                  return rounded > 0 ? `+${rounded}` : `${rounded}`;
                }
              };
            case 'bloom':
              return {
                value: film.bloomIntensity,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setBloomIntensity,
                onUpdateWorklet: filmWorklets.updateBloomIntensity,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setBloomIntensity(DEFAULT_BLOOM_INTENSITY),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'chromatic_aberration':
              return {
                value: film.chromaticAberration,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setChromaticAberration,
                onUpdateWorklet: filmWorklets.updateChromaticAberration,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setChromaticAberration(DEFAULT_CHROMATIC_ABERRATION),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'sharpening':
              return {
                value: film.sharpening,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setSharpening,
                onUpdateWorklet: filmWorklets.updateSharpening,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setSharpening(DEFAULT_SHARPENING),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'blackLevel':
              return {
                value: film.blackLevel,
                minValue: -0.5,
                maxValue: 0.5,
                centerValue: 0.0,
                onChange: film.setBlackLevel,
                onUpdateWorklet: filmWorklets.updateBlackLevel,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => {
                  film.setBlackLevelAuto(true);
                },
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round((v * 200));
                  return rounded > 0 ? `+${rounded}` : `${rounded}`;
                }
              };
            case 'highlights':
              return {
                value: film.highlights,
                minValue: 0.0,
                maxValue: 2.0,
                centerValue: 1.0,
                onChange: film.setHighlights,
                onUpdateWorklet: filmWorklets.updateHighlights,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => {
                  film.setHighlightsAuto(true);
                },
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round(((v  -1) * 100));
                  return rounded > 0 ? `+${rounded}` : `${rounded}`;
                }
              };
            case 'pivot':
              return {
                value: film.pivot,
                minValue: 0.0,
                maxValue: 1.0,
                centerValue: 0.5,
                onChange: film.setPivot,
                onUpdateWorklet: filmWorklets.updatePivot,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => {
                  film.setPivotAuto(true);
                },
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round(((v  -0.5) * 200));
                  return rounded > 0 ? `+${rounded}` : `${rounded}`;
                }
              };
            case 'pixelation':
              return {
                value: film.pixelationFactor,
                minValue: 1.0,
                maxValue: 16.0,
                onChange: film.setPixelationFactor,
                onUpdateWorklet: filmWorklets.updatePixelationFactor,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setPixelationFactor(DEFAULT_PIXELATION_FACTOR),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round(v * 10) / 10}x`;
                }
              };
            case 'tape_jitter':
              return {
                value: film.tapeJitter,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setTapeJitter,
                onUpdateWorklet: filmWorklets.updateTapeJitter,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setTapeJitter(DEFAULT_TAPE_JITTER),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'scanlines':
              return {
                value: film.scanlines,
                minValue: 0.0,
                maxValue: 1.0,
                onChange: film.setScanlines,
                onUpdateWorklet: filmWorklets.updateScanlines,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setScanlines(DEFAULT_SCANLINES),
                valueFormatter: (v: number) => {
                  'worklet';
                  return `${Math.round((v * 100))}`;
                }
              };
            case 'hue':
              return {
                value: film.hue,
                minValue: -180.0,
                maxValue: 180.0,
                centerValue: 0.0,
                onChange: film.setHue,
                onUpdateWorklet: filmWorklets.updateHue,
                hideValueInAuto: false,
                autoValueText: 'AUTO',
                onReset: () => film.setHue(DEFAULT_HUE),
                valueFormatter: (v: number) => {
                  'worklet';
                  const rounded = Math.round(v);
                  return rounded > 0 ? `+${rounded}°` : `${rounded}°`;
                }
              };
      // @@GEN_CONTROL_CASES_END@@
      default:
        throw new Error(`Unhandled parameter type: ${parameter as string}`);
    }
  }, [parameter, film, filmWorklets]);
};
