package com.grovkornet.nativefilmcamera.state

import com.grovkornet.nativefilmcamera.jni.CameraStateJNI

/**
 * Single source of truth for all camera and rendering parameters.
 */
class CameraConfiguration(val nativePointer: Long = 0L) {
    // @@GEN_FIELDS_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    // Rendering / Effect Props
    var saturation: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSaturation(nativePointer) else (CameraStateJNI.fallbackGet("saturation", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSaturation(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("saturation", nativePointer, value)
                }
            }
    var contrast: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getContrast(nativePointer) else (CameraStateJNI.fallbackGet("contrast", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setContrast(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("contrast", nativePointer, value)
                }
            }
    var grainIntensity: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainIntensity(nativePointer) else (CameraStateJNI.fallbackGet("grainIntensity", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainIntensity(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainIntensity", nativePointer, value)
                }
            }
    var grainChroma: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainChroma(nativePointer) else (CameraStateJNI.fallbackGet("grainChroma", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainChroma(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainChroma", nativePointer, value)
                }
            }
    var grainSize: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainSize(nativePointer) else (CameraStateJNI.fallbackGet("grainSize", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainSize(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainSize", nativePointer, value)
                }
            }
    var grainSpeed: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainSpeed(nativePointer) else (CameraStateJNI.fallbackGet("grainSpeed", nativePointer, 20.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainSpeed(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainSpeed", nativePointer, value)
                }
            }
    var vignetteIntensity: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getVignetteIntensity(nativePointer) else (CameraStateJNI.fallbackGet("vignetteIntensity", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setVignetteIntensity(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("vignetteIntensity", nativePointer, value)
                }
            }
    var chromaShift: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getChromaShift(nativePointer) else (CameraStateJNI.fallbackGet("chromaShift", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setChromaShift(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("chromaShift", nativePointer, value)
                }
            }
    var temperature: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTemperature(nativePointer) else (CameraStateJNI.fallbackGet("temperature", nativePointer, 5000.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTemperature(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("temperature", nativePointer, value)
                }
            }
    var tint: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTint(nativePointer) else (CameraStateJNI.fallbackGet("tint", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTint(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("tint", nativePointer, value)
                }
            }
    var bloomIntensity: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBloomIntensity(nativePointer) else (CameraStateJNI.fallbackGet("bloomIntensity", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBloomIntensity(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("bloomIntensity", nativePointer, value)
                }
            }
    var aberration: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getAberration(nativePointer) else (CameraStateJNI.fallbackGet("aberration", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setAberration(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("aberration", nativePointer, value)
                }
            }
    var chromaShiftDirection: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getChromaShiftDirection(nativePointer) else (CameraStateJNI.fallbackGet("chromaShiftDirection", nativePointer, 0) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setChromaShiftDirection(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("chromaShiftDirection", nativePointer, value)
                }
            }
    var sharpening: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSharpening(nativePointer) else (CameraStateJNI.fallbackGet("sharpening", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSharpening(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("sharpening", nativePointer, value)
                }
            }
    var satRed: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatRed(nativePointer) else (CameraStateJNI.fallbackGet("satRed", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatRed(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satRed", nativePointer, value)
                }
            }
    var satOrange: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatOrange(nativePointer) else (CameraStateJNI.fallbackGet("satOrange", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatOrange(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satOrange", nativePointer, value)
                }
            }
    var satYellow: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatYellow(nativePointer) else (CameraStateJNI.fallbackGet("satYellow", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatYellow(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satYellow", nativePointer, value)
                }
            }
    var satGreen: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatGreen(nativePointer) else (CameraStateJNI.fallbackGet("satGreen", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatGreen(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satGreen", nativePointer, value)
                }
            }
    var satCyan: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatCyan(nativePointer) else (CameraStateJNI.fallbackGet("satCyan", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatCyan(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satCyan", nativePointer, value)
                }
            }
    var satBlue: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatBlue(nativePointer) else (CameraStateJNI.fallbackGet("satBlue", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatBlue(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satBlue", nativePointer, value)
                }
            }
    var satPurple: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatPurple(nativePointer) else (CameraStateJNI.fallbackGet("satPurple", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatPurple(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satPurple", nativePointer, value)
                }
            }
    var satMagenta: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSatMagenta(nativePointer) else (CameraStateJNI.fallbackGet("satMagenta", nativePointer, 50.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSatMagenta(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("satMagenta", nativePointer, value)
                }
            }
    var aberrationInvert: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getAberrationInvert(nativePointer) else (CameraStateJNI.fallbackGet("aberrationInvert", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setAberrationInvert(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("aberrationInvert", nativePointer, value)
                }
            }
    var boundMagentaRed: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundMagentaRed(nativePointer) else (CameraStateJNI.fallbackGet("boundMagentaRed", nativePointer, 350.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundMagentaRed(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundMagentaRed", nativePointer, value)
                }
            }
    var boundRedOrange: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundRedOrange(nativePointer) else (CameraStateJNI.fallbackGet("boundRedOrange", nativePointer, 40.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundRedOrange(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundRedOrange", nativePointer, value)
                }
            }
    var boundOrangeYellow: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundOrangeYellow(nativePointer) else (CameraStateJNI.fallbackGet("boundOrangeYellow", nativePointer, 70.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundOrangeYellow(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundOrangeYellow", nativePointer, value)
                }
            }
    var boundYellowGreen: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundYellowGreen(nativePointer) else (CameraStateJNI.fallbackGet("boundYellowGreen", nativePointer, 110.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundYellowGreen(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundYellowGreen", nativePointer, value)
                }
            }
    var boundGreenCyan: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundGreenCyan(nativePointer) else (CameraStateJNI.fallbackGet("boundGreenCyan", nativePointer, 170.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundGreenCyan(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundGreenCyan", nativePointer, value)
                }
            }
    var boundCyanBlue: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundCyanBlue(nativePointer) else (CameraStateJNI.fallbackGet("boundCyanBlue", nativePointer, 230.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundCyanBlue(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundCyanBlue", nativePointer, value)
                }
            }
    var boundBluePurple: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundBluePurple(nativePointer) else (CameraStateJNI.fallbackGet("boundBluePurple", nativePointer, 280.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundBluePurple(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundBluePurple", nativePointer, value)
                }
            }
    var boundPurpleMagenta: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBoundPurpleMagenta(nativePointer) else (CameraStateJNI.fallbackGet("boundPurpleMagenta", nativePointer, 315.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBoundPurpleMagenta(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("boundPurpleMagenta", nativePointer, value)
                }
            }
    var grainRoughness: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainRoughness(nativePointer) else (CameraStateJNI.fallbackGet("grainRoughness", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainRoughness(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainRoughness", nativePointer, value)
                }
            }
    var panelY: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getPanelY(nativePointer) else (CameraStateJNI.fallbackGet("panelY", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setPanelY(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("panelY", nativePointer, value)
                }
            }
    var grainEnabled: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getGrainEnabled(nativePointer) else (CameraStateJNI.fallbackGet("grainEnabled", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setGrainEnabled(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("grainEnabled", nativePointer, value)
                }
            }
    var bloomEnabled: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBloomEnabled(nativePointer) else (CameraStateJNI.fallbackGet("bloomEnabled", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBloomEnabled(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("bloomEnabled", nativePointer, value)
                }
            }
    var blackLevel: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBlackLevel(nativePointer) else (CameraStateJNI.fallbackGet("blackLevel", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBlackLevel(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("blackLevel", nativePointer, value)
                }
            }
    var highlights: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHighlights(nativePointer) else (CameraStateJNI.fallbackGet("highlights", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHighlights(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("highlights", nativePointer, value)
                }
            }
    var pivot: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getPivot(nativePointer) else (CameraStateJNI.fallbackGet("pivot", nativePointer, 0.5f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setPivot(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("pivot", nativePointer, value)
                }
            }
    var contrastAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getContrastAuto(nativePointer) else (CameraStateJNI.fallbackGet("contrastAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setContrastAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("contrastAuto", nativePointer, value)
                }
            }
    var blackLevelAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBlackLevelAuto(nativePointer) else (CameraStateJNI.fallbackGet("blackLevelAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBlackLevelAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("blackLevelAuto", nativePointer, value)
                }
            }
    var highlightsAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHighlightsAuto(nativePointer) else (CameraStateJNI.fallbackGet("highlightsAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHighlightsAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("highlightsAuto", nativePointer, value)
                }
            }
    var pivotAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getPivotAuto(nativePointer) else (CameraStateJNI.fallbackGet("pivotAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setPivotAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("pivotAuto", nativePointer, value)
                }
            }
    var pixelationFactor: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getPixelationFactor(nativePointer) else (CameraStateJNI.fallbackGet("pixelationFactor", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setPixelationFactor(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("pixelationFactor", nativePointer, value)
                }
            }
    var tapeJitter: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTapeJitter(nativePointer) else (CameraStateJNI.fallbackGet("tapeJitter", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTapeJitter(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("tapeJitter", nativePointer, value)
                }
            }
    var scanlines: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getScanlines(nativePointer) else (CameraStateJNI.fallbackGet("scanlines", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setScanlines(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("scanlines", nativePointer, value)
                }
            }
    var chromaShiftInvert: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getChromaShiftInvert(nativePointer) else (CameraStateJNI.fallbackGet("chromaShiftInvert", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setChromaShiftInvert(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("chromaShiftInvert", nativePointer, value)
                }
            }
    var hue: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHue(nativePointer) else (CameraStateJNI.fallbackGet("hue", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHue(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hue", nativePointer, value)
                }
            }
    var hueRed: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueRed(nativePointer) else (CameraStateJNI.fallbackGet("hueRed", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueRed(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueRed", nativePointer, value)
                }
            }
    var hueOrange: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueOrange(nativePointer) else (CameraStateJNI.fallbackGet("hueOrange", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueOrange(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueOrange", nativePointer, value)
                }
            }
    var hueYellow: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueYellow(nativePointer) else (CameraStateJNI.fallbackGet("hueYellow", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueYellow(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueYellow", nativePointer, value)
                }
            }
    var hueGreen: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueGreen(nativePointer) else (CameraStateJNI.fallbackGet("hueGreen", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueGreen(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueGreen", nativePointer, value)
                }
            }
    var hueCyan: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueCyan(nativePointer) else (CameraStateJNI.fallbackGet("hueCyan", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueCyan(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueCyan", nativePointer, value)
                }
            }
    var hueBlue: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueBlue(nativePointer) else (CameraStateJNI.fallbackGet("hueBlue", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueBlue(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueBlue", nativePointer, value)
                }
            }
    var huePurple: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHuePurple(nativePointer) else (CameraStateJNI.fallbackGet("huePurple", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHuePurple(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("huePurple", nativePointer, value)
                }
            }
    var hueMagenta: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHueMagenta(nativePointer) else (CameraStateJNI.fallbackGet("hueMagenta", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHueMagenta(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("hueMagenta", nativePointer, value)
                }
            }
    var scanlinesHorizontal: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getScanlinesHorizontal(nativePointer) else (CameraStateJNI.fallbackGet("scanlinesHorizontal", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setScanlinesHorizontal(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("scanlinesHorizontal", nativePointer, value)
                }
            }
    var scanlinesMode: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getScanlinesMode(nativePointer) else (CameraStateJNI.fallbackGet("scanlinesMode", nativePointer, 0) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setScanlinesMode(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("scanlinesMode", nativePointer, value)
                }
            }
    var scanlinesDensity: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getScanlinesDensity(nativePointer) else (CameraStateJNI.fallbackGet("scanlinesDensity", nativePointer, 800.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setScanlinesDensity(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("scanlinesDensity", nativePointer, value)
                }
            }
    var lensDistortion: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getLensDistortion(nativePointer) else (CameraStateJNI.fallbackGet("lensDistortion", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setLensDistortion(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("lensDistortion", nativePointer, value)
                }
            }
    var halationIntensity: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHalationIntensity(nativePointer) else (CameraStateJNI.fallbackGet("halationIntensity", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHalationIntensity(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("halationIntensity", nativePointer, value)
                }
            }
    var halationEnabled: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHalationEnabled(nativePointer) else (CameraStateJNI.fallbackGet("halationEnabled", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHalationEnabled(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("halationEnabled", nativePointer, value)
                }
            }
    var halationThreshold: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getHalationThreshold(nativePointer) else (CameraStateJNI.fallbackGet("halationThreshold", nativePointer, 0.5f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setHalationThreshold(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("halationThreshold", nativePointer, value)
                }
            }
    var bloomThreshold: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getBloomThreshold(nativePointer) else (CameraStateJNI.fallbackGet("bloomThreshold", nativePointer, 0.5f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setBloomThreshold(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("bloomThreshold", nativePointer, value)
                }
            }

    // Hardware Props
    var ev: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getEv(nativePointer) else (CameraStateJNI.fallbackGet("ev", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setEv(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("ev", nativePointer, value)
                }
            }
    var targetFps: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTargetFps(nativePointer) else (CameraStateJNI.fallbackGet("targetFps", nativePointer, 60) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTargetFps(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("targetFps", nativePointer, value)
                }
            }
    var aspectRatio: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getAspectRatio(nativePointer) else (CameraStateJNI.fallbackGet("aspectRatio", nativePointer, 1) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setAspectRatio(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("aspectRatio", nativePointer, value)
                }
            }
    var noiseReduction: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getNoiseReduction(nativePointer) else (CameraStateJNI.fallbackGet("noiseReduction", nativePointer, 0) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setNoiseReduction(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("noiseReduction", nativePointer, value)
                }
            }
    var noiseReductionAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getNoiseReductionAuto(nativePointer) else (CameraStateJNI.fallbackGet("noiseReductionAuto", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setNoiseReductionAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("noiseReductionAuto", nativePointer, value)
                }
            }
    var isoAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getIsoAuto(nativePointer) else (CameraStateJNI.fallbackGet("isoAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setIsoAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("isoAuto", nativePointer, value)
                }
            }
    var shutterSpeedAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getShutterSpeedAuto(nativePointer) else (CameraStateJNI.fallbackGet("shutterSpeedAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setShutterSpeedAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("shutterSpeedAuto", nativePointer, value)
                }
            }
    var temperatureAuto: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTemperatureAuto(nativePointer) else (CameraStateJNI.fallbackGet("temperatureAuto", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTemperatureAuto(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("temperatureAuto", nativePointer, value)
                }
            }
    var autoFocus: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getAutoFocus(nativePointer) else (CameraStateJNI.fallbackGet("autoFocus", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setAutoFocus(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("autoFocus", nativePointer, value)
                }
            }
    var iso: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getIso(nativePointer) else (CameraStateJNI.fallbackGet("iso", nativePointer, 400) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setIso(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("iso", nativePointer, value)
                }
            }
    var exposureTime: Long
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getExposureTime(nativePointer) else (CameraStateJNI.fallbackGet("exposureTime", nativePointer, 1000000000L / 60L) as Long)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setExposureTime(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("exposureTime", nativePointer, value)
                }
            }
    var focusDistance: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getFocusDistance(nativePointer) else (CameraStateJNI.fallbackGet("focusDistance", nativePointer, 0.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setFocusDistance(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("focusDistance", nativePointer, value)
                }
            }
    var torchEnabled: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTorchEnabled(nativePointer) else (CameraStateJNI.fallbackGet("torchEnabled", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTorchEnabled(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("torchEnabled", nativePointer, value)
                }
            }
    var torchStrength: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getTorchStrength(nativePointer) else (CameraStateJNI.fallbackGet("torchStrength", nativePointer, 1) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setTorchStrength(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("torchStrength", nativePointer, value)
                }
            }
    var cameraId: String?
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getCameraId(nativePointer) else (CameraStateJNI.fallbackGet("cameraId", nativePointer, null) as String?)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setCameraId(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("cameraId", nativePointer, value)
                }
            }
    var resolutionSetting: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getResolutionSetting(nativePointer) else (CameraStateJNI.fallbackGet("resolutionSetting", nativePointer, 2) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setResolutionSetting(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("resolutionSetting", nativePointer, value)
                }
            }
    var previewQuality: Int
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getPreviewQuality(nativePointer) else (CameraStateJNI.fallbackGet("previewQuality", nativePointer, 1) as Int)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setPreviewQuality(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("previewQuality", nativePointer, value)
                }
            }
    var force60fpsCrop: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getForce60fpsCrop(nativePointer) else (CameraStateJNI.fallbackGet("force60fpsCrop", nativePointer, true) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setForce60fpsCrop(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("force60fpsCrop", nativePointer, value)
                }
            }
    var secureViewEnabled: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getSecureViewEnabled(nativePointer) else (CameraStateJNI.fallbackGet("secureViewEnabled", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setSecureViewEnabled(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("secureViewEnabled", nativePointer, value)
                }
            }
    var isSelfieCamera: Boolean
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getIsSelfieCamera(nativePointer) else (CameraStateJNI.fallbackGet("isSelfieCamera", nativePointer, false) as Boolean)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setIsSelfieCamera(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("isSelfieCamera", nativePointer, value)
                }
            }
    var zoom: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getZoom(nativePointer) else (CameraStateJNI.fallbackGet("zoom", nativePointer, 1.0f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setZoom(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("zoom", nativePointer, value)
                }
            }

    // Viewport Props
    var viewportWidth: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getViewportWidth(nativePointer) else (CameraStateJNI.fallbackGet("viewportWidth", nativePointer, 1080f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setViewportWidth(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("viewportWidth", nativePointer, value)
                }
            }
    var viewportHeight: Float
            get() = if (CameraStateJNI.isJniLoaded) CameraStateJNI.getViewportHeight(nativePointer) else (CameraStateJNI.fallbackGet("viewportHeight", nativePointer, 1920f) as Float)
            set(value) {
                if (CameraStateJNI.isJniLoaded) {
                    CameraStateJNI.setViewportHeight(nativePointer, value)
                } else {
                    CameraStateJNI.fallbackSet("viewportHeight", nativePointer, value)
                }
            }
    // @@GEN_FIELDS_END@@
}

fun CameraConfiguration.getTargetResolutionValue(): Float {
    return when (resolutionSetting) {
        0 -> 2160f
        1 -> 1440f
        2 -> 1080f
        3 -> 720f
        4 -> 480f
        5 -> 360f
        6 -> 240f
        7 -> 144f
        else -> 1080f
    }
}



fun CameraConfiguration.loadFromMap(payload: Map<String, Any>) {
    // @@GEN_MAP_LOADER_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    payload["ev"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { ev = it }
    }
    val raw_targetFps = payload["fpsSetting"] ?: payload["targetFps"]
    raw_targetFps?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { targetFps = it }
    }
    val raw_aspectRatio = payload["aspectRatio"] ?: payload["cameraAspectRatio"]
    raw_aspectRatio?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { aspectRatio = it }
    }
    val raw_noiseReduction = payload["noiseReductionMode"] ?: payload["noiseReduction"]
    raw_noiseReduction?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { noiseReduction = it }
    }
    payload["noiseReductionAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { noiseReductionAuto = it }
    }
    payload["isoAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { isoAuto = it }
    }
    payload["shutterSpeedAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { shutterSpeedAuto = it }
    }
    payload["temperatureAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { temperatureAuto = it }
    }
    val raw_autoFocus = payload["focusAuto"] ?: payload["autoFocus"]
    raw_autoFocus?.let { rawValue ->
        (rawValue as? Boolean)?.let { autoFocus = it }
    }
    payload["iso"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { iso = it }
    }
    val raw_exposureTime = payload["shutterSpeed"] ?: payload["exposureTime"]
    raw_exposureTime?.let { rawValue ->
        (rawValue as? Number)?.toLong()?.let { exposureTime = it }
    }
    payload["focusDistance"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { focusDistance = it }
    }
    val raw_torchEnabled = payload["torchState"] ?: payload["torchEnabled"]
    raw_torchEnabled?.let { rawValue ->
        (rawValue as? Boolean)?.let { torchEnabled = it }
    }
    payload["torchStrength"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { torchStrength = it }
    }
    payload["cameraId"]?.let { rawValue ->
        (rawValue as? String)?.let { cameraId = it }
    }
    payload["resolutionSetting"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { resolutionSetting = it }
    }
    payload["previewQuality"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { previewQuality = it }
    }
    payload["force60fpsCrop"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { force60fpsCrop = it }
    }
    payload["secureViewEnabled"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { secureViewEnabled = it }
    }
    payload["isSelfieCamera"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { isSelfieCamera = it }
    }
    payload["zoom"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { zoom = it }
    }
    payload["saturation"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { saturation = it }
    }
    payload["contrast"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { contrast = it }
    }
    payload["grainIntensity"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { grainIntensity = it }
    }
    payload["grainChroma"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { grainChroma = it }
    }
    payload["grainSize"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { grainSize = it }
    }
    payload["grainSpeed"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { grainSpeed = it }
    }
    payload["vignetteIntensity"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { vignetteIntensity = it }
    }
    payload["chromaShift"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { chromaShift = it }
    }
    payload["temperature"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { temperature = it }
    }
    payload["tint"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { tint = it }
    }
    payload["bloomIntensity"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { bloomIntensity = it }
    }
    payload["chromaticAberration"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { aberration = it }
    }
    payload["chromaShiftDirection"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { chromaShiftDirection = it }
    }
    payload["sharpening"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { sharpening = it }
    }
    payload["satRed"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satRed = it }
    }
    payload["satOrange"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satOrange = it }
    }
    payload["satYellow"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satYellow = it }
    }
    payload["satGreen"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satGreen = it }
    }
    payload["satCyan"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satCyan = it }
    }
    payload["satBlue"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satBlue = it }
    }
    payload["satPurple"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satPurple = it }
    }
    payload["satMagenta"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { satMagenta = it }
    }
    payload["aberrationInvert"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { aberrationInvert = it }
    }
    payload["boundMagentaRed"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundMagentaRed = it }
    }
    payload["boundRedOrange"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundRedOrange = it }
    }
    payload["boundOrangeYellow"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundOrangeYellow = it }
    }
    payload["boundYellowGreen"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundYellowGreen = it }
    }
    payload["boundGreenCyan"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundGreenCyan = it }
    }
    payload["boundCyanBlue"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundCyanBlue = it }
    }
    payload["boundBluePurple"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundBluePurple = it }
    }
    payload["boundPurpleMagenta"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { boundPurpleMagenta = it }
    }
    payload["grainRoughness"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { grainRoughness = it }
    }
    payload["panelY"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { panelY = it }
    }
    payload["grainEnabled"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { grainEnabled = it }
    }
    payload["bloomEnabled"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { bloomEnabled = it }
    }
    payload["blackLevel"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { blackLevel = it }
    }
    payload["highlights"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { highlights = it }
    }
    payload["pivot"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { pivot = it }
    }
    payload["contrastAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { contrastAuto = it }
    }
    payload["blackLevelAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { blackLevelAuto = it }
    }
    payload["highlightsAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { highlightsAuto = it }
    }
    payload["pivotAuto"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { pivotAuto = it }
    }
    payload["pixelationFactor"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { pixelationFactor = it }
    }
    payload["tapeJitter"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { tapeJitter = it }
    }
    payload["scanlines"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { scanlines = it }
    }
    payload["chromaShiftInvert"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { chromaShiftInvert = it }
    }
    payload["hue"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hue = it }
    }
    payload["hueRed"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueRed = it }
    }
    payload["hueOrange"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueOrange = it }
    }
    payload["hueYellow"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueYellow = it }
    }
    payload["hueGreen"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueGreen = it }
    }
    payload["hueCyan"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueCyan = it }
    }
    payload["hueBlue"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueBlue = it }
    }
    payload["huePurple"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { huePurple = it }
    }
    payload["hueMagenta"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { hueMagenta = it }
    }
    payload["scanlinesHorizontal"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { scanlinesHorizontal = it }
    }
    payload["scanlinesMode"]?.let { rawValue ->
        (rawValue as? Number)?.toInt()?.let { scanlinesMode = it }
    }
    payload["scanlinesDensity"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { scanlinesDensity = it }
    }
    payload["lensDistortion"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { lensDistortion = it }
    }
    payload["halationIntensity"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { halationIntensity = it }
    }
    payload["halationEnabled"]?.let { rawValue ->
        (rawValue as? Boolean)?.let { halationEnabled = it }
    }
    payload["halationThreshold"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { halationThreshold = it }
    }
    payload["bloomThreshold"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { bloomThreshold = it }
    }
    payload["viewportWidth"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { viewportWidth = it }
    }
    payload["viewportHeight"]?.let { rawValue ->
        (rawValue as? Number)?.toFloat()?.let { viewportHeight = it }
    }
    // @@GEN_MAP_LOADER_END@@
}
