/**
 * @file i18next.d.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the translations in:
 * apps/mobile/src/app/providers/i18n/locales/en.json
 * 
 * To update, modify the JSON translation files and run:
 *   npm run codegen
 */

import 'react-i18next';
import en from './locales/en.json';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: typeof en;
  }
}
