package com.grovkornet.nativefilmcamera.errors

/**
 * @file CameraErrors.kt
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-errors.json
 * 
 * To add, edit, or remove camera errors, modify the JSON file above and run:
 *   npm run codegen
 * (or build/run the mobile app via npm run android / npm run ios)
 */
enum class CameraErrorCode(val code: Int, val severity: String) {
    E_CAMERA_UNAUTHORIZED(1001, "fatal"),
    E_SHADER_COMPILE_FAILED(1002, "fatal"),
    E_PRESET_PREVIEW_FAILED(1003, "warning"),
    E_FILE_DELETE_FAILED(1004, "warning"),
    E_ENGINE_LIBRARY_LOAD_FAILED(1005, "fatal"),
    E_CAMERA_BIND_FAILED(1006, "fatal"),
    E_GALLERY_WRITE_FAILED(1007, "warning"),
    E_WATERMARK_EMBED_FAILED(1008, "warning"),
    E_AUTHENTICITY_VERIFICATION_FAILED(1009, "warning"),
    E_TORCH_SET_FAILED(1010, "warning"),
    E_FILAMENT_INIT_FAILED(1011, "fatal"),
    E_PIPELINE_INIT_FAILED(1012, "fatal");
}
