// ⚠️ AI WARNING: Before modifying this global state store, query the dependency graph: node packages/shared/scripts/graphrag/query.js <query>
import { create } from 'zustand';
import { makeMutable } from 'react-native-reanimated';
import { logger } from '@shared/lib/logger';
import { FilmStore } from './types';
// @@GEN_IMPORTS_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
import {
  DEFAULT_NOISE_REDUCTION_MODE,
  DEFAULT_NOISE_REDUCTION_AUTO,
  DEFAULT_TEMPERATURE_AUTO,
  DEFAULT_IS_SELFIE_CAMERA,
  DEFAULT_SATURATION,
  DEFAULT_CONTRAST,
  DEFAULT_GRAIN_INTENSITY,
  DEFAULT_GRAIN_CHROMA,
  DEFAULT_GRAIN_SIZE,
  DEFAULT_GRAIN_SPEED,
  DEFAULT_VIGNETTE_INTENSITY,
  DEFAULT_CHROMA_SHIFT,
  DEFAULT_TEMPERATURE,
  DEFAULT_TINT,
  DEFAULT_BLOOM_INTENSITY,
  DEFAULT_CHROMATIC_ABERRATION,
  DEFAULT_CHROMA_SHIFT_DIRECTION,
  DEFAULT_SHARPENING,
  DEFAULT_SELECTIVE_SATURATION,
  DEFAULT_ABERRATION_INVERT,
  DEFAULT_BOUND_MAGENTA_RED,
  DEFAULT_BOUND_RED_ORANGE,
  DEFAULT_BOUND_ORANGE_YELLOW,
  DEFAULT_BOUND_YELLOW_GREEN,
  DEFAULT_BOUND_GREEN_CYAN,
  DEFAULT_BOUND_CYAN_BLUE,
  DEFAULT_BOUND_BLUE_PURPLE,
  DEFAULT_BOUND_PURPLE_MAGENTA,
  DEFAULT_GRAIN_ROUGHNESS,
  DEFAULT_GRAIN_ENABLED,
  DEFAULT_BLOOM_ENABLED,
  DEFAULT_BLACK_LEVEL,
  DEFAULT_HIGHLIGHTS,
  DEFAULT_PIVOT,
  DEFAULT_CONTRAST_AUTO,
  DEFAULT_BLACK_LEVEL_AUTO,
  DEFAULT_HIGHLIGHTS_AUTO,
  DEFAULT_PIVOT_AUTO,
  DEFAULT_PIXELATION_FACTOR,
  DEFAULT_TAPE_JITTER,
  DEFAULT_SCANLINES,
  DEFAULT_CHROMA_SHIFT_INVERT,
  DEFAULT_HUE,
  DEFAULT_SELECTIVE_HUE,
  DEFAULT_SCANLINES_HORIZONTAL,
  DEFAULT_SCANLINES_MODE,
  DEFAULT_SCANLINES_DENSITY,
  DEFAULT_LENS_DISTORTION,
  DEFAULT_HALATION_INTENSITY,
  DEFAULT_HALATION_ENABLED,
  DEFAULT_HALATION_THRESHOLD,
  DEFAULT_BLOOM_THRESHOLD,
  DEFAULT_CHROMA_BLEED
} from '@grovkornet/shared';
// @@GEN_IMPORTS_END@@

export const useFilmStore = create<FilmStore>((set, get) => ({
  // @@GEN_INIT_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  noiseReductionMode: makeMutable(DEFAULT_NOISE_REDUCTION_MODE),
  noiseReductionAuto: makeMutable(DEFAULT_NOISE_REDUCTION_AUTO),
  temperatureAuto: makeMutable(DEFAULT_TEMPERATURE_AUTO),
  isSelfieCamera: makeMutable(DEFAULT_IS_SELFIE_CAMERA),
  saturation: makeMutable(DEFAULT_SATURATION),
  contrast: makeMutable(DEFAULT_CONTRAST),
  grainIntensity: makeMutable(DEFAULT_GRAIN_INTENSITY),
  grainChroma: makeMutable(DEFAULT_GRAIN_CHROMA),
  grainSize: makeMutable(DEFAULT_GRAIN_SIZE),
  grainSpeed: makeMutable(DEFAULT_GRAIN_SPEED),
  vignetteIntensity: makeMutable(DEFAULT_VIGNETTE_INTENSITY),
  chromaShift: makeMutable(DEFAULT_CHROMA_SHIFT),
  temperature: makeMutable(DEFAULT_TEMPERATURE),
  tint: makeMutable(DEFAULT_TINT),
  bloomIntensity: makeMutable(DEFAULT_BLOOM_INTENSITY),
  chromaticAberration: makeMutable(DEFAULT_CHROMATIC_ABERRATION),
  chromaShiftDirection: makeMutable(DEFAULT_CHROMA_SHIFT_DIRECTION),
  sharpening: makeMutable(DEFAULT_SHARPENING),
  satRed: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satOrange: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satYellow: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satGreen: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satCyan: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satBlue: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satPurple: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  satMagenta: makeMutable(DEFAULT_SELECTIVE_SATURATION),
  aberrationInvert: makeMutable(DEFAULT_ABERRATION_INVERT),
  boundMagentaRed: makeMutable(DEFAULT_BOUND_MAGENTA_RED),
  boundRedOrange: makeMutable(DEFAULT_BOUND_RED_ORANGE),
  boundOrangeYellow: makeMutable(DEFAULT_BOUND_ORANGE_YELLOW),
  boundYellowGreen: makeMutable(DEFAULT_BOUND_YELLOW_GREEN),
  boundGreenCyan: makeMutable(DEFAULT_BOUND_GREEN_CYAN),
  boundCyanBlue: makeMutable(DEFAULT_BOUND_CYAN_BLUE),
  boundBluePurple: makeMutable(DEFAULT_BOUND_BLUE_PURPLE),
  boundPurpleMagenta: makeMutable(DEFAULT_BOUND_PURPLE_MAGENTA),
  grainRoughness: makeMutable(DEFAULT_GRAIN_ROUGHNESS),
  grainEnabled: makeMutable(DEFAULT_GRAIN_ENABLED),
  bloomEnabled: makeMutable(DEFAULT_BLOOM_ENABLED),
  blackLevel: makeMutable(DEFAULT_BLACK_LEVEL),
  highlights: makeMutable(DEFAULT_HIGHLIGHTS),
  pivot: makeMutable(DEFAULT_PIVOT),
  contrastAuto: makeMutable(DEFAULT_CONTRAST_AUTO),
  blackLevelAuto: makeMutable(DEFAULT_BLACK_LEVEL_AUTO),
  highlightsAuto: makeMutable(DEFAULT_HIGHLIGHTS_AUTO),
  pivotAuto: makeMutable(DEFAULT_PIVOT_AUTO),
  pixelationFactor: makeMutable(DEFAULT_PIXELATION_FACTOR),
  tapeJitter: makeMutable(DEFAULT_TAPE_JITTER),
  scanlines: makeMutable(DEFAULT_SCANLINES),
  chromaShiftInvert: makeMutable(DEFAULT_CHROMA_SHIFT_INVERT),
  hue: makeMutable(DEFAULT_HUE),
  hueRed: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueOrange: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueYellow: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueGreen: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueCyan: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueBlue: makeMutable(DEFAULT_SELECTIVE_HUE),
  huePurple: makeMutable(DEFAULT_SELECTIVE_HUE),
  hueMagenta: makeMutable(DEFAULT_SELECTIVE_HUE),
  scanlinesHorizontal: makeMutable(DEFAULT_SCANLINES_HORIZONTAL),
  scanlinesMode: makeMutable(DEFAULT_SCANLINES_MODE),
  scanlinesDensity: makeMutable(DEFAULT_SCANLINES_DENSITY),
  lensDistortion: makeMutable(DEFAULT_LENS_DISTORTION),
  halationIntensity: makeMutable(DEFAULT_HALATION_INTENSITY),
  halationEnabled: makeMutable(DEFAULT_HALATION_ENABLED),
  halationThreshold: makeMutable(DEFAULT_HALATION_THRESHOLD),
  bloomThreshold: makeMutable(DEFAULT_BLOOM_THRESHOLD),
  chromaBleed: makeMutable(DEFAULT_CHROMA_BLEED),
  deviceOrientation: makeMutable(0),
  // @@GEN_INIT_END@@
  capabilities: {
    availableNoiseReductionModes: [],
    availableEdgeModes: [],
  },

  // @@GEN_SETTERS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  setNoiseReductionMode: (mode) => {
    get().noiseReductionMode.value = mode;
    notifyFilmStoreListener('noiseReductionMode');
  },
  setNoiseReductionAuto: (value) => {
    get().noiseReductionAuto.value = value;
    notifyFilmStoreListener('noiseReductionAuto');
  },
  setTemperatureAuto: (value) => {
    const { temperatureAuto, temperature, tint } = get();
    temperatureAuto.value = value;
    if (value) {
      temperature.value = DEFAULT_TEMPERATURE;
      tint.value = DEFAULT_TINT;
    }

    notifyFilmStoreListener('temperatureAuto');
  },
  setIsSelfieCamera: (value) => {
    get().isSelfieCamera.value = value;
    notifyFilmStoreListener('isSelfieCamera');
  },
  setSaturation: (value) => {
    get().saturation.value = value;
    notifyFilmStoreListener('saturation');
  },
  setContrast: (value) => {
    const { contrast, contrastAuto } = get();
    contrast.value = value;
    contrastAuto.value = false;

    notifyFilmStoreListener('contrast');
  },
  setGrainIntensity: (value) => {
    const { grainIntensity, grainEnabled } = get();
    grainIntensity.value = value;
    grainEnabled.value = value > 0;

    notifyFilmStoreListener('grainIntensity');
  },
  setGrainChroma: (value) => {
    get().grainChroma.value = value;
    notifyFilmStoreListener('grainChroma');
  },
  setGrainSize: (value) => {
    get().grainSize.value = value;
    notifyFilmStoreListener('grainSize');
  },
  setGrainSpeed: (value) => {
    get().grainSpeed.value = value;
    notifyFilmStoreListener('grainSpeed');
  },
  setVignetteIntensity: (value) => {
    get().vignetteIntensity.value = value;
    notifyFilmStoreListener('vignetteIntensity');
  },
  setChromaShift: (value) => {
    get().chromaShift.value = value;
    notifyFilmStoreListener('chromaShift');
  },
  setTemperature: (value) => {
    const { temperature, temperatureAuto } = get();
    temperature.value = value;
    temperatureAuto.value = false;

    notifyFilmStoreListener('temperature');
  },
  setTint: (value) => {
    const { tint, temperatureAuto } = get();
    tint.value = value;
    temperatureAuto.value = false;

    notifyFilmStoreListener('tint');
  },
  setBloomIntensity: (value) => {
    const { bloomIntensity, bloomEnabled } = get();
    bloomIntensity.value = value;
    bloomEnabled.value = value > 0;

    notifyFilmStoreListener('bloomIntensity');
  },
  setChromaticAberration: (value) => {
    get().chromaticAberration.value = value;
    notifyFilmStoreListener('chromaticAberration');
  },
  setChromaShiftDirection: (value) => {
    get().chromaShiftDirection.value = value;
    notifyFilmStoreListener('chromaShiftDirection');
  },
  setSharpening: (value) => {
    get().sharpening.value = value;
    notifyFilmStoreListener('sharpening');
  },
  setSatRed: (value) => {
    get().satRed.value = value;
    notifyFilmStoreListener('satRed');
  },
  setSatOrange: (value) => {
    get().satOrange.value = value;
    notifyFilmStoreListener('satOrange');
  },
  setSatYellow: (value) => {
    get().satYellow.value = value;
    notifyFilmStoreListener('satYellow');
  },
  setSatGreen: (value) => {
    get().satGreen.value = value;
    notifyFilmStoreListener('satGreen');
  },
  setSatCyan: (value) => {
    get().satCyan.value = value;
    notifyFilmStoreListener('satCyan');
  },
  setSatBlue: (value) => {
    get().satBlue.value = value;
    notifyFilmStoreListener('satBlue');
  },
  setSatPurple: (value) => {
    get().satPurple.value = value;
    notifyFilmStoreListener('satPurple');
  },
  setSatMagenta: (value) => {
    get().satMagenta.value = value;
    notifyFilmStoreListener('satMagenta');
  },
  setAberrationInvert: (value) => {
    get().aberrationInvert.value = value;
    notifyFilmStoreListener('aberrationInvert');
  },
  setBoundMagentaRed: (value) => {
    get().boundMagentaRed.value = value;
    notifyFilmStoreListener('boundMagentaRed');
  },
  setBoundRedOrange: (value) => {
    get().boundRedOrange.value = value;
    notifyFilmStoreListener('boundRedOrange');
  },
  setBoundOrangeYellow: (value) => {
    get().boundOrangeYellow.value = value;
    notifyFilmStoreListener('boundOrangeYellow');
  },
  setBoundYellowGreen: (value) => {
    get().boundYellowGreen.value = value;
    notifyFilmStoreListener('boundYellowGreen');
  },
  setBoundGreenCyan: (value) => {
    get().boundGreenCyan.value = value;
    notifyFilmStoreListener('boundGreenCyan');
  },
  setBoundCyanBlue: (value) => {
    get().boundCyanBlue.value = value;
    notifyFilmStoreListener('boundCyanBlue');
  },
  setBoundBluePurple: (value) => {
    get().boundBluePurple.value = value;
    notifyFilmStoreListener('boundBluePurple');
  },
  setBoundPurpleMagenta: (value) => {
    get().boundPurpleMagenta.value = value;
    notifyFilmStoreListener('boundPurpleMagenta');
  },
  setGrainRoughness: (value) => {
    get().grainRoughness.value = value;
    notifyFilmStoreListener('grainRoughness');
  },
  setGrainEnabled: (value) => {
    get().grainEnabled.value = value;
    notifyFilmStoreListener('grainEnabled');
  },
  setBloomEnabled: (value) => {
    get().bloomEnabled.value = value;
    notifyFilmStoreListener('bloomEnabled');
  },
  setBlackLevel: (value) => {
    const { blackLevel, blackLevelAuto } = get();
    blackLevel.value = value;
    blackLevelAuto.value = false;

    notifyFilmStoreListener('blackLevel');
  },
  setHighlights: (value) => {
    const { highlights, highlightsAuto } = get();
    highlights.value = value;
    highlightsAuto.value = false;

    notifyFilmStoreListener('highlights');
  },
  setPivot: (value) => {
    const { pivot, pivotAuto } = get();
    pivot.value = value;
    pivotAuto.value = false;

    notifyFilmStoreListener('pivot');
  },
  setContrastAuto: (value) => {
    const { contrastAuto, contrast } = get();
    contrastAuto.value = value;
    if (value) {
      contrast.value = DEFAULT_CONTRAST;
    }

    notifyFilmStoreListener('contrastAuto');
  },
  setBlackLevelAuto: (value) => {
    const { blackLevelAuto, blackLevel } = get();
    blackLevelAuto.value = value;
    if (value) {
      blackLevel.value = DEFAULT_BLACK_LEVEL;
    }

    notifyFilmStoreListener('blackLevelAuto');
  },
  setHighlightsAuto: (value) => {
    const { highlightsAuto, highlights } = get();
    highlightsAuto.value = value;
    if (value) {
      highlights.value = DEFAULT_HIGHLIGHTS;
    }

    notifyFilmStoreListener('highlightsAuto');
  },
  setPivotAuto: (value) => {
    const { pivotAuto, pivot } = get();
    pivotAuto.value = value;
    if (value) {
      pivot.value = DEFAULT_PIVOT;
    }

    notifyFilmStoreListener('pivotAuto');
  },
  setPixelationFactor: (value) => {
    get().pixelationFactor.value = value;
    notifyFilmStoreListener('pixelationFactor');
  },
  setTapeJitter: (value) => {
    get().tapeJitter.value = value;
    notifyFilmStoreListener('tapeJitter');
  },
  setScanlines: (value) => {
    get().scanlines.value = value;
    notifyFilmStoreListener('scanlines');
  },
  setChromaShiftInvert: (value) => {
    get().chromaShiftInvert.value = value;
    notifyFilmStoreListener('chromaShiftInvert');
  },
  setHue: (value) => {
    get().hue.value = value;
    notifyFilmStoreListener('hue');
  },
  setHueRed: (value) => {
    get().hueRed.value = value;
    notifyFilmStoreListener('hueRed');
  },
  setHueOrange: (value) => {
    get().hueOrange.value = value;
    notifyFilmStoreListener('hueOrange');
  },
  setHueYellow: (value) => {
    get().hueYellow.value = value;
    notifyFilmStoreListener('hueYellow');
  },
  setHueGreen: (value) => {
    get().hueGreen.value = value;
    notifyFilmStoreListener('hueGreen');
  },
  setHueCyan: (value) => {
    get().hueCyan.value = value;
    notifyFilmStoreListener('hueCyan');
  },
  setHueBlue: (value) => {
    get().hueBlue.value = value;
    notifyFilmStoreListener('hueBlue');
  },
  setHuePurple: (value) => {
    get().huePurple.value = value;
    notifyFilmStoreListener('huePurple');
  },
  setHueMagenta: (value) => {
    get().hueMagenta.value = value;
    notifyFilmStoreListener('hueMagenta');
  },
  setScanlinesHorizontal: (value) => {
    get().scanlinesHorizontal.value = value;
    notifyFilmStoreListener('scanlinesHorizontal');
  },
  setScanlinesMode: (value) => {
    get().scanlinesMode.value = value;
    notifyFilmStoreListener('scanlinesMode');
  },
  setScanlinesDensity: (value) => {
    get().scanlinesDensity.value = value;
    notifyFilmStoreListener('scanlinesDensity');
  },
  setLensDistortion: (value) => {
    get().lensDistortion.value = value;
    notifyFilmStoreListener('lensDistortion');
  },
  setHalationIntensity: (value) => {
    const { halationIntensity, halationEnabled } = get();
    halationIntensity.value = value;
    halationEnabled.value = value > 0;

    notifyFilmStoreListener('halationIntensity');
  },
  setHalationEnabled: (value) => {
    get().halationEnabled.value = value;
    notifyFilmStoreListener('halationEnabled');
  },
  setHalationThreshold: (value) => {
    get().halationThreshold.value = value;
    notifyFilmStoreListener('halationThreshold');
  },
  setBloomThreshold: (value) => {
    get().bloomThreshold.value = value;
    notifyFilmStoreListener('bloomThreshold');
  },
  setChromaBleed: (value) => {
    get().chromaBleed.value = value;
    notifyFilmStoreListener('chromaBleed');
  },
  setDeviceOrientation: (value) => {
    get().deviceOrientation.value = value;
    notifyFilmStoreListener('deviceOrientation');
  },
  // @@GEN_SETTERS_END@@
  setCapabilities: (caps) => {
    logger.info('FilmStore', 'Capabilities updated for Film');
    set((state) => ({
      capabilities: {
        ...state.capabilities,
        ...caps,
      }
    }));
  },
}));

let changeListener: ((paramName?: string) => void) | null = null;
export const setFilmStoreListener = (l: (paramName?: string) => void) => { changeListener = l; };
export const notifyFilmStoreListener = (paramName?: string) => { changeListener?.(paramName); };


