/**
 * @file errors.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-errors.yaml
 * 
 * To add, edit, or remove camera errors, modify the YAML file above and run:
 *   npm run codegen
 * (or build/run the mobile app via npm run android)
 */

export enum CameraErrorCode {
  E_CAMERA_UNAUTHORIZED = 'E_CAMERA_UNAUTHORIZED',
  E_SHADER_COMPILE_FAILED = 'E_SHADER_COMPILE_FAILED',
  E_PRESET_PREVIEW_FAILED = 'E_PRESET_PREVIEW_FAILED',
  E_FILE_DELETE_FAILED = 'E_FILE_DELETE_FAILED',
  E_ENGINE_LIBRARY_LOAD_FAILED = 'E_ENGINE_LIBRARY_LOAD_FAILED',
  E_CAMERA_BIND_FAILED = 'E_CAMERA_BIND_FAILED',
  E_GALLERY_WRITE_FAILED = 'E_GALLERY_WRITE_FAILED',
  E_WATERMARK_EMBED_FAILED = 'E_WATERMARK_EMBED_FAILED',
  E_AUTHENTICITY_VERIFICATION_FAILED = 'E_AUTHENTICITY_VERIFICATION_FAILED',
  E_TORCH_SET_FAILED = 'E_TORCH_SET_FAILED',
  E_FILAMENT_INIT_FAILED = 'E_FILAMENT_INIT_FAILED',
  E_PIPELINE_INIT_FAILED = 'E_PIPELINE_INIT_FAILED',
  E_LOW_MEMORY = 'E_LOW_MEMORY',
  E_THERMAL_THROTTLING = 'E_THERMAL_THROTTLING',
  E_ZOOM_OUT_OF_BOUNDS = 'E_ZOOM_OUT_OF_BOUNDS',
  E_RESOLUTION_NOT_SUPPORTED = 'E_RESOLUTION_NOT_SUPPORTED',
}

export interface CameraErrorDetail {
  code: number;
  severity: 'fatal' | 'warning';
  category: string;
  requiredParams: string[];
  description: string;
}

export const CAMERA_ERROR_DETAILS: Record<CameraErrorCode, CameraErrorDetail> = {
  [CameraErrorCode.E_CAMERA_UNAUTHORIZED]: {
    code: 1001,
    severity: 'fatal',
    category: 'permissions',
    requiredParams: [],
    description: "The user has not granted camera permissions."
  },
  [CameraErrorCode.E_SHADER_COMPILE_FAILED]: {
    code: 1002,
    severity: 'fatal',
    category: 'rendering',
    requiredParams: ["shaderName","compileLog"],
    description: "Failed to compile rendering shader."
  },
  [CameraErrorCode.E_PRESET_PREVIEW_FAILED]: {
    code: 1003,
    severity: 'warning',
    category: 'preset',
    requiredParams: ["reason"],
    description: "Failed to generate preset preview."
  },
  [CameraErrorCode.E_FILE_DELETE_FAILED]: {
    code: 1004,
    severity: 'warning',
    category: 'io',
    requiredParams: ["uri","reason"],
    description: "Failed to delete file."
  },
  [CameraErrorCode.E_ENGINE_LIBRARY_LOAD_FAILED]: {
    code: 1005,
    severity: 'fatal',
    category: 'system',
    requiredParams: ["reason"],
    description: "Failed to load native library grovkornet-engine."
  },
  [CameraErrorCode.E_CAMERA_BIND_FAILED]: {
    code: 1006,
    severity: 'fatal',
    category: 'system',
    requiredParams: ["reason"],
    description: "Failed to bind camera capture and preview use cases."
  },
  [CameraErrorCode.E_GALLERY_WRITE_FAILED]: {
    code: 1007,
    severity: 'warning',
    category: 'io',
    requiredParams: ["reason"],
    description: "Failed to save image to system gallery."
  },
  [CameraErrorCode.E_WATERMARK_EMBED_FAILED]: {
    code: 1008,
    severity: 'warning',
    category: 'authenticity',
    requiredParams: ["reason"],
    description: "Failed to embed native watermark signature on the image."
  },
  [CameraErrorCode.E_AUTHENTICITY_VERIFICATION_FAILED]: {
    code: 1009,
    severity: 'warning',
    category: 'authenticity',
    requiredParams: ["reason"],
    description: "Photo authenticity verification failed."
  },
  [CameraErrorCode.E_TORCH_SET_FAILED]: {
    code: 1010,
    severity: 'warning',
    category: 'hardware',
    requiredParams: ["reason"],
    description: "Failed to set flash/torch mode."
  },
  [CameraErrorCode.E_FILAMENT_INIT_FAILED]: {
    code: 1011,
    severity: 'fatal',
    category: 'rendering',
    requiredParams: ["reason"],
    description: "Filament native initialization failed (null pointer)."
  },
  [CameraErrorCode.E_PIPELINE_INIT_FAILED]: {
    code: 1012,
    severity: 'fatal',
    category: 'rendering',
    requiredParams: ["reason"],
    description: "Failed to create rendering pipeline (textures/render targets)."
  },
  [CameraErrorCode.E_LOW_MEMORY]: {
    code: 1013,
    severity: 'warning',
    category: 'system',
    requiredParams: ["availableMemory","requiredMemory"],
    description: "Device is running extremely low on memory, aborting intensive rendering operations."
  },
  [CameraErrorCode.E_THERMAL_THROTTLING]: {
    code: 1014,
    severity: 'warning',
    category: 'system',
    requiredParams: ["thermalStatus"],
    description: "Device temperature is too high, performance may be throttled."
  },
  [CameraErrorCode.E_ZOOM_OUT_OF_BOUNDS]: {
    code: 1015,
    severity: 'warning',
    category: 'hardware',
    requiredParams: ["requestedZoom","maxZoom"],
    description: "Requested zoom level is not supported by the camera hardware."
  },
  [CameraErrorCode.E_RESOLUTION_NOT_SUPPORTED]: {
    code: 1016,
    severity: 'warning',
    category: 'hardware',
    requiredParams: ["width","height"],
    description: "The requested camera resolution is not supported by this device."
  },
};
