/**
 * @file events.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-events.yaml
 * 
 * To add, edit, or remove camera events, modify the YAML file above and run:
 *   npm run codegen
 */

export interface OnCapabilitiesUpdateEventAvailableCamerasItem {
  id: string;
  focalLength: number;
  focalLength35mm: number;
}

export interface OnDebugUpdateEvent {
  fps: number;
  hwFps: number;
  resolution: string;
  timestamp?: number;
}

export interface OnExposureUpdateEvent {
  iso: number;
  shutterSpeed: number;
  focusDistance?: number;
  activeCameraId?: string;
  noiseReduction?: number;
}

export interface OnCapabilitiesUpdateEvent {
  supportsFocus: boolean;
  isoMin?: number;
  isoMax?: number;
  availableCameras: OnCapabilitiesUpdateEventAvailableCamerasItem[];
}

export interface OnPhotoCapturedEvent {
  uri: string;
}

export interface OnTorchStateChangedEvent {
  enabled: boolean;
}

export interface OnDeviceHealthUpdateEvent {
  thermalState: 'normal' | 'warning' | 'critical';
  isLowRam: boolean;
}

export interface GeneratedCameraViewEvents {
  onDebugUpdate?: (event: { nativeEvent: OnDebugUpdateEvent }) => void;
  onExposureUpdate?: (event: { nativeEvent: OnExposureUpdateEvent }) => void;
  onCapabilitiesUpdate?: (event: { nativeEvent: OnCapabilitiesUpdateEvent }) => void;
  onPhotoCaptured?: (event: { nativeEvent: OnPhotoCapturedEvent }) => void;
  onTorchStateChanged?: (event: { nativeEvent: OnTorchStateChangedEvent }) => void;
}
