// ⚠️ AI WARNING: Before modifying this complex/cross-platform module, query the dependency graph: node packages/shared/scripts/graphrag/query.js <query>
import { requireNativeViewManager, requireNativeModule, EventEmitter } from 'expo-modules-core';
import * as React from 'react';
import { ViewProps } from 'react-native';
import { GeneratedCameraViewEvents } from './events';

export interface NativeFilmCameraViewProps extends ViewProps, GeneratedCameraViewEvents {
  // @@GEN_PROPS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  ev?: number;
  targetFps?: number;
  cameraAspectRatio?: number;
  noiseReduction?: number;
  noiseReductionAuto?: boolean;
  isoAuto?: boolean;
  shutterSpeedAuto?: boolean;
  temperatureAuto?: boolean;
  autoFocus?: boolean;
  iso?: number;
  exposureTime?: number;
  focusDistance?: number;
  torchState?: number;
  torchStrength?: number;
  cameraId?: string | null;
  resolutionSetting?: number;
  previewQuality?: number;
  force60fpsCrop?: boolean;
  secureViewEnabled?: boolean;
  isSelfieCamera?: boolean;
  zoom?: number;
  // @@GEN_PROPS_END@@
}

const NativeFilmCameraView: React.ComponentType<NativeFilmCameraViewProps> =
  requireNativeViewManager('NativeFilmCamera');

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let NativeFilmCameraModule: any;
try {
  NativeFilmCameraModule = requireNativeModule('NativeFilmCamera');
} catch {
  NativeFilmCameraModule = {
    verifyGrovkornetAuthenticity: async () => Promise.resolve(true),
    generatePresetPreview: async () => Promise.resolve(''),
    deleteFile: async () => Promise.resolve(false),
  };
}

export async function verifyGrovkornetAuthenticity(uri: string): Promise<boolean> {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return await NativeFilmCameraModule.verifyGrovkornetAuthenticity(uri);
}

export async function generatePresetPreview(inputUri: string, payload: any): Promise<string> {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return await NativeFilmCameraModule.generatePresetPreview(inputUri, payload);
}

export async function deleteFile(uri: string): Promise<boolean> {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return await NativeFilmCameraModule.deleteFile(uri);
}

export async function pauseStream(): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return await NativeFilmCameraModule.pauseStream();
}

export async function resumeStream(): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return await NativeFilmCameraModule.resumeStream();
}

export const NativeCameraEventEmitter = new EventEmitter<any>(NativeFilmCameraModule);

export * from './errors';
export { NativeFilmCameraView };
export * from './NitroCameraConfiguration.nitro';
export * from './events';
