import {
  usePresetStore,
  Preset,
  PresetPayload,
  DEFAULT_PRESET_PAYLOAD,
  DEFAULT_FILM_PAYLOAD,
  DEFAULT_BODY_PAYLOAD,
  DEFAULT_LENS_PAYLOAD,
  PresetStore
} from '@entities/preset';
import { useFilmStore, getNitroConfig } from '@entities/film';
import { useBodyStore } from '@entities/body';
import { useLensStore } from '@entities/lens';
import i18n from 'i18next';

const AUTO_MAPPINGS: Record<string, string> = {
  temperature: 'temperatureAuto',
  tint: 'temperatureAuto',
  contrast: 'contrastAuto',
  blackLevel: 'blackLevelAuto',
  highlights: 'highlightsAuto',
  pivot: 'pivotAuto',
  noiseReductionMode: 'noiseReductionAuto',
  iso: 'isoAuto',
  shutterSpeed: 'shutterSpeedAuto',
  ev: 'evAuto',
};

const snapshotStorePayload = <T extends Record<string, any>>(
  storeState: Record<string, any>,
  defaultPayload: T
): T => {
  const payload = {} as Record<keyof T, unknown>;
  Object.keys(defaultPayload).forEach((key) => {
    const k = key as keyof T;
    const val = storeState[key];
    const hasValue = val && typeof val === 'object' && 'value' in val;
    payload[k] = hasValue ? val.value : val !== undefined ? val : defaultPayload[k];
  });
  return payload as T;
};

const normalizeStorePayload = <T extends Record<string, any>>(
  payload: T | undefined,
  defaultPayload: T
): T => {
  const result = { ...defaultPayload };
  if (payload) {
    Object.keys(payload).forEach((key) => {
      const k = key as keyof T;
      if (payload[k] !== undefined && payload[k] !== null) {
        result[k] = payload[k];
      }
    });
  }
  return result;
};

const areStorePayloadsEqual = <T extends Record<string, any>>(
  n1: T,
  n2: T,
  defaultPayload: T
): boolean => {
  const keys = Object.keys(defaultPayload) as Array<keyof T>;
  for (const key of keys) {
    const keyStr = key as string;
    const autoKey = AUTO_MAPPINGS[keyStr];
    if (autoKey && n1[autoKey] && n2[autoKey]) {
      continue;
    }

    const val1 = n1[key];
    const val2 = n2[key];
    if (typeof val1 === 'number' && typeof val2 === 'number') {
      if (Math.abs(val1 - val2) >= 0.000001) return false;
    } else if (val1 !== val2) {
      return false;
    }
  }
  return true;
};

const applyStorePayload = <T extends Record<string, any>>(
  storeState: Record<string, any>,
  defaultPayload: T,
  customPayload: T | undefined
): T => {
  const target = { ...defaultPayload, ...customPayload };
  Object.keys(target).forEach((key) => {
    const storeItem = storeState[key];
    if (storeItem && typeof storeItem === 'object' && 'value' in storeItem) {
      (storeItem as Record<string, unknown>).value = target[key];
    }
  });
  return target;
};

const syncPayloadToNitro = (payload: Record<string, any>): void => {
  const nitroConfig = getNitroConfig();
  Object.keys(payload).forEach((key) => {
    if (key in nitroConfig) {
      try {
        (nitroConfig as unknown as Record<string, unknown>)[key] = payload[key];
      } catch {
        // Ignored
      }
    }
  });
};

/**
 * Snapshots the current runtime values of all stores
 */
export const snapshotCurrentPayload = (): PresetPayload => {
  return {
    // @@GEN_SNAPSHOT_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        body: snapshotStorePayload(useBodyStore.getState(), DEFAULT_BODY_PAYLOAD),
        film: snapshotStorePayload(useFilmStore.getState(), DEFAULT_FILM_PAYLOAD),
        lens: snapshotStorePayload(useLensStore.getState(), DEFAULT_LENS_PAYLOAD),
    // @@GEN_SNAPSHOT_END@@
  };
};

const normalizePayload = (p: PresetPayload): PresetPayload => {
  return {
    // @@GEN_NORMALIZE_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        body: normalizeStorePayload(p.body, DEFAULT_BODY_PAYLOAD),
        film: normalizeStorePayload(p.film, DEFAULT_FILM_PAYLOAD),
        lens: normalizeStorePayload(p.lens, DEFAULT_LENS_PAYLOAD),
    // @@GEN_NORMALIZE_END@@
  };
};

export const arePayloadsEqual = (p1: PresetPayload, p2: PresetPayload): boolean => {
  if (!p1 || !p2) return false;

  const n1 = normalizePayload(p1);
  const n2 = normalizePayload(p2);

  // @@GEN_EQUAL_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    if (!areStorePayloadsEqual(n1.body, n2.body, DEFAULT_BODY_PAYLOAD)) return false;
    if (!areStorePayloadsEqual(n1.film, n2.film, DEFAULT_FILM_PAYLOAD)) return false;
    if (!areStorePayloadsEqual(n1.lens, n2.lens, DEFAULT_LENS_PAYLOAD)) return false;
  // @@GEN_EQUAL_END@@

  return true;
};

/**
 * Applies a preset by updating the store shared values
 */
export const applyPreset = (id: string): void => {
  const store = usePresetStore.getState();
  let payload: PresetPayload | null = null;

  if (id === 'default') {
    payload = DEFAULT_PRESET_PAYLOAD;
  } else if (id === 'customized') {
    payload = store.customizedPayload;
  } else {
    const preset = store.userPresets.find((p) => p.id === id);
    if (preset) {
      payload = preset.payload;
    }
  }

  if (!payload) return;

  store.setApplyingPreset(true);
  store.setActivePresetId(id);

  // @@GEN_APPLY_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    const targetBody = applyStorePayload(useBodyStore.getState(), DEFAULT_BODY_PAYLOAD, payload.body);
    syncPayloadToNitro(targetBody);

    const targetFilm = applyStorePayload(useFilmStore.getState(), DEFAULT_FILM_PAYLOAD, payload.film);
    syncPayloadToNitro(targetFilm);

    const targetLens = applyStorePayload(useLensStore.getState(), DEFAULT_LENS_PAYLOAD, payload.lens);
    syncPayloadToNitro(targetLens);
  // @@GEN_APPLY_END@@

  store.setApplyingPreset(false);
};

/**
 * Syncs the current JS runtime state of the stores to the native Nitro configuration.
 */
export const syncRuntimeToNative = (): void => {
  // @@GEN_SYNC_NATIVE_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    const targetBody = snapshotStorePayload(useBodyStore.getState(), DEFAULT_BODY_PAYLOAD);
    syncPayloadToNitro(targetBody);

    const targetFilm = snapshotStorePayload(useFilmStore.getState(), DEFAULT_FILM_PAYLOAD);
    syncPayloadToNitro(targetFilm);

    const targetLens = snapshotStorePayload(useLensStore.getState(), DEFAULT_LENS_PAYLOAD);
    syncPayloadToNitro(targetLens);
  // @@GEN_SYNC_NATIVE_END@@
};

/**
 * Creates and saves a new user preset
 */
export const addPreset = (name: string, thumbnailUri?: string): void => {
  const store = usePresetStore.getState();
  const payload = store.customizedPayload ?? snapshotCurrentPayload();

  const newPreset: Preset = {
    id: Date.now().toString(),
    name,
    payload,
    isFavorite: false,
    inQuickSelect: true,
    createdAt: Date.now(),
    thumbnailUri,
  };

  store.addUserPreset(newPreset);
};

/**
 * Deletes a user preset and falls back to default if the deleted preset was active
 */
export const removePreset = (id: string): void => {
  const store = usePresetStore.getState();

  if (id === 'customized') {
    store.setCustomizedPayload(null);
    store.setCustomizedThumbnailUri(null);
    applyPreset('default');
    return;
  }

  const wasActive = store.activePresetId === id;

  store.removeUserPreset(id);

  if (wasActive) {
    applyPreset('default');
  }
};

/**
 * Marks the active preset as customized when a parameter changes manually
 */
export const markAsCustomized = (): void => {
  const store = usePresetStore.getState();
  if (store.isApplyingPreset) return;

  const payload = snapshotCurrentPayload();

  // Check if it matches the default preset
  if (arePayloadsEqual(payload, DEFAULT_PRESET_PAYLOAD)) {
    store.setActivePresetId('default');
    store.setCustomizedPayload(null);
    store.setCustomizedThumbnailUri(null);
    return;
  }

  // Check if it matches any user preset
  const matchingUserPreset = store.userPresets.find((preset) =>
    arePayloadsEqual(payload, preset.payload)
  );

  if (matchingUserPreset) {
    store.setActivePresetId(matchingUserPreset.id);
    store.setCustomizedPayload(null);
    store.setCustomizedThumbnailUri(null);
    return;
  }

  store.setActivePresetId('customized');
  store.setCustomizedPayload(payload);
};

/**
 * Generates the list of quick presets dynamically based on the store's raw data
 */
export const generateQuickSelectList = (state: Pick<PresetStore, 'userPresets' | 'customizedPayload' | 'activePresetId'>) => {
  const { userPresets, customizedPayload, activePresetId } = state;
  const tDefault = i18n.t ? i18n.t('presets.default', 'Default') : 'Default';
  const list = [{ id: 'default', name: tDefault || 'Default' }];
  
  if (customizedPayload) {
    const tCustomized = i18n.t ? i18n.t('presets.customized', 'Custom') : 'Custom';
    list.push({ id: 'customized', name: tCustomized || 'Custom' });
  }

  const sortedPresets = [...userPresets].sort((a, b) => {
    // 1. Favorite preset first
    if (a.isFavorite && !b.isFavorite) return -1;
    if (!a.isFavorite && b.isFavorite) return 1;

    // 2. Quick select (pinned) next
    if (a.inQuickSelect && !b.inQuickSelect) return -1;
    if (!a.inQuickSelect && b.inQuickSelect) return 1;

    // 3. Alphabetical sorting
    return a.name.localeCompare(b.name, undefined, { sensitivity: 'base', numeric: true });
  });

  sortedPresets.forEach((p) => {
    if (p.inQuickSelect || p.id === activePresetId) {
      list.push({ id: p.id, name: p.name });
    }
  });

  return list;
};

/**
 * Navigates to the next quick preset
 */
export const nextQuickPreset = (): void => {
  const store = usePresetStore.getState();
  const list = generateQuickSelectList(store);
  if (list.length <= 1) return;
  const currentIndex = list.findIndex((p) => p.id === store.activePresetId);
  const nextIndex = (currentIndex + 1) % list.length;
  applyPreset(list[nextIndex].id);
};

/**
 * Navigates to the previous quick preset
 */
export const prevQuickPreset = (): void => {
  const store = usePresetStore.getState();
  const list = generateQuickSelectList(store);
  if (list.length <= 1) return;
  const currentIndex = list.findIndex((p) => p.id === store.activePresetId);
  const prevIndex = (currentIndex - 1 + list.length) % list.length;
  applyPreset(list[prevIndex].id);
};
