/**
 * @file CameraEvents.h
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-events.yaml
 * 
 * To add, edit, or remove camera events, modify the YAML file above and run:
 *   npm run codegen
 */

#pragma once
#include <jni.h>
#include <string>
#include <vector>
#include <optional>

namespace grovkornet {
namespace events {

enum class ThermalState {
    Normal,
    Warning,
    Critical
};

inline const char* toString(ThermalState val) {
    switch (val) {
        case ThermalState::Normal: return "normal";
        case ThermalState::Warning: return "warning";
        case ThermalState::Critical: return "critical";
    }
    return "normal";
}

struct OnCapabilitiesUpdateEventAvailableCamerasItem {
    std::string id;
    double focalLength;
    double focalLength35mm;
};

struct OnDebugUpdateEvent {
    double fps;
    double hwFps;
    std::string resolution;
    std::optional<double> timestamp;
};

struct OnExposureUpdateEvent {
    double iso;
    double shutterSpeed;
    std::optional<double> focusDistance;
    std::optional<std::string> activeCameraId;
    std::optional<double> noiseReduction;
};

struct OnCapabilitiesUpdateEvent {
    bool supportsFocus;
    std::optional<double> isoMin;
    std::optional<double> isoMax;
    std::vector<OnCapabilitiesUpdateEventAvailableCamerasItem> availableCameras;
};

struct OnPhotoCapturedEvent {
    std::string uri;
};

struct OnTorchStateChangedEvent {
    bool enabled;
};

struct OnDeviceHealthUpdateEvent {
    ThermalState thermalState;
    bool isLowRam;
};

struct OnSessionReadyEvent {
};

// JNI Helper functions for serialization to Java Map (jobject)
inline jobject createJavaHashMap(JNIEnv* env) {
    jclass hashMapClass = env->FindClass("java/util/HashMap");
    jmethodID init = env->GetMethodID(hashMapClass, "<init>", "()V");
    return env->NewObject(hashMapClass, init);
}

inline void putInJavaMap(JNIEnv* env, jobject map, const std::string& key, jobject value) {
    jclass mapClass = env->FindClass("java/util/Map");
    jmethodID put = env->GetMethodID(mapClass, "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
    jstring jkey = env->NewStringUTF(key.c_str());
    env->CallObjectMethod(map, put, jkey, value);
    env->DeleteLocalRef(jkey);
}

inline jobject toJavaDouble(JNIEnv* env, double value) {
    jclass doubleClass = env->FindClass("java/lang/Double");
    jmethodID init = env->GetMethodID(doubleClass, "<init>", "(D)V");
    return env->NewObject(doubleClass, init, value);
}

inline jobject toJavaBoolean(JNIEnv* env, bool value) {
    jclass booleanClass = env->FindClass("java/lang/Boolean");
    jmethodID init = env->GetMethodID(booleanClass, "<init>", "(Z)V");
    return env->NewObject(booleanClass, init, value);
}

inline jobject toJavaString(JNIEnv* env, const std::string& value) {
    return env->NewStringUTF(value.c_str());
}

inline jobject toJNI(JNIEnv* env, const OnCapabilitiesUpdateEventAvailableCamerasItem& item) {
    jobject map = createJavaHashMap(env);
    jobject j_id = toJavaString(env, item.id);
        putInJavaMap(env, map, "id", j_id);
        env->DeleteLocalRef(j_id);
    jobject j_focalLength = toJavaDouble(env, item.focalLength);
        putInJavaMap(env, map, "focalLength", j_focalLength);
        env->DeleteLocalRef(j_focalLength);
    jobject j_focalLength35mm = toJavaDouble(env, item.focalLength35mm);
        putInJavaMap(env, map, "focalLength35mm", j_focalLength35mm);
        env->DeleteLocalRef(j_focalLength35mm);
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnDebugUpdateEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_fps = toJavaDouble(env, event.fps);
        putInJavaMap(env, map, "fps", j_fps);
        env->DeleteLocalRef(j_fps);
    jobject j_hwFps = toJavaDouble(env, event.hwFps);
        putInJavaMap(env, map, "hwFps", j_hwFps);
        env->DeleteLocalRef(j_hwFps);
    jobject j_resolution = toJavaString(env, event.resolution);
        putInJavaMap(env, map, "resolution", j_resolution);
        env->DeleteLocalRef(j_resolution);
    if (event.timestamp.has_value()) {
            jobject j_timestamp = toJavaDouble(env, event.timestamp.value());
            putInJavaMap(env, map, "timestamp", j_timestamp);
            env->DeleteLocalRef(j_timestamp);
    }
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnExposureUpdateEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_iso = toJavaDouble(env, event.iso);
        putInJavaMap(env, map, "iso", j_iso);
        env->DeleteLocalRef(j_iso);
    jobject j_shutterSpeed = toJavaDouble(env, event.shutterSpeed);
        putInJavaMap(env, map, "shutterSpeed", j_shutterSpeed);
        env->DeleteLocalRef(j_shutterSpeed);
    if (event.focusDistance.has_value()) {
            jobject j_focusDistance = toJavaDouble(env, event.focusDistance.value());
            putInJavaMap(env, map, "focusDistance", j_focusDistance);
            env->DeleteLocalRef(j_focusDistance);
    }
    if (event.activeCameraId.has_value()) {
            jobject j_activeCameraId = toJavaString(env, event.activeCameraId.value());
            putInJavaMap(env, map, "activeCameraId", j_activeCameraId);
            env->DeleteLocalRef(j_activeCameraId);
    }
    if (event.noiseReduction.has_value()) {
            jobject j_noiseReduction = toJavaDouble(env, event.noiseReduction.value());
            putInJavaMap(env, map, "noiseReduction", j_noiseReduction);
            env->DeleteLocalRef(j_noiseReduction);
    }
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnCapabilitiesUpdateEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_supportsFocus = toJavaBoolean(env, event.supportsFocus);
        putInJavaMap(env, map, "supportsFocus", j_supportsFocus);
        env->DeleteLocalRef(j_supportsFocus);
    if (event.isoMin.has_value()) {
            jobject j_isoMin = toJavaDouble(env, event.isoMin.value());
            putInJavaMap(env, map, "isoMin", j_isoMin);
            env->DeleteLocalRef(j_isoMin);
    }
    if (event.isoMax.has_value()) {
            jobject j_isoMax = toJavaDouble(env, event.isoMax.value());
            putInJavaMap(env, map, "isoMax", j_isoMax);
            env->DeleteLocalRef(j_isoMax);
    }
    jclass arrayListClass_availableCameras = env->FindClass("java/util/ArrayList");
        jmethodID initList_availableCameras = env->GetMethodID(arrayListClass_availableCameras, "<init>", "()V");
        jobject jlist_availableCameras = env->NewObject(arrayListClass_availableCameras, initList_availableCameras);
        jmethodID addList_availableCameras = env->GetMethodID(arrayListClass_availableCameras, "add", "(Ljava/lang/Object;)Z");

        for (const auto& item : event.availableCameras) {
            jobject jitem_availableCameras = toJNI(env, item);
            env->CallBooleanMethod(jlist_availableCameras, addList_availableCameras, jitem_availableCameras);
            env->DeleteLocalRef(jitem_availableCameras);
        }
        putInJavaMap(env, map, "availableCameras", jlist_availableCameras);
        env->DeleteLocalRef(jlist_availableCameras);
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnPhotoCapturedEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_uri = toJavaString(env, event.uri);
        putInJavaMap(env, map, "uri", j_uri);
        env->DeleteLocalRef(j_uri);
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnTorchStateChangedEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_enabled = toJavaBoolean(env, event.enabled);
        putInJavaMap(env, map, "enabled", j_enabled);
        env->DeleteLocalRef(j_enabled);
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnDeviceHealthUpdateEvent& event) {
    jobject map = createJavaHashMap(env);
    jobject j_thermalState = toJavaString(env, toString(event.thermalState));
        putInJavaMap(env, map, "thermalState", j_thermalState);
        env->DeleteLocalRef(j_thermalState);
    jobject j_isLowRam = toJavaBoolean(env, event.isLowRam);
        putInJavaMap(env, map, "isLowRam", j_isLowRam);
        env->DeleteLocalRef(j_isLowRam);
    return map;
}

inline jobject toJNI(JNIEnv* env, const OnSessionReadyEvent& event) {
    jobject map = createJavaHashMap(env);
    return map;
}

#if __has_include(<jsi/jsi.h>)
// High-frequency JSI dispatch helpers to avoid JNI/GC overhead
inline void dispatchJsiEvent(facebook::jsi::Runtime& runtime, const facebook::jsi::Function& callback, const OnDebugUpdateEvent& event) {
    facebook::jsi::Object payload(runtime);
    payload.setProperty(runtime, "fps", event.fps);
    payload.setProperty(runtime, "hwFps", event.hwFps);
    payload.setProperty(runtime, "resolution", facebook::jsi::String::createFromUtf8(runtime, event.resolution));
    payload.setProperty(runtime, "timestamp", event.timestamp);
    callback.call(runtime, payload);
}

#endif
} // namespace events
} // namespace grovkornet
