/**
 * @file HardwareConfig.h
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/hardware-config.json
 * 
 * To add, edit, or remove hardware/rendering constants, modify the JSON file above and run:
 *   npm run codegen
 */

#pragma once

namespace HardwareConfig {
    static constexpr int LUT_SIZE = 33;
    static constexpr float MIN_DRS_SCALE = 0.5f;
    static constexpr float MAX_DRS_SCALE = 1.0f;
    static constexpr int FRAME_TIME_WINDOW_SIZE = 10;
    static constexpr int DRS_COOLDOWN_FRAMES = 30;
}
