#pragma once

struct RenderParams {
    // @@GEN_STRUCT_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    float saturation;
    float contrast;
    float grainIntensity;
    float grainChroma;
    float grainSize;
    float grainSpeed;
    float vignetteIntensity;
    float chromaShift;
    float whiteBalance;
    float tint;
    float bloomIntensity;
    float chromaticAberration;
    float chromaShiftDirection;
    float sharpening;
    float satRed;
    float satOrange;
    float satYellow;
    float satGreen;
    float satCyan;
    float satBlue;
    float satPurple;
    float satMagenta;
    float aberrationInvert;
    float boundMagentaRed;
    float boundRedOrange;
    float boundOrangeYellow;
    float boundYellowGreen;
    float boundGreenCyan;
    float boundCyanBlue;
    float boundBluePurple;
    float boundPurpleMagenta;
    float grainRoughness;
    float panelY;
    float grainEnabled;
    float bloomEnabled;
    float blackLevel;
    float highlights;
    float pivot;
    float contrastAuto;
    float blackLevelAuto;
    float highlightsAuto;
    float pivotAuto;
    float pixelationFactor;
    float tapeJitter;
    float scanlines;
    float chromaShiftInvert;
    float hue;
    float hueRed;
    float hueOrange;
    float hueYellow;
    float hueGreen;
    float hueCyan;
    float hueBlue;
    float huePurple;
    float hueMagenta;
    float scanlinesHorizontal;
    float scanlinesMode;
    float scanlinesDensity;
    float lensDistortion;
    // @@GEN_STRUCT_END@@
};

