import { useFilmStore } from '@entities/film';
import { ParameterType } from '@entities/system';
import {
  DEFAULT_NOISE_REDUCTION_MODE,
  DEFAULT_NOISE_REDUCTION_AUTO,
  DEFAULT_TEMPERATURE_AUTO,
  DEFAULT_TEMPERATURE,
  DEFAULT_TINT,
  DEFAULT_IS_SELFIE_CAMERA,
  DEFAULT_SATURATION,
  DEFAULT_SELECTIVE_SATURATION,
  DEFAULT_BOUND_MAGENTA_RED,
  DEFAULT_BOUND_RED_ORANGE,
  DEFAULT_BOUND_ORANGE_YELLOW,
  DEFAULT_BOUND_YELLOW_GREEN,
  DEFAULT_BOUND_GREEN_CYAN,
  DEFAULT_BOUND_CYAN_BLUE,
  DEFAULT_BOUND_BLUE_PURPLE,
  DEFAULT_BOUND_PURPLE_MAGENTA,
  DEFAULT_CONTRAST,
  DEFAULT_GRAIN_INTENSITY,
  DEFAULT_GRAIN_CHROMA,
  DEFAULT_GRAIN_SIZE,
  DEFAULT_GRAIN_SPEED,
  DEFAULT_GRAIN_ROUGHNESS,
  DEFAULT_GRAIN_ENABLED,
  DEFAULT_VIGNETTE_INTENSITY,
  DEFAULT_CHROMA_SHIFT,
  DEFAULT_CHROMA_SHIFT_DIRECTION,
  DEFAULT_CHROMA_SHIFT_INVERT,
  DEFAULT_BLOOM_INTENSITY,
  DEFAULT_BLOOM_ENABLED,
  DEFAULT_CHROMATIC_ABERRATION,
  DEFAULT_ABERRATION_INVERT,
  DEFAULT_SHARPENING,
  DEFAULT_BLACK_LEVEL,
  DEFAULT_HIGHLIGHTS,
  DEFAULT_PIVOT,
  DEFAULT_CONTRAST_AUTO,
  DEFAULT_BLACK_LEVEL_AUTO,
  DEFAULT_HIGHLIGHTS_AUTO,
  DEFAULT_PIVOT_AUTO,
  DEFAULT_PIXELATION_FACTOR,
  DEFAULT_TAPE_JITTER,
  DEFAULT_SCANLINES,
  DEFAULT_SCANLINES_HORIZONTAL,
  DEFAULT_SCANLINES_MODE,
  DEFAULT_SCANLINES_DENSITY,
  DEFAULT_HUE,
  DEFAULT_SELECTIVE_HUE,
  DEFAULT_LENS_DISTORTION,
} from '@grovkornet/shared';

export const resetFilmParameter = (param: ParameterType): boolean => {
  const store = useFilmStore.getState();
  switch (param) {
    case 'temperature':
    case 'tint':
      store.setTemperatureAuto(true);
      return true;
    case 'contrast':
      store.setContrastAuto(true);
      store.setPivotAuto(true);
      return true;
    case 'blackLevel':
      store.setBlackLevelAuto(true);
      return true;
    case 'highlights':
      store.setHighlightsAuto(true);
      return true;
    case 'pivot':
      store.setPivotAuto(true);
      return true;
    default: {
      return resetFilmEffect(param);
    }
  }
};

export const resetFilmEffect = (effect: string): boolean => {
  const store = useFilmStore.getState();
  let handled = true;
  switch (effect) {
    // @@GEN_RESET_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    case 'noise_reduction':
      store.setNoiseReductionMode(DEFAULT_NOISE_REDUCTION_MODE);
      store.setNoiseReductionAuto(DEFAULT_NOISE_REDUCTION_AUTO);
      break;
    case 'temperature':
    case 'tint':
      store.setTemperatureAuto(DEFAULT_TEMPERATURE_AUTO);
      store.setTemperature(DEFAULT_TEMPERATURE);
      store.setTint(DEFAULT_TINT);
      break;
    case 'camera_facing':
      store.setIsSelfieCamera(DEFAULT_IS_SELFIE_CAMERA);
      break;
    case 'saturation':
      store.setSaturation(DEFAULT_SATURATION);
      store.setSatRed(DEFAULT_SELECTIVE_SATURATION);
      store.setSatOrange(DEFAULT_SELECTIVE_SATURATION);
      store.setSatYellow(DEFAULT_SELECTIVE_SATURATION);
      store.setSatGreen(DEFAULT_SELECTIVE_SATURATION);
      store.setSatCyan(DEFAULT_SELECTIVE_SATURATION);
      store.setSatBlue(DEFAULT_SELECTIVE_SATURATION);
      store.setSatPurple(DEFAULT_SELECTIVE_SATURATION);
      store.setSatMagenta(DEFAULT_SELECTIVE_SATURATION);
      store.setBoundMagentaRed(DEFAULT_BOUND_MAGENTA_RED);
      store.setBoundRedOrange(DEFAULT_BOUND_RED_ORANGE);
      store.setBoundOrangeYellow(DEFAULT_BOUND_ORANGE_YELLOW);
      store.setBoundYellowGreen(DEFAULT_BOUND_YELLOW_GREEN);
      store.setBoundGreenCyan(DEFAULT_BOUND_GREEN_CYAN);
      store.setBoundCyanBlue(DEFAULT_BOUND_CYAN_BLUE);
      store.setBoundBluePurple(DEFAULT_BOUND_BLUE_PURPLE);
      store.setBoundPurpleMagenta(DEFAULT_BOUND_PURPLE_MAGENTA);
      break;
    case 'contrast':
      store.setContrast(DEFAULT_CONTRAST);
      break;
    case 'grain':
      store.setGrainIntensity(DEFAULT_GRAIN_INTENSITY);
      store.setGrainChroma(DEFAULT_GRAIN_CHROMA);
      store.setGrainSize(DEFAULT_GRAIN_SIZE);
      store.setGrainSpeed(DEFAULT_GRAIN_SPEED);
      store.setGrainRoughness(DEFAULT_GRAIN_ROUGHNESS);
      store.setGrainEnabled(DEFAULT_GRAIN_ENABLED);
      break;
    case 'vignette':
      store.setVignetteIntensity(DEFAULT_VIGNETTE_INTENSITY);
      break;
    case 'chroma_shift':
      store.setChromaShift(DEFAULT_CHROMA_SHIFT);
      store.setChromaShiftDirection(DEFAULT_CHROMA_SHIFT_DIRECTION);
      store.setChromaShiftInvert(DEFAULT_CHROMA_SHIFT_INVERT);
      break;
    case 'bloom':
      store.setBloomIntensity(DEFAULT_BLOOM_INTENSITY);
      store.setBloomEnabled(DEFAULT_BLOOM_ENABLED);
      break;
    case 'chromatic_aberration':
      store.setChromaticAberration(DEFAULT_CHROMATIC_ABERRATION);
      store.setAberrationInvert(DEFAULT_ABERRATION_INVERT);
      break;
    case 'sharpening':
      store.setSharpening(DEFAULT_SHARPENING);
      break;
    case 'tone':
      store.setBlackLevel(DEFAULT_BLACK_LEVEL);
      store.setHighlights(DEFAULT_HIGHLIGHTS);
      store.setPivot(DEFAULT_PIVOT);
      store.setContrastAuto(DEFAULT_CONTRAST_AUTO);
      store.setBlackLevelAuto(DEFAULT_BLACK_LEVEL_AUTO);
      store.setHighlightsAuto(DEFAULT_HIGHLIGHTS_AUTO);
      store.setPivotAuto(DEFAULT_PIVOT_AUTO);
      break;
    case 'pixelation':
      store.setPixelationFactor(DEFAULT_PIXELATION_FACTOR);
      break;
    case 'tape_jitter':
      store.setTapeJitter(DEFAULT_TAPE_JITTER);
      break;
    case 'scanlines':
      store.setScanlines(DEFAULT_SCANLINES);
      store.setScanlinesHorizontal(DEFAULT_SCANLINES_HORIZONTAL);
      store.setScanlinesMode(DEFAULT_SCANLINES_MODE);
      store.setScanlinesDensity(DEFAULT_SCANLINES_DENSITY);
      break;
    case 'hue':
      store.setHue(DEFAULT_HUE);
      store.setHueRed(DEFAULT_SELECTIVE_HUE);
      store.setHueOrange(DEFAULT_SELECTIVE_HUE);
      store.setHueYellow(DEFAULT_SELECTIVE_HUE);
      store.setHueGreen(DEFAULT_SELECTIVE_HUE);
      store.setHueCyan(DEFAULT_SELECTIVE_HUE);
      store.setHueBlue(DEFAULT_SELECTIVE_HUE);
      store.setHuePurple(DEFAULT_SELECTIVE_HUE);
      store.setHueMagenta(DEFAULT_SELECTIVE_HUE);
      break;
    case 'lens_distortion':
      store.setLensDistortion(DEFAULT_LENS_DISTORTION);
      break;
    // @@GEN_RESET_END@@
    default:
      handled = false;
  }
  return handled;
};
