import React from 'react';
import { StyleSheet, View } from 'react-native';
import { useShallow } from 'zustand/shallow';
import { useBodyStore, useBodyWorklets } from '@entities/body';
import { useLensStore } from '@entities/lens';
import { useFilmStore, useFilmWorklets } from '@entities/film';
import { useCameraStore } from '@entities/camera';
import { useGalleryStore } from '@entities/gallery';
import { NativeRenderer } from '@entities/lens';
import Animated, { useDerivedValue, useSharedValue, useAnimatedProps, useAnimatedReaction, runOnJS } from 'react-native-reanimated';
import { useDeviceRotation } from '@shared/lib/hooks/useDeviceRotation';
import { GestureDetector, Gesture } from 'react-native-gesture-handler';
import { useVerificationStore } from '@entities/verification';
import { FlashOverlay } from '@features/camera';
import { useInteractionContext } from '@shared/lib';
import { useCameraCapture } from '../lib/useCameraCapture';
import { useCameraEvents } from '../lib/useCameraEvents';

interface ViewfinderProps {
  cameraKey?: number;
}

export const Viewfinder = React.memo(({ cameraKey }: ViewfinderProps) => {
  // 1. Stable reference SharedValues (statically extracted to avoid React subscription)
  const {
    iso,
    shutterSpeed,
    ev,
    isoAuto,
    shutterSpeedAuto,
    torchState,
    torchStrength,
    aspectRatio,
    resolutionSetting,
    fpsSetting,
    previewQuality,
    force60fpsCrop,
    zoom,
    evAuto,
    fps,
    hwFps,
    resolution,
    stabilizationMode,
  } = useBodyStore.getState();

  const {
    focusAuto,
    focusDistance,
  } = useLensStore.getState();

  const {
    // @@GEN_SELECTOR_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    noiseReductionMode,
    noiseReductionAuto,
    temperatureAuto,
    isSelfieCamera,
    // @@GEN_SELECTOR_END@@
  } = useFilmStore.getState();

  // 2. Stable actions
  const setLatestPreviewUri = useGalleryStore.getState().setLatestPreviewUri;
  const setLatestCapturedUri = useGalleryStore.getState().setLatestCapturedUri;

  // 3. Reactive primitives (subscribed to cause re-renders only when necessary)
  const isCameraSecure = useCameraStore(state => state.isCameraSecure);
  const thermalState = useCameraStore(state => state.thermalState);
  const { isInteractable } = useInteractionContext();

  const capabilities = useBodyStore(state => state.capabilities);
  const { cameraAuto, cameraId } = useLensStore(useShallow(state => ({
    cameraAuto: state.cameraAuto,
    cameraId: state.cameraId,
  })));

  const cameraRef = useCameraCapture();
  const { exposureHandler, debugHandler, capabilitiesHandler, torchStateHandler } = useCameraEvents();

  const photoHandler = React.useCallback((event: { nativeEvent: { uri: string } }) => {
    const uri = event.nativeEvent.uri;
    // The temporary preview URI lives in the app's cache (file:///data/...)
    // The final URI (MediaStore) starts with content:// or file:///storage/
    if (uri.startsWith('file:///data/')) {
      setLatestPreviewUri(uri);
    } else {
      setLatestCapturedUri(uri);
      // Mark as verified instantly!
      useVerificationStore.getState().setVerified(uri, true);
    }
  }, [setLatestPreviewUri, setLatestCapturedUri]);

  const sessionReadyHandler = React.useCallback(() => {
    // Under Jest tests, run-time dynamic imports can bypass Jest mocks and cause native module load crashes.
    // We fall back to a synchronous require wrapped in a promise to keep tests stable without dynamic import VM flags.
    const getPresets = () => {
      if (process.env.NODE_ENV === 'test') {
        return Promise.resolve(require('@features/presets'));
      }
      return import('@features/presets');
    };

    getPresets()
      .then(({ syncRuntimeToNative }) => syncRuntimeToNative())
      .catch(err => console.warn('Failed to sync native runtime', err));
  }, []);

  const resolvedNoiseReduction = useDerivedValue(() => {
    return noiseReductionAuto.value ? -1 : noiseReductionMode.value;
  });

  const resolvedIso = useDerivedValue(() => {
    return isoAuto.value ? -1 : iso.value;
  });

  const resolvedShutterSpeed = useDerivedValue(() => {
    return shutterSpeedAuto.value ? -1 : shutterSpeed.value;
  });

  const resolvedFocusDistance = useDerivedValue(() => {
    return focusAuto.value ? -1.0 : focusDistance.value;
  });

  const resolvedTorchStrength = useDerivedValue(() => {
    return Math.max(1, Math.round(torchStrength.value * (capabilities.maxTorchStrength ?? 1)));
  }, [capabilities.maxTorchStrength]);

  const resolvedForce60fpsCrop = useDerivedValue(() => {
    return force60fpsCrop.value === 1;
  });

  const startZoom = useSharedValue(1.0);
  const hasWarnedPinchNaN = useSharedValue(false);
  const bodyWorklets = useBodyWorklets();

  const gestures = React.useMemo(() => {
    return Gesture.Pinch()
      .enabled(isInteractable)
      .onBegin(() => {
        // Force Reanimated and CameraX to bypass optimizations and re-sync HAL hardware state
        bodyWorklets.updateZoom(zoom.value + 0.000001);
      })
      .onStart(() => {
        startZoom.value = zoom.value;
      })
      .onChange((event) => {
        const scale = event.scale ?? 1;
        if (isNaN(scale) || scale === 0 || isNaN(startZoom.value)) {
          if (__DEV__ && !hasWarnedPinchNaN.value) {
            hasWarnedPinchNaN.value = true;
            console.warn(`[Gesture Warning]: scale or startZoom is NaN/0 in Viewfinder (Pinch)`);
          }
          return;
        }
        bodyWorklets.updateZoom(startZoom.value * scale);
      })
      .onFinalize(() => {
        startZoom.value = zoom.value;
      });
  }, [zoom, bodyWorklets, startZoom, isInteractable, hasWarnedPinchNaN]);

  const rotationY = useDeviceRotation();
  const filmWorklets = useFilmWorklets();

  useAnimatedReaction(
    () => rotationY.value,
    (rotation) => {
      let deviceOrientation = 0; // Portrait
      if (rotation === 90) {
        deviceOrientation = 1; // Landscape Left
      } else if (rotation === 180) {
        deviceOrientation = 2; // Portrait Upside Down
      } else if (rotation === -90 || rotation === 270) {
        deviceOrientation = 3; // Landscape Right
      }
      filmWorklets.updateDeviceOrientation(deviceOrientation);
    },
    [filmWorklets]
  );



  const effectiveFps = useDerivedValue(() => {
    let fps = fpsSetting.value;

    // If we are at high resolution (4K or 1440p) and the 60 FPS crop is disabled,
    // limit the target FPS to 30 (hardware limit) to allow the full uncropped frame.
    const isHighRes = resolutionSetting.value <= 1;
    const isCropDisabled = force60fpsCrop.value === 0;
    if (isHighRes && isCropDisabled) {
      fps = Math.min(fps, 30);
    }

    if (thermalState === 'warning') {
      fps = Math.min(fps, 30);
    } else if (thermalState === 'critical') {
      fps = Math.min(fps, 15);
    }
    return fps;
  }, [thermalState]);

  const animatedProps = useAnimatedProps(() => {
    return {
      // @@GEN_ANIMATED_PROPS_START@@
      // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
      // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
      // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
      evAuto: evAuto.value,
      ev: ev.value,
      targetFps: effectiveFps.value,
      cameraAspectRatio: aspectRatio.value,
      noiseReduction: resolvedNoiseReduction.value,
      noiseReductionAuto: noiseReductionAuto.value,
      isoAuto: isoAuto.value,
      shutterSpeedAuto: shutterSpeedAuto.value,
      temperatureAuto: temperatureAuto.value,
      autoFocus: focusAuto.value,
      iso: resolvedIso.value,
      exposureTime: resolvedShutterSpeed.value,
      focusDistance: resolvedFocusDistance.value,
      torchState: torchState.value,
      torchStrength: resolvedTorchStrength.value,
      resolutionSetting: resolutionSetting.value,
      previewQuality: previewQuality.value,
      force60fpsCrop: resolvedForce60fpsCrop.value,
      isSelfieCamera: isSelfieCamera.value,
      zoom: zoom.value,
      stabilizationMode: stabilizationMode.value,
      fps: fps.value,
      hwFps: hwFps.value,
      resolution: resolution.value,
      // @@GEN_ANIMATED_PROPS_END@@
    };
  }, [thermalState]);

  return (
    <View style={styles.container}>
      <GestureDetector gesture={gestures}>
        <Animated.View style={StyleSheet.absoluteFill}>
          <NativeRenderer
            ref={cameraRef}
            key={`camera-${cameraKey}-${isCameraSecure}`}
            style={StyleSheet.absoluteFill}
            zoom={zoom.value}
            ev={ev.value}
            iso={resolvedIso.value}
            exposureTime={resolvedShutterSpeed.value}
            focusDistance={resolvedFocusDistance.value}
            // @@GEN_PROPS_START@@
        // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
        // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
        // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        animatedProps={animatedProps}
        cameraId={cameraAuto ? null : cameraId}
        secureViewEnabled={isCameraSecure}
        // @@GEN_PROPS_END@@
            onCapabilitiesUpdate={capabilitiesHandler}
            onDebugUpdate={debugHandler}
            onExposureUpdate={exposureHandler}
            onPhotoCaptured={photoHandler}
            onTorchStateChanged={torchStateHandler}
            onSessionReady={sessionReadyHandler}
          />
        </Animated.View>
      </GestureDetector>
      <FlashOverlay />
    </View>
  );
});

Viewfinder.displayName = 'Viewfinder';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    overflow: 'hidden',
  },
});
