import { SharedValue } from 'react-native-reanimated';

export interface LensCapabilities {
  supportsFocus: boolean;
  availableCameras: Array<{
    id: string;
    focalLength: number;
    focalLength35mm: number;
  }>;
}

interface LensState {
  cameraAuto: boolean;
  chromaticAberration: SharedValue<number>;
  aberrationDirection: SharedValue<number>;
  bloomEnabled: SharedValue<boolean>;
  bloomIntensity: SharedValue<number>;
  activeCameraId: string;
  // @@GEN_STATE_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  focusAuto: SharedValue<boolean>;
  focusDistance: SharedValue<number>;
  cameraId: string;
  // @@GEN_STATE_END@@
  capabilities: LensCapabilities;
}

interface LensActions {
  setCameraAuto: (value: boolean) => void;
  // @@GEN_ACTIONS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  setFocusAuto: (value: boolean) => void;
  setFocusDistance: (value: number) => void;
  setCameraId: (value: string) => void;
  // @@GEN_ACTIONS_END@@
  setActiveCameraId: (value: string) => void;
  setCapabilities: (capabilities: LensCapabilities) => void;
}

export interface LensStore extends LensState, LensActions {}

// @@GEN_PARAMETERS_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export const LENS_PARAMETERS = [
  'focus'
] as const;
// @@GEN_PARAMETERS_END@@
