import { create } from 'zustand';
import { makeMutable } from 'react-native-reanimated';
import { logger } from '@shared/lib/logger';
import { 
  DEFAULT_FOCUS_AUTO,
  DEFAULT_FOCUS_DISTANCE,
  DEFAULT_CAMERA_ID,
} from '@grovkornet/shared';
import { LensStore } from './types';

export const useLensStore = create<LensStore>((set, get) => ({
  cameraAuto: true,
  chromaticAberration: makeMutable(0),
  aberrationDirection: makeMutable(0),
  bloomEnabled: makeMutable(false),
  bloomIntensity: makeMutable(0),
  activeCameraId: DEFAULT_CAMERA_ID,
  // @@GEN_STATE_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  focusAuto: makeMutable(DEFAULT_FOCUS_AUTO),
  focusDistance: makeMutable(DEFAULT_FOCUS_DISTANCE),
  cameraId: DEFAULT_CAMERA_ID,
  // @@GEN_STATE_END@@
  capabilities: {
    supportsFocus: true,
    availableCameras: [],
  },

  setCameraAuto: (value) => {
    set({ cameraAuto: value });
    notifyLensStoreListener();
  },
  // @@GEN_SETTERS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  setFocusAuto: (value) => {
    get().focusAuto.value = value;
    notifyLensStoreListener('focusAuto');
  },
  setFocusDistance: (value) => {
    const { focusDistance, focusAuto } = get();
    focusDistance.value = value;
    focusAuto.value = false;

    notifyLensStoreListener('focusDistance');
  },
  setCameraId: (value) => {
    set({ cameraId: value });
    notifyLensStoreListener('cameraId');
  },
  // @@GEN_SETTERS_END@@
  setActiveCameraId: (value) => {
    set({ activeCameraId: value });
  },
  setCapabilities: (caps) => {
    logger.info('LensStore', 'Hardware capabilities updated for Lens');
    set((state) => ({
      capabilities: {
        ...state.capabilities,
        ...caps,
      }
    }));
  },
}));

let changeListener: ((paramName?: string) => void) | null = null;
export const setLensStoreListener = (l: (paramName?: string) => void) => { changeListener = l; };
export const notifyLensStoreListener = (paramName?: string) => { changeListener?.(paramName); };
