/**
 * @file hardwareConfig.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/hardware-config.json
 * 
 * To add, edit, or remove hardware/rendering constants, modify the JSON file above and run:
 *   npm run codegen
 */

export const HARDWARE_CONFIG = {
  lut: {
    size: 33,
  },
  drs: {
    minScale: 0.5,
    maxScale: 1,
    frameTimeWindowSize: 10,
    cooldownFrames: 30,
  },
} as const;
