/**
 * @file index.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-parameters/ (formerly camera-parameters.yaml)
 * 
 * To add, edit, or remove default values, modify the YAML files and run:
 *   npm run codegen
 */

export const DEFAULT_GRAIN_INTENSITY = 0;
export const DEFAULT_SATURATION = 1;
export const DEFAULT_CONTRAST = 1;
export const DEFAULT_CHROMATIC_ABERRATION = 0;
export const DEFAULT_GRAIN_SPEED = 20;
export const DEFAULT_ISO = 400;
export const DEFAULT_EV = 0;
export const DEFAULT_SHUTTER_SPEED = 60;
export const DEFAULT_TEMPERATURE = 5000;
export const DEFAULT_TINT = 0;
export const DEFAULT_SELECTIVE_SATURATION = 50;
export const DEFAULT_HUE = 0;
export const DEFAULT_SELECTIVE_HUE = 0;
export const DEFAULT_BOUND_MAGENTA_RED = 350;
export const DEFAULT_BOUND_RED_ORANGE = 40;
export const DEFAULT_BOUND_ORANGE_YELLOW = 70;
export const DEFAULT_BOUND_YELLOW_GREEN = 110;
export const DEFAULT_BOUND_GREEN_CYAN = 170;
export const DEFAULT_BOUND_CYAN_BLUE = 230;
export const DEFAULT_BOUND_BLUE_PURPLE = 280;
export const DEFAULT_BOUND_PURPLE_MAGENTA = 315;
export const DEFAULT_PIXELATION_FACTOR = 1;
export const DEFAULT_GRAIN_CHROMA = 0;
export const DEFAULT_GRAIN_SIZE = 1;
export const DEFAULT_VIGNETTE_INTENSITY = 0;
export const DEFAULT_CHROMA_SHIFT = 0;
export const DEFAULT_BLOOM_INTENSITY = 0;
export const DEFAULT_CHROMA_SHIFT_DIRECTION = 0;
export const DEFAULT_SHARPENING = 0;
export const DEFAULT_ABERRATION_INVERT = false;
export const DEFAULT_GRAIN_ROUGHNESS = 0;
export const DEFAULT_GRAIN_ENABLED = false;
export const DEFAULT_BLOOM_ENABLED = false;
export const DEFAULT_BLACK_LEVEL = 0;
export const DEFAULT_HIGHLIGHTS = 1;
export const DEFAULT_PIVOT = 0.5;
export const DEFAULT_CONTRAST_AUTO = true;
export const DEFAULT_BLACK_LEVEL_AUTO = true;
export const DEFAULT_HIGHLIGHTS_AUTO = true;
export const DEFAULT_PIVOT_AUTO = true;
export const DEFAULT_TAPE_JITTER = 0;
export const DEFAULT_SCANLINES = 0;
export const DEFAULT_SCANLINES_HORIZONTAL = true;
export const DEFAULT_SCANLINES_MODE = 0;
export const DEFAULT_SCANLINES_DENSITY = 800;
export const DEFAULT_CHROMA_SHIFT_INVERT = false;
export const DEFAULT_FPS_SETTING = 60;
export const DEFAULT_ASPECT_RATIO = 1;
export const DEFAULT_NOISE_REDUCTION_MODE = 0;
export const DEFAULT_NOISE_REDUCTION_AUTO = false;
export const DEFAULT_ISO_AUTO = true;
export const DEFAULT_SHUTTER_SPEED_AUTO = true;
export const DEFAULT_TEMPERATURE_AUTO = true;
export const DEFAULT_FOCUS_AUTO = true;
export const DEFAULT_FOCUS_DISTANCE = 0;
export const DEFAULT_TORCH_STATE = 0;
export const DEFAULT_TORCH_STRENGTH = 1;
export const DEFAULT_CAMERA_ID = "";
export const DEFAULT_RESOLUTION_SETTING = 2;
export const DEFAULT_PREVIEW_QUALITY = 1;
export const DEFAULT_FORCE_60FPS_CROP = 1;
export const DEFAULT_IS_SELFIE_CAMERA = false;
export const DEFAULT_ZOOM = 1;
export const DEFAULT_LENS_DISTORTION = 0;
export const DEFAULT_HALATION_INTENSITY = 0;
export const DEFAULT_HALATION_ENABLED = false;
export const DEFAULT_HALATION_THRESHOLD = 0.5;
export const DEFAULT_BLOOM_THRESHOLD = 0.5;
export const DEFAULT_CHROMA_BLEED = 0;

export * from './hardwareConfig';
