package com.grovkornet.nativefilmcamera.jni

import android.util.Log

object CameraStateJNI {
    @JvmField var isJniLoaded = false
    private val fallbackStore = HashMap<String, Any?>()

    init {
        try {
            System.loadLibrary("grovkornet_engine")
            isJniLoaded = true
        } catch (e: Throwable) {
            System.err.println("CameraStateJNI: Native library not loaded, using JVM fallback store: " + e.message)
        }
    }

    @JvmStatic
    fun fallbackGet(key: String, statePtr: Long, defaultVal: Any?): Any? {
        val compositeKey = "${statePtr}_${key}"
        return fallbackStore[compositeKey] ?: defaultVal
    }

    @JvmStatic
    fun fallbackSet(key: String, statePtr: Long, value: Any?) {
        val compositeKey = "${statePtr}_${key}"
        fallbackStore[compositeKey] = value
    }

    @JvmStatic
    fun fallbackClear() {
        fallbackStore.clear()
    }

    @JvmStatic external fun nativeCreateState(): Long
    @JvmStatic external fun nativeCopyActiveState(): Long
    @JvmStatic external fun nativeFreeState(statePtr: Long)

    // @@GEN_JNI_METHODS_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        @JvmStatic external fun getEv(statePtr: Long): Float
        @JvmStatic external fun setEv(statePtr: Long, value: Float)
        @JvmStatic external fun getTargetFps(statePtr: Long): Int
        @JvmStatic external fun setTargetFps(statePtr: Long, value: Int)
        @JvmStatic external fun getAspectRatio(statePtr: Long): Int
        @JvmStatic external fun setAspectRatio(statePtr: Long, value: Int)
        @JvmStatic external fun getNoiseReduction(statePtr: Long): Int
        @JvmStatic external fun setNoiseReduction(statePtr: Long, value: Int)
        @JvmStatic external fun getNoiseReductionAuto(statePtr: Long): Boolean
        @JvmStatic external fun setNoiseReductionAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getIsoAuto(statePtr: Long): Boolean
        @JvmStatic external fun setIsoAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getShutterSpeedAuto(statePtr: Long): Boolean
        @JvmStatic external fun setShutterSpeedAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getTemperatureAuto(statePtr: Long): Boolean
        @JvmStatic external fun setTemperatureAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getAutoFocus(statePtr: Long): Boolean
        @JvmStatic external fun setAutoFocus(statePtr: Long, value: Boolean)
        @JvmStatic external fun getIso(statePtr: Long): Int
        @JvmStatic external fun setIso(statePtr: Long, value: Int)
        @JvmStatic external fun getExposureTime(statePtr: Long): Long
        @JvmStatic external fun setExposureTime(statePtr: Long, value: Long)
        @JvmStatic external fun getFocusDistance(statePtr: Long): Float
        @JvmStatic external fun setFocusDistance(statePtr: Long, value: Float)
        @JvmStatic external fun getTorchEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setTorchEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getTorchStrength(statePtr: Long): Int
        @JvmStatic external fun setTorchStrength(statePtr: Long, value: Int)
        @JvmStatic external fun getCameraId(statePtr: Long): String?
        @JvmStatic external fun setCameraId(statePtr: Long, value: String?)
        @JvmStatic external fun getResolutionSetting(statePtr: Long): Int
        @JvmStatic external fun setResolutionSetting(statePtr: Long, value: Int)
        @JvmStatic external fun getPreviewQuality(statePtr: Long): Int
        @JvmStatic external fun setPreviewQuality(statePtr: Long, value: Int)
        @JvmStatic external fun getForce60fpsCrop(statePtr: Long): Boolean
        @JvmStatic external fun setForce60fpsCrop(statePtr: Long, value: Boolean)
        @JvmStatic external fun getSecureViewEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setSecureViewEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getIsSelfieCamera(statePtr: Long): Boolean
        @JvmStatic external fun setIsSelfieCamera(statePtr: Long, value: Boolean)
        @JvmStatic external fun getZoom(statePtr: Long): Float
        @JvmStatic external fun setZoom(statePtr: Long, value: Float)
        @JvmStatic external fun getViewportWidth(statePtr: Long): Float
        @JvmStatic external fun setViewportWidth(statePtr: Long, value: Float)
        @JvmStatic external fun getViewportHeight(statePtr: Long): Float
        @JvmStatic external fun setViewportHeight(statePtr: Long, value: Float)
    // @@GEN_JNI_METHODS_END@@
}
