package com.grovkornet.nativefilmcamera.jni

import android.util.Log

object CameraStateJNI {
    @JvmField var isJniLoaded = false
    private val fallbackStore = HashMap<String, Any?>()

    init {
        try {
            System.loadLibrary("grovkornet_engine")
            isJniLoaded = true
        } catch (e: Throwable) {
            System.err.println("CameraStateJNI: Native library not loaded, using JVM fallback store: " + e.message)
        }
    }

    @JvmStatic
    fun fallbackGet(key: String, statePtr: Long, defaultVal: Any?): Any? {
        val compositeKey = "${statePtr}_${key}"
        return fallbackStore[compositeKey] ?: defaultVal
    }

    @JvmStatic
    fun fallbackSet(key: String, statePtr: Long, value: Any?) {
        val compositeKey = "${statePtr}_${key}"
        fallbackStore[compositeKey] = value
    }

    @JvmStatic
    fun fallbackClear() {
        fallbackStore.clear()
    }

    @JvmStatic external fun nativeCreateState(): Long
    @JvmStatic external fun nativeFreeState(statePtr: Long)

    // @@GEN_JNI_METHODS_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
        @JvmStatic external fun getSaturation(statePtr: Long): Float
        @JvmStatic external fun setSaturation(statePtr: Long, value: Float)
        @JvmStatic external fun getContrast(statePtr: Long): Float
        @JvmStatic external fun setContrast(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainIntensity(statePtr: Long): Float
        @JvmStatic external fun setGrainIntensity(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainChroma(statePtr: Long): Float
        @JvmStatic external fun setGrainChroma(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainSize(statePtr: Long): Float
        @JvmStatic external fun setGrainSize(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainSpeed(statePtr: Long): Float
        @JvmStatic external fun setGrainSpeed(statePtr: Long, value: Float)
        @JvmStatic external fun getVignetteIntensity(statePtr: Long): Float
        @JvmStatic external fun setVignetteIntensity(statePtr: Long, value: Float)
        @JvmStatic external fun getChromaShift(statePtr: Long): Float
        @JvmStatic external fun setChromaShift(statePtr: Long, value: Float)
        @JvmStatic external fun getWhiteBalance(statePtr: Long): Float
        @JvmStatic external fun setWhiteBalance(statePtr: Long, value: Float)
        @JvmStatic external fun getTint(statePtr: Long): Float
        @JvmStatic external fun setTint(statePtr: Long, value: Float)
        @JvmStatic external fun getBloomIntensity(statePtr: Long): Float
        @JvmStatic external fun setBloomIntensity(statePtr: Long, value: Float)
        @JvmStatic external fun getAberration(statePtr: Long): Float
        @JvmStatic external fun setAberration(statePtr: Long, value: Float)
        @JvmStatic external fun getChromaShiftDirection(statePtr: Long): Int
        @JvmStatic external fun setChromaShiftDirection(statePtr: Long, value: Int)
        @JvmStatic external fun getSharpening(statePtr: Long): Float
        @JvmStatic external fun setSharpening(statePtr: Long, value: Float)
        @JvmStatic external fun getSatRed(statePtr: Long): Float
        @JvmStatic external fun setSatRed(statePtr: Long, value: Float)
        @JvmStatic external fun getSatOrange(statePtr: Long): Float
        @JvmStatic external fun setSatOrange(statePtr: Long, value: Float)
        @JvmStatic external fun getSatYellow(statePtr: Long): Float
        @JvmStatic external fun setSatYellow(statePtr: Long, value: Float)
        @JvmStatic external fun getSatGreen(statePtr: Long): Float
        @JvmStatic external fun setSatGreen(statePtr: Long, value: Float)
        @JvmStatic external fun getSatCyan(statePtr: Long): Float
        @JvmStatic external fun setSatCyan(statePtr: Long, value: Float)
        @JvmStatic external fun getSatBlue(statePtr: Long): Float
        @JvmStatic external fun setSatBlue(statePtr: Long, value: Float)
        @JvmStatic external fun getSatPurple(statePtr: Long): Float
        @JvmStatic external fun setSatPurple(statePtr: Long, value: Float)
        @JvmStatic external fun getSatMagenta(statePtr: Long): Float
        @JvmStatic external fun setSatMagenta(statePtr: Long, value: Float)
        @JvmStatic external fun getAberrationInvert(statePtr: Long): Boolean
        @JvmStatic external fun setAberrationInvert(statePtr: Long, value: Boolean)
        @JvmStatic external fun getBoundMagentaRed(statePtr: Long): Float
        @JvmStatic external fun setBoundMagentaRed(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundRedOrange(statePtr: Long): Float
        @JvmStatic external fun setBoundRedOrange(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundOrangeYellow(statePtr: Long): Float
        @JvmStatic external fun setBoundOrangeYellow(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundYellowGreen(statePtr: Long): Float
        @JvmStatic external fun setBoundYellowGreen(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundGreenCyan(statePtr: Long): Float
        @JvmStatic external fun setBoundGreenCyan(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundCyanBlue(statePtr: Long): Float
        @JvmStatic external fun setBoundCyanBlue(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundBluePurple(statePtr: Long): Float
        @JvmStatic external fun setBoundBluePurple(statePtr: Long, value: Float)
        @JvmStatic external fun getBoundPurpleMagenta(statePtr: Long): Float
        @JvmStatic external fun setBoundPurpleMagenta(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainRoughness(statePtr: Long): Float
        @JvmStatic external fun setGrainRoughness(statePtr: Long, value: Float)
        @JvmStatic external fun getPanelY(statePtr: Long): Float
        @JvmStatic external fun setPanelY(statePtr: Long, value: Float)
        @JvmStatic external fun getGrainEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setGrainEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getBloomEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setBloomEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getBlackLevel(statePtr: Long): Float
        @JvmStatic external fun setBlackLevel(statePtr: Long, value: Float)
        @JvmStatic external fun getHighlights(statePtr: Long): Float
        @JvmStatic external fun setHighlights(statePtr: Long, value: Float)
        @JvmStatic external fun getPivot(statePtr: Long): Float
        @JvmStatic external fun setPivot(statePtr: Long, value: Float)
        @JvmStatic external fun getContrastAuto(statePtr: Long): Boolean
        @JvmStatic external fun setContrastAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getBlackLevelAuto(statePtr: Long): Boolean
        @JvmStatic external fun setBlackLevelAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getHighlightsAuto(statePtr: Long): Boolean
        @JvmStatic external fun setHighlightsAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getPivotAuto(statePtr: Long): Boolean
        @JvmStatic external fun setPivotAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getPixelationFactor(statePtr: Long): Float
        @JvmStatic external fun setPixelationFactor(statePtr: Long, value: Float)
        @JvmStatic external fun getTapeJitter(statePtr: Long): Float
        @JvmStatic external fun setTapeJitter(statePtr: Long, value: Float)
        @JvmStatic external fun getScanlines(statePtr: Long): Float
        @JvmStatic external fun setScanlines(statePtr: Long, value: Float)
        @JvmStatic external fun getChromaShiftInvert(statePtr: Long): Boolean
        @JvmStatic external fun setChromaShiftInvert(statePtr: Long, value: Boolean)
        @JvmStatic external fun getHue(statePtr: Long): Float
        @JvmStatic external fun setHue(statePtr: Long, value: Float)
        @JvmStatic external fun getHueRed(statePtr: Long): Float
        @JvmStatic external fun setHueRed(statePtr: Long, value: Float)
        @JvmStatic external fun getHueOrange(statePtr: Long): Float
        @JvmStatic external fun setHueOrange(statePtr: Long, value: Float)
        @JvmStatic external fun getHueYellow(statePtr: Long): Float
        @JvmStatic external fun setHueYellow(statePtr: Long, value: Float)
        @JvmStatic external fun getHueGreen(statePtr: Long): Float
        @JvmStatic external fun setHueGreen(statePtr: Long, value: Float)
        @JvmStatic external fun getHueCyan(statePtr: Long): Float
        @JvmStatic external fun setHueCyan(statePtr: Long, value: Float)
        @JvmStatic external fun getHueBlue(statePtr: Long): Float
        @JvmStatic external fun setHueBlue(statePtr: Long, value: Float)
        @JvmStatic external fun getHuePurple(statePtr: Long): Float
        @JvmStatic external fun setHuePurple(statePtr: Long, value: Float)
        @JvmStatic external fun getHueMagenta(statePtr: Long): Float
        @JvmStatic external fun setHueMagenta(statePtr: Long, value: Float)
        @JvmStatic external fun getScanlinesHorizontal(statePtr: Long): Boolean
        @JvmStatic external fun setScanlinesHorizontal(statePtr: Long, value: Boolean)
        @JvmStatic external fun getScanlinesMode(statePtr: Long): Int
        @JvmStatic external fun setScanlinesMode(statePtr: Long, value: Int)
        @JvmStatic external fun getScanlinesDensity(statePtr: Long): Float
        @JvmStatic external fun setScanlinesDensity(statePtr: Long, value: Float)
        @JvmStatic external fun getLensDistortion(statePtr: Long): Float
        @JvmStatic external fun setLensDistortion(statePtr: Long, value: Float)
        @JvmStatic external fun getEv(statePtr: Long): Float
        @JvmStatic external fun setEv(statePtr: Long, value: Float)
        @JvmStatic external fun getTargetFps(statePtr: Long): Int
        @JvmStatic external fun setTargetFps(statePtr: Long, value: Int)
        @JvmStatic external fun getAspectRatio(statePtr: Long): Int
        @JvmStatic external fun setAspectRatio(statePtr: Long, value: Int)
        @JvmStatic external fun getNoiseReduction(statePtr: Long): Int
        @JvmStatic external fun setNoiseReduction(statePtr: Long, value: Int)
        @JvmStatic external fun getIsoAuto(statePtr: Long): Boolean
        @JvmStatic external fun setIsoAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getShutterSpeedAuto(statePtr: Long): Boolean
        @JvmStatic external fun setShutterSpeedAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getWhiteBalanceAuto(statePtr: Long): Boolean
        @JvmStatic external fun setWhiteBalanceAuto(statePtr: Long, value: Boolean)
        @JvmStatic external fun getAutoFocus(statePtr: Long): Boolean
        @JvmStatic external fun setAutoFocus(statePtr: Long, value: Boolean)
        @JvmStatic external fun getIso(statePtr: Long): Int
        @JvmStatic external fun setIso(statePtr: Long, value: Int)
        @JvmStatic external fun getExposureTime(statePtr: Long): Long
        @JvmStatic external fun setExposureTime(statePtr: Long, value: Long)
        @JvmStatic external fun getFocusDistance(statePtr: Long): Float
        @JvmStatic external fun setFocusDistance(statePtr: Long, value: Float)
        @JvmStatic external fun getTorchEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setTorchEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getTorchStrength(statePtr: Long): Int
        @JvmStatic external fun setTorchStrength(statePtr: Long, value: Int)
        @JvmStatic external fun getCameraId(statePtr: Long): String?
        @JvmStatic external fun setCameraId(statePtr: Long, value: String?)
        @JvmStatic external fun getResolutionSetting(statePtr: Long): Int
        @JvmStatic external fun setResolutionSetting(statePtr: Long, value: Int)
        @JvmStatic external fun getPreviewQuality(statePtr: Long): Int
        @JvmStatic external fun setPreviewQuality(statePtr: Long, value: Int)
        @JvmStatic external fun getForce60fpsCrop(statePtr: Long): Boolean
        @JvmStatic external fun setForce60fpsCrop(statePtr: Long, value: Boolean)
        @JvmStatic external fun getSecureViewEnabled(statePtr: Long): Boolean
        @JvmStatic external fun setSecureViewEnabled(statePtr: Long, value: Boolean)
        @JvmStatic external fun getIsSelfieCamera(statePtr: Long): Boolean
        @JvmStatic external fun setIsSelfieCamera(statePtr: Long, value: Boolean)
        @JvmStatic external fun getZoom(statePtr: Long): Float
        @JvmStatic external fun setZoom(statePtr: Long, value: Float)
        @JvmStatic external fun getViewportWidth(statePtr: Long): Float
        @JvmStatic external fun setViewportWidth(statePtr: Long, value: Float)
        @JvmStatic external fun getViewportHeight(statePtr: Long): Float
        @JvmStatic external fun setViewportHeight(statePtr: Long, value: Float)
    // @@GEN_JNI_METHODS_END@@
}
