package com.margelo.nitro.com.grovkornet.nativefilmcamera

import com.grovkornet.nativefilmcamera.ui.NativeFilmCameraView

class HybridNitroCameraConfiguration : HybridNitroCameraConfigurationSpec() {
    // @@GEN_OVERRIDES_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    override var saturation: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.saturation?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                saturation = value.toFloat()
            }
        }

    override var contrast: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.contrast?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                contrast = value.toFloat()
            }
        }

    override var grainIntensity: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainIntensity?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainIntensity = value.toFloat()
            }
        }

    override var grainChroma: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainChroma?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainChroma = value.toFloat()
            }
        }

    override var grainSize: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainSize?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainSize = value.toFloat()
            }
        }

    override var grainSpeed: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainSpeed?.toDouble() ?: 20.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainSpeed = value.toFloat()
            }
        }

    override var vignetteIntensity: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.vignetteIntensity?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                vignetteIntensity = value.toFloat()
            }
        }

    override var chromaShift: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.chromaShift?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                chromaShift = value.toFloat()
            }
        }

    override var whiteBalance: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.whiteBalance?.toDouble() ?: 5000.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                whiteBalance = value.toFloat()
            }
        }

    override var tint: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.tint?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                tint = value.toFloat()
            }
        }

    override var bloomIntensity: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.bloomIntensity?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                bloomIntensity = value.toFloat()
            }
        }

    override var chromaticAberration: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.aberration?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                aberration = value.toFloat()
            }
        }

    override var chromaShiftDirection: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.chromaShiftDirection?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                chromaShiftDirection = value.toInt()
            }
        }

    override var sharpening: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.sharpening?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                sharpening = value.toFloat()
            }
        }

    override var satRed: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satRed?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satRed = value.toFloat()
            }
        }

    override var satOrange: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satOrange?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satOrange = value.toFloat()
            }
        }

    override var satYellow: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satYellow?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satYellow = value.toFloat()
            }
        }

    override var satGreen: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satGreen?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satGreen = value.toFloat()
            }
        }

    override var satCyan: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satCyan?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satCyan = value.toFloat()
            }
        }

    override var satBlue: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satBlue?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satBlue = value.toFloat()
            }
        }

    override var satPurple: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satPurple?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satPurple = value.toFloat()
            }
        }

    override var satMagenta: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.satMagenta?.toDouble() ?: 50.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                satMagenta = value.toFloat()
            }
        }

    override var aberrationInvert: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.aberrationInvert ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                aberrationInvert = value
            }
        }

    override var boundMagentaRed: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundMagentaRed?.toDouble() ?: 350.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundMagentaRed = value.toFloat()
            }
        }

    override var boundRedOrange: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundRedOrange?.toDouble() ?: 40.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundRedOrange = value.toFloat()
            }
        }

    override var boundOrangeYellow: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundOrangeYellow?.toDouble() ?: 70.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundOrangeYellow = value.toFloat()
            }
        }

    override var boundYellowGreen: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundYellowGreen?.toDouble() ?: 110.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundYellowGreen = value.toFloat()
            }
        }

    override var boundGreenCyan: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundGreenCyan?.toDouble() ?: 170.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundGreenCyan = value.toFloat()
            }
        }

    override var boundCyanBlue: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundCyanBlue?.toDouble() ?: 230.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundCyanBlue = value.toFloat()
            }
        }

    override var boundBluePurple: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundBluePurple?.toDouble() ?: 280.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundBluePurple = value.toFloat()
            }
        }

    override var boundPurpleMagenta: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.boundPurpleMagenta?.toDouble() ?: 315.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                boundPurpleMagenta = value.toFloat()
            }
        }

    override var grainRoughness: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainRoughness?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainRoughness = value.toFloat()
            }
        }

    override var panelY: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.panelY?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                panelY = value.toFloat()
            }
        }

    override var grainEnabled: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.grainEnabled ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                grainEnabled = value
            }
        }

    override var bloomEnabled: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.bloomEnabled ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                bloomEnabled = value
            }
        }

    override var blackLevel: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.blackLevel?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                blackLevel = value.toFloat()
            }
        }

    override var highlights: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.highlights?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                highlights = value.toFloat()
            }
        }

    override var pivot: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.pivot?.toDouble() ?: 0.5
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                pivot = value.toFloat()
            }
        }

    override var contrastAuto: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.contrastAuto ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                contrastAuto = value
            }
        }

    override var blackLevelAuto: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.blackLevelAuto ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                blackLevelAuto = value
            }
        }

    override var highlightsAuto: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.highlightsAuto ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                highlightsAuto = value
            }
        }

    override var pivotAuto: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.pivotAuto ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                pivotAuto = value
            }
        }

    override var pixelationFactor: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.pixelationFactor?.toDouble() ?: 1.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                pixelationFactor = value.toFloat()
            }
        }

    override var tapeJitter: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.tapeJitter?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                tapeJitter = value.toFloat()
            }
        }

    override var scanlines: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.scanlines?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                scanlines = value.toFloat()
            }
        }

    override var chromaShiftInvert: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.chromaShiftInvert ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                chromaShiftInvert = value
            }
        }

    override var hue: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hue?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hue = value.toFloat()
            }
        }

    override var hueRed: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueRed?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueRed = value.toFloat()
            }
        }

    override var hueOrange: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueOrange?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueOrange = value.toFloat()
            }
        }

    override var hueYellow: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueYellow?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueYellow = value.toFloat()
            }
        }

    override var hueGreen: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueGreen?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueGreen = value.toFloat()
            }
        }

    override var hueCyan: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueCyan?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueCyan = value.toFloat()
            }
        }

    override var hueBlue: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueBlue?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueBlue = value.toFloat()
            }
        }

    override var huePurple: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.huePurple?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                huePurple = value.toFloat()
            }
        }

    override var hueMagenta: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.hueMagenta?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                hueMagenta = value.toFloat()
            }
        }

    override var scanlinesHorizontal: Boolean
        get() = NativeFilmCameraView.getFirstValidConfig()?.scanlinesHorizontal ?: false
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                scanlinesHorizontal = value
            }
        }

    override var scanlinesMode: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.scanlinesMode?.toDouble() ?: 0.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                scanlinesMode = value.toInt()
            }
        }

    override var scanlinesDensity: Double
        get() = NativeFilmCameraView.getFirstValidConfig()?.scanlinesDensity?.toDouble() ?: 800.0
        set(value) {
            NativeFilmCameraView.dispatchUpdate {
                scanlinesDensity = value.toFloat()
            }
        }
    // @@GEN_OVERRIDES_END@@
}
