package com.margelo.nitro.com.grovkornet.nativefilmcamera

import com.grovkornet.nativefilmcamera.ui.NativeFilmCameraView
import com.grovkornet.nativefilmcamera.jni.CameraStateJNI
import android.util.Log

class HybridNitroCameraConfiguration : HybridNitroCameraConfigurationSpec() {
    // @@GEN_OVERRIDES_START@@
    // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
    // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
    // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
    override var saturation: Double
        get() = try { CameraStateJNI.getSaturation(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setSaturation(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set saturation", e)
            }
        }

    override var contrast: Double
        get() = try { CameraStateJNI.getContrast(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setContrast(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set contrast", e)
            }
        }

    override var grainIntensity: Double
        get() = try { CameraStateJNI.getGrainIntensity(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setGrainIntensity(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainIntensity", e)
            }
        }

    override var grainChroma: Double
        get() = try { CameraStateJNI.getGrainChroma(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setGrainChroma(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainChroma", e)
            }
        }

    override var grainSize: Double
        get() = try { CameraStateJNI.getGrainSize(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setGrainSize(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainSize", e)
            }
        }

    override var grainSpeed: Double
        get() = try { CameraStateJNI.getGrainSpeed(0L).toDouble() } catch (e: Throwable) { 20.0 }
        set(value) {
            try {
                CameraStateJNI.setGrainSpeed(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainSpeed", e)
            }
        }

    override var vignetteIntensity: Double
        get() = try { CameraStateJNI.getVignetteIntensity(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setVignetteIntensity(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set vignetteIntensity", e)
            }
        }

    override var chromaShift: Double
        get() = try { CameraStateJNI.getChromaShift(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setChromaShift(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set chromaShift", e)
            }
        }

    override var temperature: Double
        get() = try { CameraStateJNI.getTemperature(0L).toDouble() } catch (e: Throwable) { 5000.0 }
        set(value) {
            try {
                CameraStateJNI.setTemperature(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set temperature", e)
            }
        }

    override var tint: Double
        get() = try { CameraStateJNI.getTint(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setTint(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set tint", e)
            }
        }

    override var bloomIntensity: Double
        get() = try { CameraStateJNI.getBloomIntensity(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setBloomIntensity(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set bloomIntensity", e)
            }
        }

    override var chromaticAberration: Double
        get() = try { CameraStateJNI.getAberration(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setAberration(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set chromaticAberration", e)
            }
        }

    override var chromaShiftDirection: Double
        get() = try { CameraStateJNI.getChromaShiftDirection(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setChromaShiftDirection(0L, value.toInt())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set chromaShiftDirection", e)
            }
        }

    override var sharpening: Double
        get() = try { CameraStateJNI.getSharpening(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setSharpening(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set sharpening", e)
            }
        }

    override var satRed: Double
        get() = try { CameraStateJNI.getSatRed(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatRed(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satRed", e)
            }
        }

    override var satOrange: Double
        get() = try { CameraStateJNI.getSatOrange(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatOrange(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satOrange", e)
            }
        }

    override var satYellow: Double
        get() = try { CameraStateJNI.getSatYellow(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatYellow(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satYellow", e)
            }
        }

    override var satGreen: Double
        get() = try { CameraStateJNI.getSatGreen(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatGreen(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satGreen", e)
            }
        }

    override var satCyan: Double
        get() = try { CameraStateJNI.getSatCyan(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatCyan(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satCyan", e)
            }
        }

    override var satBlue: Double
        get() = try { CameraStateJNI.getSatBlue(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatBlue(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satBlue", e)
            }
        }

    override var satPurple: Double
        get() = try { CameraStateJNI.getSatPurple(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatPurple(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satPurple", e)
            }
        }

    override var satMagenta: Double
        get() = try { CameraStateJNI.getSatMagenta(0L).toDouble() } catch (e: Throwable) { 50.0 }
        set(value) {
            try {
                CameraStateJNI.setSatMagenta(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set satMagenta", e)
            }
        }

    override var aberrationInvert: Boolean
        get() = try { CameraStateJNI.getAberrationInvert(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setAberrationInvert(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set aberrationInvert", e)
            }
        }

    override var boundMagentaRed: Double
        get() = try { CameraStateJNI.getBoundMagentaRed(0L).toDouble() } catch (e: Throwable) { 350.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundMagentaRed(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundMagentaRed", e)
            }
        }

    override var boundRedOrange: Double
        get() = try { CameraStateJNI.getBoundRedOrange(0L).toDouble() } catch (e: Throwable) { 40.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundRedOrange(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundRedOrange", e)
            }
        }

    override var boundOrangeYellow: Double
        get() = try { CameraStateJNI.getBoundOrangeYellow(0L).toDouble() } catch (e: Throwable) { 70.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundOrangeYellow(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundOrangeYellow", e)
            }
        }

    override var boundYellowGreen: Double
        get() = try { CameraStateJNI.getBoundYellowGreen(0L).toDouble() } catch (e: Throwable) { 110.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundYellowGreen(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundYellowGreen", e)
            }
        }

    override var boundGreenCyan: Double
        get() = try { CameraStateJNI.getBoundGreenCyan(0L).toDouble() } catch (e: Throwable) { 170.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundGreenCyan(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundGreenCyan", e)
            }
        }

    override var boundCyanBlue: Double
        get() = try { CameraStateJNI.getBoundCyanBlue(0L).toDouble() } catch (e: Throwable) { 230.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundCyanBlue(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundCyanBlue", e)
            }
        }

    override var boundBluePurple: Double
        get() = try { CameraStateJNI.getBoundBluePurple(0L).toDouble() } catch (e: Throwable) { 280.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundBluePurple(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundBluePurple", e)
            }
        }

    override var boundPurpleMagenta: Double
        get() = try { CameraStateJNI.getBoundPurpleMagenta(0L).toDouble() } catch (e: Throwable) { 315.0 }
        set(value) {
            try {
                CameraStateJNI.setBoundPurpleMagenta(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set boundPurpleMagenta", e)
            }
        }

    override var grainRoughness: Double
        get() = try { CameraStateJNI.getGrainRoughness(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setGrainRoughness(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainRoughness", e)
            }
        }

    override var panelY: Double
        get() = try { CameraStateJNI.getPanelY(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setPanelY(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set panelY", e)
            }
        }

    override var grainEnabled: Boolean
        get() = try { CameraStateJNI.getGrainEnabled(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setGrainEnabled(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set grainEnabled", e)
            }
        }

    override var bloomEnabled: Boolean
        get() = try { CameraStateJNI.getBloomEnabled(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setBloomEnabled(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set bloomEnabled", e)
            }
        }

    override var blackLevel: Double
        get() = try { CameraStateJNI.getBlackLevel(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setBlackLevel(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set blackLevel", e)
            }
        }

    override var highlights: Double
        get() = try { CameraStateJNI.getHighlights(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setHighlights(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set highlights", e)
            }
        }

    override var pivot: Double
        get() = try { CameraStateJNI.getPivot(0L).toDouble() } catch (e: Throwable) { 0.5 }
        set(value) {
            try {
                CameraStateJNI.setPivot(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set pivot", e)
            }
        }

    override var contrastAuto: Boolean
        get() = try { CameraStateJNI.getContrastAuto(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setContrastAuto(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set contrastAuto", e)
            }
        }

    override var blackLevelAuto: Boolean
        get() = try { CameraStateJNI.getBlackLevelAuto(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setBlackLevelAuto(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set blackLevelAuto", e)
            }
        }

    override var highlightsAuto: Boolean
        get() = try { CameraStateJNI.getHighlightsAuto(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setHighlightsAuto(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set highlightsAuto", e)
            }
        }

    override var pivotAuto: Boolean
        get() = try { CameraStateJNI.getPivotAuto(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setPivotAuto(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set pivotAuto", e)
            }
        }

    override var pixelationFactor: Double
        get() = try { CameraStateJNI.getPixelationFactor(0L).toDouble() } catch (e: Throwable) { 1.0 }
        set(value) {
            try {
                CameraStateJNI.setPixelationFactor(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set pixelationFactor", e)
            }
        }

    override var tapeJitter: Double
        get() = try { CameraStateJNI.getTapeJitter(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setTapeJitter(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set tapeJitter", e)
            }
        }

    override var scanlines: Double
        get() = try { CameraStateJNI.getScanlines(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setScanlines(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set scanlines", e)
            }
        }

    override var chromaShiftInvert: Boolean
        get() = try { CameraStateJNI.getChromaShiftInvert(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setChromaShiftInvert(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set chromaShiftInvert", e)
            }
        }

    override var hue: Double
        get() = try { CameraStateJNI.getHue(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHue(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hue", e)
            }
        }

    override var hueRed: Double
        get() = try { CameraStateJNI.getHueRed(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueRed(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueRed", e)
            }
        }

    override var hueOrange: Double
        get() = try { CameraStateJNI.getHueOrange(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueOrange(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueOrange", e)
            }
        }

    override var hueYellow: Double
        get() = try { CameraStateJNI.getHueYellow(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueYellow(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueYellow", e)
            }
        }

    override var hueGreen: Double
        get() = try { CameraStateJNI.getHueGreen(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueGreen(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueGreen", e)
            }
        }

    override var hueCyan: Double
        get() = try { CameraStateJNI.getHueCyan(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueCyan(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueCyan", e)
            }
        }

    override var hueBlue: Double
        get() = try { CameraStateJNI.getHueBlue(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueBlue(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueBlue", e)
            }
        }

    override var huePurple: Double
        get() = try { CameraStateJNI.getHuePurple(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHuePurple(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set huePurple", e)
            }
        }

    override var hueMagenta: Double
        get() = try { CameraStateJNI.getHueMagenta(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHueMagenta(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set hueMagenta", e)
            }
        }

    override var scanlinesHorizontal: Boolean
        get() = try { CameraStateJNI.getScanlinesHorizontal(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setScanlinesHorizontal(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set scanlinesHorizontal", e)
            }
        }

    override var scanlinesMode: Double
        get() = try { CameraStateJNI.getScanlinesMode(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setScanlinesMode(0L, value.toInt())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set scanlinesMode", e)
            }
        }

    override var scanlinesDensity: Double
        get() = try { CameraStateJNI.getScanlinesDensity(0L).toDouble() } catch (e: Throwable) { 800.0 }
        set(value) {
            try {
                CameraStateJNI.setScanlinesDensity(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set scanlinesDensity", e)
            }
        }

    override var lensDistortion: Double
        get() = try { CameraStateJNI.getLensDistortion(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setLensDistortion(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set lensDistortion", e)
            }
        }

    override var halationIntensity: Double
        get() = try { CameraStateJNI.getHalationIntensity(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setHalationIntensity(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set halationIntensity", e)
            }
        }

    override var halationEnabled: Boolean
        get() = try { CameraStateJNI.getHalationEnabled(0L) } catch (e: Throwable) { false }
        set(value) {
            try {
                CameraStateJNI.setHalationEnabled(0L, value)
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set halationEnabled", e)
            }
        }

    override var halationThreshold: Double
        get() = try { CameraStateJNI.getHalationThreshold(0L).toDouble() } catch (e: Throwable) { 0.5 }
        set(value) {
            try {
                CameraStateJNI.setHalationThreshold(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set halationThreshold", e)
            }
        }

    override var bloomThreshold: Double
        get() = try { CameraStateJNI.getBloomThreshold(0L).toDouble() } catch (e: Throwable) { 0.5 }
        set(value) {
            try {
                CameraStateJNI.setBloomThreshold(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set bloomThreshold", e)
            }
        }

    override var chromaBleed: Double
        get() = try { CameraStateJNI.getChromaBleed(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setChromaBleed(0L, value.toFloat())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set chromaBleed", e)
            }
        }

    override var deviceOrientation: Double
        get() = try { CameraStateJNI.getDeviceOrientation(0L).toDouble() } catch (e: Throwable) { 0.0 }
        set(value) {
            try {
                CameraStateJNI.setDeviceOrientation(0L, value.toInt())
            } catch (e: Throwable) {
                Log.e("HybridNitroCameraConfiguration", "Failed to set deviceOrientation", e)
            }
        }
    // @@GEN_OVERRIDES_END@@
}
