const fs = require('fs');
const path = require('path');
const { loadYamlConfig, PROJECT_ROOT } = require('./utils/config-loader');

const ERRORS_YAML_PATH = 'packages/shared/camera-errors.yaml';

const FILE_PATHS = {
  tsErrors: 'packages/engine/src/errors.ts',
  kotlinErrors: 'packages/engine/android/src/main/java/com/grovkornet/nativefilmcamera/errors/CameraErrors.kt'
};

function toCamelCase(str) {
  let cleaned = str;
  if (cleaned.startsWith('E_')) {
    cleaned = cleaned.substring(2);
  }
  return cleaned.toLowerCase().replace(/_([a-z])/g, (g) => g[1].toUpperCase());
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function main() {
  console.log(`Loading errors from: ${ERRORS_YAML_PATH}`);
  const data = loadYamlConfig(ERRORS_YAML_PATH);

  if (!data.errors || !Array.isArray(data.errors)) {
    throw new Error("Invalid schema: 'errors' array is required.");
  }

  const errors = data.errors;
  console.log(`Loaded ${errors.length} errors. Generating code...`);

  // 1. Generate TS Errors File
  const tsEnumEntries = errors.map(e => `  ${e.name} = '${e.name}',`).join('\n');
  const tsDetailsEntries = errors.map(e => {
    const req = e.required_params ? JSON.stringify(e.required_params) : '[]';
    return `  [CameraErrorCode.${e.name}]: {
    code: ${e.code},
    severity: '${e.severity}',
    category: '${e.category}',
    requiredParams: ${req},
    description: "${e.description.replace(/"/g, '\\"')}"
  },`;
  }).join('\n');

  const tsContent = `/**
 * @file errors.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-errors.yaml
 * 
 * To add, edit, or remove camera errors, modify the YAML file above and run:
 *   npm run codegen
 * (or build/run the mobile app via npm run android)
 */

export enum CameraErrorCode {
${tsEnumEntries}
}

export interface CameraErrorDetail {
  code: number;
  severity: 'fatal' | 'warning';
  category: string;
  requiredParams: string[];
  description: string;
}

export const CAMERA_ERROR_DETAILS: Record<CameraErrorCode, CameraErrorDetail> = {
${tsDetailsEntries}
};
`;

  // 2. Generate Kotlin Errors File
  const kotlinEnumEntries = errors.map((e, idx, arr) => {
    const comma = idx === arr.length - 1 ? ';' : ',';
    return `    ${e.name}(${e.code}, "${e.severity}", "${e.category}")${comma}`;
  }).join('\n');

  const kotlinFactoryMethods = errors.map(e => {
    const camelName = toCamelCase(e.name);
    const capName = capitalize(camelName);
    const params = e.required_params || [];
    
    const methodArgs = params.map(p => `${p}: String`).join(', ');
    const separator = methodArgs ? ', ' : '';
    
    let messageExpr;
    if (params.length > 0) {
      const paramBindings = params.map(p => `${p}=\$${p}`).join(', ');
      messageExpr = `"${e.description.replace(/"/g, '\\"')} Params: [${paramBindings}]"`;
    } else {
      messageExpr = `"${e.description.replace(/"/g, '\\"')}"`;
    }
    
    return `    fun create${capName}(${methodArgs}${separator}cause: Throwable? = null): CameraCodedException {
        return CameraCodedException(
            CameraErrorCode.${e.name},
            ${messageExpr},
            cause
        )
    }`;
  }).join('\n\n');

  const kotlinContent = `package com.grovkornet.nativefilmcamera.errors

/**
 * @file CameraErrors.kt
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-errors.yaml
 * 
 * To add, edit, or remove camera errors, modify the YAML file above and run:
 *   npm run codegen
 * (or build/run the mobile app via npm run android)
 */
enum class CameraErrorCode(val code: Int, val severity: String, val category: String) {
${kotlinEnumEntries}
}

object CameraErrorFactory {
${kotlinFactoryMethods}
}
`;

  // Write TS File
  const tsPath = path.resolve(PROJECT_ROOT, FILE_PATHS.tsErrors);
  fs.mkdirSync(path.dirname(tsPath), { recursive: true });
  fs.writeFileSync(tsPath, tsContent, 'utf8');
  console.log(`Successfully generated TS errors: ${FILE_PATHS.tsErrors}`);

  // Write Kotlin File
  const kotlinPath = path.resolve(PROJECT_ROOT, FILE_PATHS.kotlinErrors);
  fs.mkdirSync(path.dirname(kotlinPath), { recursive: true });
  fs.writeFileSync(kotlinPath, kotlinContent, 'utf8');
  console.log(`Successfully generated Kotlin errors: ${FILE_PATHS.kotlinErrors}`);
}

if (require.main === module) {
  main();
}

module.exports = {
  main
};
