const fs = require('fs');
const path = require('path');
const { loadYamlConfig, PROJECT_ROOT } = require('./utils/config-loader');

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function yamlTypeToTsType(prop) {
  if (prop.enum) {
    return prop.enum.map(e => `'${e}'`).join(' | ');
  }
  switch (prop.type) {
    case 'number': return 'number';
    case 'string': return 'string';
    case 'boolean': return 'boolean';
    case 'array': return 'any[]';
    case 'object': return 'Record<string, any>';
    default: return 'any';
  }
}

function yamlTypeToKotlinType(prop) {
  let baseType = 'Any';
  switch (prop.type) {
    case 'number': baseType = 'Double'; break;
    case 'string': baseType = 'String'; break;
    case 'boolean': baseType = 'Boolean'; break;
    case 'array': baseType = 'List<Any>'; break;
    case 'object': baseType = 'Map<String, Any>'; break;
  }
  return prop.optional ? `${baseType}?` : baseType;
}

function yamlTypeToCppType(prop, eventName) {
  if (prop.enum) {
    return capitalize(prop.name);
  }
  let baseType = 'void*';
  switch (prop.type) {
    case 'number': baseType = 'double'; break;
    case 'string': baseType = 'std::string'; break;
    case 'boolean': baseType = 'bool'; break;
    case 'array':
      if (prop.properties) {
        baseType = `std::vector<${capitalize(eventName)}Event${capitalize(prop.name)}Item>`;
      } else {
        baseType = 'std::vector<std::string>';
      }
      break;
    case 'object': baseType = 'jobject'; break;
  }
  return prop.optional ? `std::optional<${baseType}>` : baseType;
}

function generateTs(events) {
  let content = `/**
 * @file events.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-events.yaml
 * 
 * To add, edit, or remove camera events, modify the YAML file above and run:
 *   npm run codegen
 */

`;

  // Generate nested sub-interfaces
  events.forEach(event => {
    event.properties.forEach(prop => {
      if (prop.type === 'array' && prop.properties) {
        const interfaceName = `${capitalize(event.name)}Event${capitalize(prop.name)}Item`;
        content += `export interface ${interfaceName} {\n`;
        prop.properties.forEach(p => {
          content += `  ${p.name}${p.optional ? '?' : ''}: ${yamlTypeToTsType(p)};\n`;
        });
        content += `}\n\n`;
      }
    });
  });

  // Generate main event interfaces
  events.forEach(event => {
    const interfaceName = `${capitalize(event.name)}Event`;
    content += `export interface ${interfaceName} {\n`;
    event.properties.forEach(prop => {
      let tsType;
      if (prop.type === 'array' && prop.properties) {
        tsType = `${capitalize(event.name)}Event${capitalize(prop.name)}Item[]`;
      } else {
        tsType = yamlTypeToTsType(prop);
      }
      content += `  ${prop.name}${prop.optional ? '?' : ''}: ${tsType};\n`;
    });
    content += `}\n\n`;
  });

  // Generate a composite type of all View Events
  const viewEvents = events.filter(e => e.scope === 'view');
  content += `export interface GeneratedCameraViewEvents {\n`;
  viewEvents.forEach(event => {
    content += `  ${event.name}?: (event: { nativeEvent: ${capitalize(event.name)}Event }) => void;\n`;
  });
  content += `}\n`;

  const outputPath = path.resolve(PROJECT_ROOT, 'packages/engine/src/events.ts');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`Generated TS events: ${outputPath}`);
}

function generateKotlin(events) {
  let content = `package com.grovkornet.nativefilmcamera.events

/**
 * @file CameraEvents.kt
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-events.yaml
 * 
 * To add, edit, or remove camera events, modify the YAML file above and run:
 *   npm run codegen
 */
object CameraEvents {
`;

  events.forEach(event => {
    // Generate any nested helpers (like availableCameras items)
    event.properties.forEach(prop => {
      if (prop.type === 'array' && prop.properties) {
        const funcName = `create${capitalize(event.name)}${capitalize(prop.name)}Item`;
        const args = prop.properties.map(p => {
          const ktType = yamlTypeToKotlinType(p);
          const defaultVal = p.optional ? ' = null' : '';
          return `        ${p.name}: ${ktType}${defaultVal}`;
        }).join(',\n');
        
        content += `    fun ${funcName}(\n${args}\n    ): Map<String, Any> {\n`;
        
        const hasOptionals = prop.properties.some(p => p.optional);
        if (hasOptionals) {
          content += `        val map = mutableMapOf<String, Any>()\n`;
          prop.properties.forEach(p => {
            if (p.optional) {
              content += `        ${p.name}?.let { map["${p.name}"] = it }\n`;
            } else {
              content += `        map["${p.name}"] = ${p.name}\n`;
            }
          });
          content += `        return map\n`;
        } else {
          content += `        return mapOf(\n`;
          const entries = prop.properties.map(p => `            "${p.name}" to ${p.name}`).join(',\n');
          content += `${entries}\n        )\n`;
        }
        content += `    }\n\n`;
      }
    });

    // Generate main helper method
    const funcName = `create${capitalize(event.name)}`;
    const args = event.properties.map(p => {
      let ktType;
      if (p.type === 'array' && p.properties) {
        ktType = `List<Map<String, Any>>`;
      } else {
        ktType = yamlTypeToKotlinType(p);
      }
      const defaultVal = p.optional ? ' = null' : '';
      return `        ${p.name}: ${ktType}${defaultVal}`;
    }).join(',\n');

    content += `    fun ${funcName}(\n${args}\n    ): Map<String, Any> {\n`;

    const hasOptionals = event.properties.some(p => p.optional);
    if (hasOptionals) {
      content += `        val map = mutableMapOf<String, Any>()\n`;
      event.properties.forEach(p => {
        if (p.optional) {
          content += `        ${p.name}?.let { map["${p.name}"] = it }\n`;
        } else {
          content += `        map["${p.name}"] = ${p.name}\n`;
        }
      });
      content += `        return map\n`;
    } else {
      content += `        return mapOf(\n`;
      const entries = event.properties.map(p => `            "${p.name}" to ${p.name}`).join(',\n');
      content += `${entries}\n        )\n`;
    }
    content += `    }\n\n`;
  });

  content += `}\n`;

  const outputPath = path.resolve(PROJECT_ROOT, 'packages/engine/android/src/main/java/com/grovkornet/nativefilmcamera/events/CameraEvents.kt');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`Generated Kotlin events: ${outputPath}`);
}

function generateCppEnums(events) {
  let cpp = '';
  const processedEnums = new Set();
  events.forEach(event => {
    event.properties.forEach(prop => {
      if (prop.enum) {
        const enumName = capitalize(prop.name);
        if (processedEnums.has(enumName)) return;
        processedEnums.add(enumName);
        
        cpp += `enum class ${enumName} {\n`;
        const enumValues = prop.enum.map(v => `    ${capitalize(v)}`);
        cpp += enumValues.join(',\n') + '\n';
        cpp += `};\n\n`;
        
        // toString helper
        cpp += `inline const char* toString(${enumName} val) {\n`;
        cpp += `    switch (val) {\n`;
        prop.enum.forEach(v => {
          cpp += `        case ${enumName}::${capitalize(v)}: return "${v}";\n`;
        });
        cpp += `    }\n`;
        cpp += `    return "${prop.enum[0]}";\n`;
        cpp += `}\n\n`;
      }
    });
  });
  return cpp;
}

function generateCppStructs(events) {
  let cpp = '';
  
  // 1. Generate nested structs first
  events.forEach(event => {
    event.properties.forEach(prop => {
      if (prop.type === 'array' && prop.properties) {
        const structName = `${capitalize(event.name)}Event${capitalize(prop.name)}Item`;
        cpp += `struct ${structName} {\n`;
        prop.properties.forEach(p => {
          cpp += `    ${yamlTypeToCppType(p, event.name)} ${p.name};\n`;
        });
        cpp += `};\n\n`;
      }
    });
  });

  // 2. Generate main structs
  events.forEach(event => {
    const structName = `${capitalize(event.name)}Event`;
    cpp += `struct ${structName} {\n`;
    event.properties.forEach(prop => {
      cpp += `    ${yamlTypeToCppType(prop, event.name)} ${prop.name};\n`;
    });
    cpp += `};\n\n`;
  });

  return cpp;
}

function generateJniPropertySerializer(prop, accessPath, eventName) {
  let serializationCode = '';
  const key = prop.name;
  
  let wrapStart = '';
  let wrapEnd = '';
  let valPath = accessPath;
  
  if (prop.optional) {
    wrapStart = `    if (${accessPath}.has_value()) {\n    `;
    wrapEnd = `\n    }`;
    valPath = `${accessPath}.value()`;
  }
  
  let body = '';
  if (prop.enum) {
    body += `    jobject j_${prop.name} = toJavaString(env, toString(${valPath}));\n`;
    body += `        putInJavaMap(env, map, "${key}", j_${prop.name});\n`;
    body += `        env->DeleteLocalRef(j_${prop.name});`;
  } else if (prop.type === 'number') {
    body += `    jobject j_${prop.name} = toJavaDouble(env, ${valPath});\n`;
    body += `        putInJavaMap(env, map, "${key}", j_${prop.name});\n`;
    body += `        env->DeleteLocalRef(j_${prop.name});`;
  } else if (prop.type === 'string') {
    body += `    jobject j_${prop.name} = toJavaString(env, ${valPath});\n`;
    body += `        putInJavaMap(env, map, "${key}", j_${prop.name});\n`;
    body += `        env->DeleteLocalRef(j_${prop.name});`;
  } else if (prop.type === 'boolean') {
    body += `    jobject j_${prop.name} = toJavaBoolean(env, ${valPath});\n`;
    body += `        putInJavaMap(env, map, "${key}", j_${prop.name});\n`;
    body += `        env->DeleteLocalRef(j_${prop.name});`;
  } else if (prop.type === 'array') {
    if (prop.properties) {
      // It's a vector of items
      body += `    jclass arrayListClass_${prop.name} = env->FindClass("java/util/ArrayList");\n`;
      body += `        jmethodID initList_${prop.name} = env->GetMethodID(arrayListClass_${prop.name}, "<init>", "()V");\n`;
      body += `        jobject jlist_${prop.name} = env->NewObject(arrayListClass_${prop.name}, initList_${prop.name});\n`;
      body += `        jmethodID addList_${prop.name} = env->GetMethodID(arrayListClass_${prop.name}, "add", "(Ljava/lang/Object;)Z");\n\n`;
      body += `        for (const auto& item : ${valPath}) {\n`;
      body += `            jobject jitem_${prop.name} = toJNI(env, item);\n`;
      body += `            env->CallBooleanMethod(jlist_${prop.name}, addList_${prop.name}, jitem_${prop.name});\n`;
      body += `            env->DeleteLocalRef(jitem_${prop.name});\n`;
      body += `        }\n`;
      body += `        putInJavaMap(env, map, "${key}", jlist_${prop.name});\n`;
      body += `        env->DeleteLocalRef(jlist_${prop.name});`;
    } else {
      // simple vector of strings
      body += `    jclass arrayListClass_${prop.name} = env->FindClass("java/util/ArrayList");\n`;
      body += `        jmethodID initList_${prop.name} = env->GetMethodID(arrayListClass_${prop.name}, "<init>", "()V");\n`;
      body += `        jobject jlist_${prop.name} = env->NewObject(arrayListClass_${prop.name}, initList_${prop.name});\n`;
      body += `        jmethodID addList_${prop.name} = env->GetMethodID(arrayListClass_${prop.name}, "add", "(Ljava/lang/Object;)Z");\n\n`;
      body += `        for (const auto& item : ${valPath}) {\n`;
      body += `            jobject jitem_${prop.name} = toJavaString(env, item);\n`;
      body += `            env->CallBooleanMethod(jlist_${prop.name}, addList_${prop.name}, jitem_${prop.name});\n`;
      body += `            env->DeleteLocalRef(jitem_${prop.name});\n`;
      body += `        }\n`;
      body += `        putInJavaMap(env, map, "${key}", jlist_${prop.name});\n`;
      body += `        env->DeleteLocalRef(jlist_${prop.name});`;
    }
  } else {
    body += `    // Unhandled JNI type for ${key}`;
  }
  
  if (prop.optional) {
    body = body.split('\n').map(line => '    ' + line).join('\n');
  }
  
  serializationCode = wrapStart + body + wrapEnd + '\n';
  return serializationCode;
}

function generateCppJniHelpers(events) {
  let cpp = `// JNI Helper functions for serialization to Java Map (jobject)
inline jobject createJavaHashMap(JNIEnv* env) {
    jclass hashMapClass = env->FindClass("java/util/HashMap");
    jmethodID init = env->GetMethodID(hashMapClass, "<init>", "()V");
    return env->NewObject(hashMapClass, init);
}

inline void putInJavaMap(JNIEnv* env, jobject map, const std::string& key, jobject value) {
    jclass mapClass = env->FindClass("java/util/Map");
    jmethodID put = env->GetMethodID(mapClass, "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
    jstring jkey = env->NewStringUTF(key.c_str());
    env->CallObjectMethod(map, put, jkey, value);
    env->DeleteLocalRef(jkey);
}

inline jobject toJavaDouble(JNIEnv* env, double value) {
    jclass doubleClass = env->FindClass("java/lang/Double");
    jmethodID init = env->GetMethodID(doubleClass, "<init>", "(D)V");
    return env->NewObject(doubleClass, init, value);
}

inline jobject toJavaBoolean(JNIEnv* env, bool value) {
    jclass booleanClass = env->FindClass("java/lang/Boolean");
    jmethodID init = env->GetMethodID(booleanClass, "<init>", "(Z)V");
    return env->NewObject(booleanClass, init, value);
}

inline jobject toJavaString(JNIEnv* env, const std::string& value) {
    return env->NewStringUTF(value.c_str());
}

`;

  // First, generate toJNI for nested items
  events.forEach(event => {
    event.properties.forEach(prop => {
      if (prop.type === 'array' && prop.properties) {
        const structName = `${capitalize(event.name)}Event${capitalize(prop.name)}Item`;
        cpp += `inline jobject toJNI(JNIEnv* env, const ${structName}& item) {\n`;
        cpp += `    jobject map = createJavaHashMap(env);\n`;
        
        prop.properties.forEach(p => {
          cpp += generateJniPropertySerializer(p, `item.${p.name}`, event.name);
        });
        
        cpp += `    return map;\n`;
        cpp += `}\n\n`;
      }
    });
  });

  // Then, generate toJNI for main structs
  events.forEach(event => {
    const structName = `${capitalize(event.name)}Event`;
    cpp += `inline jobject toJNI(JNIEnv* env, const ${structName}& event) {\n`;
    cpp += `    jobject map = createJavaHashMap(env);\n`;
    
    event.properties.forEach(p => {
      cpp += generateJniPropertySerializer(p, `event.${p.name}`, event.name);
    });
    
    cpp += `    return map;\n`;
    cpp += `}\n\n`;
  });

  return cpp;
}

function generateCppJsiHelpers(events) {
  let cpp = `#if __has_include(<jsi/jsi.h>)
// High-frequency JSI dispatch helpers to avoid JNI/GC overhead
`;

  events.filter(e => e.frequency === 'high').forEach(event => {
    const structName = `${capitalize(event.name)}Event`;
    cpp += `inline void dispatchJsiEvent(facebook::jsi::Runtime& runtime, const facebook::jsi::Function& callback, const ${structName}& event) {\n`;
    cpp += `    facebook::jsi::Object payload(runtime);\n`;
    
    event.properties.forEach(p => {
      if (p.type === 'number') {
        cpp += `    payload.setProperty(runtime, "${p.name}", event.${p.name});\n`;
      } else if (p.type === 'string') {
        cpp += `    payload.setProperty(runtime, "${p.name}", facebook::jsi::String::createFromUtf8(runtime, event.${p.name}));\n`;
      } else if (p.type === 'boolean') {
        cpp += `    payload.setProperty(runtime, "${p.name}", event.${p.name});\n`;
      } else {
        cpp += `    // Complex type serialization for ${p.name} not standard for high-frequency events\n`;
      }
    });
    
    cpp += `    callback.call(runtime, payload);\n`;
    cpp += `}\n\n`;
  });

  cpp += `#endif\n`;
  return cpp;
}

function generateCpp(events) {
  let content = `/**
 * @file CameraEvents.h
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/camera-events.yaml
 * 
 * To add, edit, or remove camera events, modify the YAML file above and run:
 *   npm run codegen
 */

#pragma once
#include <jni.h>
#include <string>
#include <vector>
#include <optional>

namespace grovkornet {
namespace events {

`;

  content += generateCppEnums(events);
  content += generateCppStructs(events);
  content += generateCppJniHelpers(events);
  content += generateCppJsiHelpers(events);

  content += `} // namespace events
} // namespace grovkornet
`;

  const outputPath = path.resolve(PROJECT_ROOT, 'packages/engine/android/src/main/cpp/core/CameraEvents.h');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`Generated C++ events: ${outputPath}`);
}

function main() {
  const EVENTS_YAML_PATH = 'packages/shared/camera-events.yaml';
  console.log(`Loading events from: ${EVENTS_YAML_PATH}`);
  const data = loadYamlConfig(EVENTS_YAML_PATH);
  
  if (!data.events || !Array.isArray(data.events)) {
    throw new Error("Invalid schema: 'events' array is required.");
  }
  
  const events = data.events;
  console.log(`Successfully loaded ${events.length} events. Generating files...`);
  
  generateTs(events);
  generateKotlin(events);
  generateCpp(events);
  
  console.log('Event codegen completed successfully.');
}

if (require.main === module) {
  main();
}

module.exports = {
  main
};
