const fs = require('fs');
const path = require('path');
const { loadYamlConfig, PROJECT_ROOT } = require('./utils/config-loader');

const HARDWARE_YAML_PATH = 'packages/shared/hardware-config.yaml';

const FILE_PATHS = {
  cppHeader: 'packages/engine/android/src/main/cpp/core/HardwareConfig.h',
  tsConfig: 'packages/shared/src/hardwareConfig.ts'
};

function main() {
  console.log(`Loading hardware configuration from YAML: ${HARDWARE_YAML_PATH}`);
  const config = loadYamlConfig(HARDWARE_YAML_PATH);

  // Basic Validation
  if (!config.lut || typeof config.lut.size !== 'number') {
    throw new Error("Invalid schema: 'lut.size' is required as a number.");
  }
  if (!config.drs || 
      typeof config.drs.min_scale !== 'number' || 
      typeof config.drs.max_scale !== 'number' ||
      typeof config.drs.frame_time_window_size !== 'number' ||
      typeof config.drs.cooldown_frames !== 'number') {
    throw new Error("Invalid schema: 'drs' properties are required as numbers.");
  }

  console.log('Generating code files...');

  // 1. Generate C++ Header File
  const cppContent = `/**
 * @file HardwareConfig.h
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/hardware-config.yaml
 * 
 * To add, edit, or remove hardware/rendering constants, modify the YAML file above and run:
 *   npm run codegen
 */

#pragma once

namespace HardwareConfig {
    static constexpr int LUT_SIZE = ${config.lut.size};
    static constexpr float MIN_DRS_SCALE = ${config.drs.min_scale.toFixed(1)}f;
    static constexpr float MAX_DRS_SCALE = ${config.drs.max_scale.toFixed(1)}f;
    static constexpr int FRAME_TIME_WINDOW_SIZE = ${config.drs.frame_time_window_size};
    static constexpr int DRS_COOLDOWN_FRAMES = ${config.drs.cooldown_frames};
}
`;

  // 2. Generate TS Config File
  const tsContent = `/**
 * @file hardwareConfig.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the Single Source of Truth (SSOT):
 * packages/shared/hardware-config.yaml
 * 
 * To add, edit, or remove hardware/rendering constants, modify the YAML file above and run:
 *   npm run codegen
 */

export const HARDWARE_CONFIG = {
  lut: {
    size: ${config.lut.size},
  },
  drs: {
    minScale: ${config.drs.min_scale},
    maxScale: ${config.drs.max_scale},
    frameTimeWindowSize: ${config.drs.frame_time_window_size},
    cooldownFrames: ${config.drs.cooldown_frames},
  },
} as const;
`;

  // Write C++ Header File
  const cppPath = path.resolve(PROJECT_ROOT, FILE_PATHS.cppHeader);
  fs.mkdirSync(path.dirname(cppPath), { recursive: true });
  fs.writeFileSync(cppPath, cppContent, 'utf8');
  console.log(`Successfully generated C++ header: ${FILE_PATHS.cppHeader}`);

  // Write TS Config File
  const tsPath = path.resolve(PROJECT_ROOT, FILE_PATHS.tsConfig);
  fs.mkdirSync(path.dirname(tsPath), { recursive: true });
  fs.writeFileSync(tsPath, tsContent, 'utf8');
  console.log(`Successfully generated TS config: ${FILE_PATHS.tsConfig}`);
}

if (require.main === module) {
  main();
}

module.exports = {
  main
};
