const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '../../../..');

const EN_JSON_PATH = path.resolve(PROJECT_ROOT, 'apps/mobile/src/app/providers/i18n/locales/en.json');
const IT_JSON_PATH = path.resolve(PROJECT_ROOT, 'apps/mobile/src/app/providers/i18n/locales/it.json');
const TARGET_DTS_PATH = path.resolve(PROJECT_ROOT, 'apps/mobile/src/app/providers/i18n/i18next.d.ts');

function checkMissingKeys(source, target, currentPath = '') {
  const missing = [];
  for (const key in source) {
    const fullKey = currentPath ? `${currentPath}.${key}` : key;
    if (!(key in target)) {
      missing.push(fullKey);
    } else if (typeof source[key] === 'object' && source[key] !== null) {
      if (typeof target[key] === 'object' && target[key] !== null) {
        missing.push(...checkMissingKeys(source[key], target[key], fullKey));
      } else {
        missing.push(`${fullKey} (expected object, found ${typeof target[key]})`);
      }
    }
  }
  return missing;
}

function main() {
  console.log('🌐 Running i18n Codegen & Validation...');

  if (!fs.existsSync(EN_JSON_PATH)) {
    console.error(`❌ English translation file not found at: ${EN_JSON_PATH}`);
    process.exit(1);
  }

  const enData = JSON.parse(fs.readFileSync(EN_JSON_PATH, 'utf8'));

  // 1. Validate other translation files if they exist
  if (fs.existsSync(IT_JSON_PATH)) {
    const itData = JSON.parse(fs.readFileSync(IT_JSON_PATH, 'utf8'));
    const missingKeys = checkMissingKeys(enData, itData);
    
    if (missingKeys.length > 0) {
      console.warn(`⚠️ Found ${missingKeys.length} missing translation keys in Italian (it.json):`);
      missingKeys.forEach(key => console.warn(`  - ${key}`));
    } else {
      console.log('✅ Italian translation (it.json) is fully synchronized with English (en.json).');
    }
  } else {
    console.warn(`⚠️ Italian translation file not found at: ${IT_JSON_PATH}`);
  }

  // 2. Generate i18next.d.ts type definition
  const dtsContent = `/**
 * @file i18next.d.ts
 * @note GENERATED FILE - DO NOT MODIFY DIRECTLY.
 * 
 * This file is automatically generated from the translations in:
 * apps/mobile/src/app/providers/i18n/locales/en.json
 * 
 * To update, modify the JSON translation files and run:
 *   npm run codegen
 */

import 'react-i18next';
import en from './locales/en.json';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: typeof en;
  }
}
`;

  try {
    fs.writeFileSync(TARGET_DTS_PATH, dtsContent, 'utf8');
    console.log(`✅ Generated type definitions at: ${TARGET_DTS_PATH}`);
  } catch (error) {
    console.error(`❌ Failed to write i18next.d.ts: ${error.message}`);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  main
};
