
/**
 * Serialized Look & Feel parameters from FilmStore
 */
export interface FilmPresetPayload {
  // @@GEN_FILM_PAYLOAD_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  noiseReductionMode: number;
  noiseReductionAuto: boolean;
  temperatureAuto: boolean;
  saturation: number;
  contrast: number;
  grainIntensity: number;
  grainChroma: number;
  grainSize: number;
  grainSpeed: number;
  vignetteIntensity: number;
  chromaShift: number;
  temperature: number;
  tint: number;
  bloomIntensity: number;
  chromaticAberration: number;
  chromaShiftDirection: number;
  sharpening: number;
  satRed: number;
  satOrange: number;
  satYellow: number;
  satGreen: number;
  satCyan: number;
  satBlue: number;
  satPurple: number;
  satMagenta: number;
  aberrationInvert: boolean;
  boundMagentaRed: number;
  boundRedOrange: number;
  boundOrangeYellow: number;
  boundYellowGreen: number;
  boundGreenCyan: number;
  boundCyanBlue: number;
  boundBluePurple: number;
  boundPurpleMagenta: number;
  grainRoughness: number;
  grainEnabled: boolean;
  bloomEnabled: boolean;
  blackLevel: number;
  highlights: number;
  pivot: number;
  contrastAuto: boolean;
  blackLevelAuto: boolean;
  highlightsAuto: boolean;
  pivotAuto: boolean;
  pixelationFactor: number;
  tapeJitter: number;
  scanlines: number;
  chromaShiftInvert: boolean;
  hue: number;
  hueRed: number;
  hueOrange: number;
  hueYellow: number;
  hueGreen: number;
  hueCyan: number;
  hueBlue: number;
  huePurple: number;
  hueMagenta: number;
  scanlinesMode: number;
  scanlinesDensity: number;
  // @@GEN_FILM_PAYLOAD_END@@
}

export type GeneratedFilmExcludedKeys =
  // @@GEN_FILM_EXCLUDED_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  | 'isSelfieCamera'
  | 'scanlinesHorizontal'
  // @@GEN_FILM_EXCLUDED_END@@
  ;

/**
 * Serialized Exposure parameters from BodyStore
 */
export interface BodyPresetPayload {
  iso: number;
  ev: number;
  shutterSpeed: number;
  isoAuto: boolean;
  shutterSpeedAuto: boolean;
  evAuto: boolean;
}

export interface PresetPayload {
  film: FilmPresetPayload;
  body: BodyPresetPayload;
}

export interface Preset {
  id: string;
  name: string;
  payload: PresetPayload;
  isFavorite: boolean;
  inQuickSelect: boolean;
  createdAt: number;
  thumbnailUri?: string;
}


