/**
 * Serialized Look & Feel parameters per store, dynamically generated
 */

// @@GEN_PAYLOAD_INTERFACES_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export interface BodyPresetPayload {
}

export interface FilmPresetPayload {
  noiseReductionMode: number;
  noiseReductionAuto: boolean;
  temperatureAuto: boolean;
  saturation: number;
  contrast: number;
  grainIntensity: number;
  grainChroma: number;
  grainSize: number;
  grainSpeed: number;
  vignetteIntensity: number;
  chromaShift: number;
  temperature: number;
  tint: number;
  bloomIntensity: number;
  chromaticAberration: number;
  chromaShiftDirection: number;
  sharpening: number;
  satRed: number;
  satOrange: number;
  satYellow: number;
  satGreen: number;
  satCyan: number;
  satBlue: number;
  satPurple: number;
  satMagenta: number;
  aberrationInvert: boolean;
  boundMagentaRed: number;
  boundRedOrange: number;
  boundOrangeYellow: number;
  boundYellowGreen: number;
  boundGreenCyan: number;
  boundCyanBlue: number;
  boundBluePurple: number;
  boundPurpleMagenta: number;
  grainRoughness: number;
  grainEnabled: boolean;
  bloomEnabled: boolean;
  blackLevel: number;
  highlights: number;
  pivot: number;
  contrastAuto: boolean;
  blackLevelAuto: boolean;
  highlightsAuto: boolean;
  pivotAuto: boolean;
  pixelationFactor: number;
  tapeJitter: number;
  scanlines: number;
  chromaShiftInvert: boolean;
  hue: number;
  hueRed: number;
  hueOrange: number;
  hueYellow: number;
  hueGreen: number;
  hueCyan: number;
  hueBlue: number;
  huePurple: number;
  hueMagenta: number;
  scanlinesMode: number;
  scanlinesDensity: number;
  lensDistortion: number;
  halationIntensity: number;
  halationEnabled: boolean;
  halationThreshold: number;
  bloomThreshold: number;
}

export interface LensPresetPayload {
}
// @@GEN_PAYLOAD_INTERFACES_END@@

// @@GEN_MASTER_PAYLOAD_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export interface PresetPayload {
  body: BodyPresetPayload;
  film: FilmPresetPayload;
  lens: LensPresetPayload;
}
// @@GEN_MASTER_PAYLOAD_END@@

// @@GEN_PAYLOAD_EXCLUDED_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export type GeneratedBodyExcludedKeys =
  | 'ev'
  | 'fpsSetting'
  | 'aspectRatio'
  | 'isoAuto'
  | 'shutterSpeedAuto'
  | 'iso'
  | 'shutterSpeed'
  | 'torchState'
  | 'torchStrength'
  | 'resolutionSetting'
  | 'previewQuality'
  | 'force60fpsCrop'
  | 'zoom'
  ;

export type GeneratedFilmExcludedKeys =
  | 'isSelfieCamera'
  | 'scanlinesHorizontal'
  ;

export type GeneratedLensExcludedKeys =
  | 'focusAuto'
  | 'focusDistance'
  | 'cameraId'
  ;
// @@GEN_PAYLOAD_EXCLUDED_END@@

export interface Preset {
  id: string;
  name: string;
  payload: PresetPayload;
  isFavorite: boolean;
  inQuickSelect: boolean;
  createdAt: number;
  thumbnailUri?: string;
}
