/* eslint-disable @typescript-eslint/no-empty-object-type */
/**
 * Serialized Look & Feel parameters per store, dynamically generated
 */

// @@GEN_PAYLOAD_INTERFACES_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export interface BodyPresetPayload {
}

export interface FilmPresetPayload {
  noiseReductionMode: number;
  noiseReductionAuto: boolean;
  temperatureAuto: boolean;
  saturation: number;
  contrast: number;
  grainIntensity: number;
  grainChroma: number;
  grainSize: number;
  grainSpeed: number;
  vignetteIntensity: number;
  chromaShift: number;
  temperature: number;
  tint: number;
  bloomIntensity: number;
  chromaticAberration: number;
  chromaShiftDirection: number;
  sharpening: number;
  satRed: number;
  satOrange: number;
  satYellow: number;
  satGreen: number;
  satCyan: number;
  satBlue: number;
  satPurple: number;
  satMagenta: number;
  aberrationInvert: boolean;
  boundMagentaRed: number;
  boundRedOrange: number;
  boundOrangeYellow: number;
  boundYellowGreen: number;
  boundGreenCyan: number;
  boundCyanBlue: number;
  boundBluePurple: number;
  boundPurpleMagenta: number;
  grainRoughness: number;
  grainEnabled: boolean;
  bloomEnabled: boolean;
  blackLevel: number;
  highlights: number;
  pivot: number;
  contrastAuto: boolean;
  blackLevelAuto: boolean;
  highlightsAuto: boolean;
  pivotAuto: boolean;
  pixelationFactor: number;
  tapeJitter: number;
  scanlines: number;
  chromaShiftInvert: boolean;
  hue: number;
  hueRed: number;
  hueOrange: number;
  hueYellow: number;
  hueGreen: number;
  hueCyan: number;
  hueBlue: number;
  huePurple: number;
  hueMagenta: number;
  scanlinesMode: number;
  scanlinesDensity: number;
  lensDistortion: number;
  halationIntensity: number;
  halationEnabled: boolean;
  halationThreshold: number;
  bloomThreshold: number;
  chromaBleed: number;
}

export interface LensPresetPayload {
}
// @@GEN_PAYLOAD_INTERFACES_END@@

// @@GEN_MASTER_PAYLOAD_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export interface PresetPayload {
  body: BodyPresetPayload;
  film: FilmPresetPayload;
  lens: LensPresetPayload;
}
// @@GEN_MASTER_PAYLOAD_END@@

// @@GEN_PAYLOAD_EXCLUDED_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export type GeneratedBodyExcludedKeys =
  | 'evAuto'
  | 'ev'
  | 'fpsSetting'
  | 'aspectRatio'
  | 'isoAuto'
  | 'shutterSpeedAuto'
  | 'iso'
  | 'shutterSpeed'
  | 'torchState'
  | 'torchStrength'
  | 'resolutionSetting'
  | 'previewQuality'
  | 'force60fpsCrop'
  | 'zoom'
  | 'fps'
  | 'hwFps'
  | 'resolution'
  ;

export type GeneratedFilmExcludedKeys =
  | 'isSelfieCamera'
  | 'scanlinesHorizontal'
  | 'deviceOrientation'
  ;

export type GeneratedLensExcludedKeys =
  | 'focusAuto'
  | 'focusDistance'
  | 'cameraId'
  ;
// @@GEN_PAYLOAD_EXCLUDED_END@@

// @@GEN_PAYLOAD_ACTIONS_START@@
// ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
// This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
// or packages/shared/camera-errors.yaml, then run `npm run codegen`.
export type GeneratedBodyActionKeys =
  | 'setEvAuto'
  | 'setEv'
  | 'setFpsSetting'
  | 'setAspectRatio'
  | 'setIsoAuto'
  | 'setShutterSpeedAuto'
  | 'setIso'
  | 'setShutterSpeed'
  | 'setTorchState'
  | 'setTorchStrength'
  | 'setResolutionSetting'
  | 'setPreviewQuality'
  | 'setForce60fpsCrop'
  | 'setZoom'
  | 'setFps'
  | 'setHwFps'
  | 'setResolution'
  ;

export type GeneratedFilmActionKeys =
  | 'setNoiseReductionMode'
  | 'setNoiseReductionAuto'
  | 'setTemperatureAuto'
  | 'setIsSelfieCamera'
  | 'setSaturation'
  | 'setContrast'
  | 'setGrainIntensity'
  | 'setGrainChroma'
  | 'setGrainSize'
  | 'setGrainSpeed'
  | 'setVignetteIntensity'
  | 'setChromaShift'
  | 'setTemperature'
  | 'setTint'
  | 'setBloomIntensity'
  | 'setChromaticAberration'
  | 'setChromaShiftDirection'
  | 'setSharpening'
  | 'setSatRed'
  | 'setSatOrange'
  | 'setSatYellow'
  | 'setSatGreen'
  | 'setSatCyan'
  | 'setSatBlue'
  | 'setSatPurple'
  | 'setSatMagenta'
  | 'setAberrationInvert'
  | 'setBoundMagentaRed'
  | 'setBoundRedOrange'
  | 'setBoundOrangeYellow'
  | 'setBoundYellowGreen'
  | 'setBoundGreenCyan'
  | 'setBoundCyanBlue'
  | 'setBoundBluePurple'
  | 'setBoundPurpleMagenta'
  | 'setGrainRoughness'
  | 'setGrainEnabled'
  | 'setBloomEnabled'
  | 'setBlackLevel'
  | 'setHighlights'
  | 'setPivot'
  | 'setContrastAuto'
  | 'setBlackLevelAuto'
  | 'setHighlightsAuto'
  | 'setPivotAuto'
  | 'setPixelationFactor'
  | 'setTapeJitter'
  | 'setScanlines'
  | 'setChromaShiftInvert'
  | 'setHue'
  | 'setHueRed'
  | 'setHueOrange'
  | 'setHueYellow'
  | 'setHueGreen'
  | 'setHueCyan'
  | 'setHueBlue'
  | 'setHuePurple'
  | 'setHueMagenta'
  | 'setScanlinesHorizontal'
  | 'setScanlinesMode'
  | 'setScanlinesDensity'
  | 'setLensDistortion'
  | 'setHalationIntensity'
  | 'setHalationEnabled'
  | 'setHalationThreshold'
  | 'setBloomThreshold'
  | 'setChromaBleed'
  | 'setDeviceOrientation'
  ;

export type GeneratedLensActionKeys =
  | 'setFocusAuto'
  | 'setFocusDistance'
  | 'setCameraId'
  ;
// @@GEN_PAYLOAD_ACTIONS_END@@

export interface Preset {
  id: string;
  name: string;
  payload: PresetPayload;
  isFavorite: boolean;
  inQuickSelect: boolean;
  createdAt: number;
  thumbnailUri?: string;
}
