import { create } from 'zustand';
import { makeMutable } from 'react-native-reanimated';
import { logger } from '@shared/lib/logger';
import { BodyStore } from './types';
import { 
  DEFAULT_ISO,
  DEFAULT_EV,
  DEFAULT_SHUTTER_SPEED,
  DEFAULT_FPS_SETTING,
  DEFAULT_ASPECT_RATIO,
  DEFAULT_ISO_AUTO,
  DEFAULT_SHUTTER_SPEED_AUTO,
  DEFAULT_TORCH_STATE,
  DEFAULT_TORCH_STRENGTH,
  DEFAULT_RESOLUTION_SETTING,
  DEFAULT_PREVIEW_QUALITY,
  DEFAULT_FORCE_60FPS_CROP,
  DEFAULT_ZOOM,
} from '@grovkornet/shared';

export const useBodyStore = create<BodyStore>((set, get) => ({
  fps: makeMutable(0),
  hwFps: makeMutable(0),
  resolution: makeMutable(''),
  evAuto: makeMutable(true),
  // @@GEN_STATE_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  ev: makeMutable(DEFAULT_EV),
  fpsSetting: makeMutable(DEFAULT_FPS_SETTING),
  aspectRatio: makeMutable(DEFAULT_ASPECT_RATIO),
  isoAuto: makeMutable(DEFAULT_ISO_AUTO),
  shutterSpeedAuto: makeMutable(DEFAULT_SHUTTER_SPEED_AUTO),
  iso: makeMutable(DEFAULT_ISO),
  shutterSpeed: makeMutable(DEFAULT_SHUTTER_SPEED),
  torchState: makeMutable(DEFAULT_TORCH_STATE),
  torchStrength: makeMutable(DEFAULT_TORCH_STRENGTH),
  resolutionSetting: makeMutable(DEFAULT_RESOLUTION_SETTING),
  previewQuality: makeMutable(DEFAULT_PREVIEW_QUALITY),
  force60fpsCrop: makeMutable(DEFAULT_FORCE_60FPS_CROP),
  zoom: makeMutable(DEFAULT_ZOOM),
  // @@GEN_STATE_END@@
  capabilities: {
    hasTorch: false,
    maxTorchStrength: 1,
    isoMin: 100,
    isoMax: 3200,
    maxFps: 60,
  },

  setDebugInfo: (fpsVal, resVal, hwFpsVal) => {
    const { fps, resolution, hwFps } = get();
    fps.value = fpsVal;
    resolution.value = resVal;
    hwFps.value = hwFpsVal;
  },
  setEvAuto: (value) => {
    get().evAuto.value = value;
    if (value) get().ev.value = DEFAULT_EV;
  },
  // @@GEN_SETTERS_START@@
  // ⚠️ AI & MANUAL WARNING: DO NOT EDIT THIS SECTION!
  // This block is auto-generated by codegen. To modify, edit the configs in packages/shared/camera-parameters/
  // or packages/shared/camera-errors.yaml, then run `npm run codegen`.
  setEv: (value) => {
    const { ev, evAuto, isoAuto, shutterSpeedAuto } = get();
    ev.value = value;
    evAuto.value = false;
    isoAuto.value = true;
    shutterSpeedAuto.value = true;

    notifyBodyStoreListener('ev');
  },
  setFpsSetting: (value) => {
    get().fpsSetting.value = value;
    notifyBodyStoreListener('fpsSetting');
  },
  setAspectRatio: (value) => {
    get().aspectRatio.value = value;
    notifyBodyStoreListener('aspectRatio');
  },
  setIsoAuto: (value) => {
    const { isoAuto, shutterSpeedAuto } = get();
    isoAuto.value = value;
    shutterSpeedAuto.value = value;

    notifyBodyStoreListener('isoAuto');
  },
  setShutterSpeedAuto: (value) => {
    const { shutterSpeedAuto, isoAuto } = get();
    shutterSpeedAuto.value = value;
    isoAuto.value = value;

    notifyBodyStoreListener('shutterSpeedAuto');
  },
  setIso: (value) => {
    const { iso, isoAuto, shutterSpeedAuto, evAuto, ev } = get();
    iso.value = value;
    isoAuto.value = false;
    shutterSpeedAuto.value = false;
    evAuto.value = true;
    ev.value = DEFAULT_EV;

    notifyBodyStoreListener('iso');
  },
  setShutterSpeed: (value) => {
    const { shutterSpeed, shutterSpeedAuto, isoAuto, evAuto, ev } = get();
    shutterSpeed.value = value;
    shutterSpeedAuto.value = false;
    isoAuto.value = false;
    evAuto.value = true;
    ev.value = DEFAULT_EV;

    notifyBodyStoreListener('shutterSpeed');
  },
  setTorchState: (value) => {
    get().torchState.value = value;
    notifyBodyStoreListener('torchState');
  },
  setTorchStrength: (value) => {
    get().torchStrength.value = value;
    notifyBodyStoreListener('torchStrength');
  },
  setResolutionSetting: (value) => {
    get().resolutionSetting.value = value;
    notifyBodyStoreListener('resolutionSetting');
  },
  setPreviewQuality: (value) => {
    get().previewQuality.value = value;
    notifyBodyStoreListener('previewQuality');
  },
  setForce60fpsCrop: (value) => {
    get().force60fpsCrop.value = value;
    notifyBodyStoreListener('force60fpsCrop');
  },
  setZoom: (value) => {
    get().zoom.value = value;
    notifyBodyStoreListener('zoom');
  },
  // @@GEN_SETTERS_END@@
  setCapabilities: (caps) => {
    logger.info('BodyStore', 'Hardware capabilities updated for Body');
    if (caps.maxFps && get().fpsSetting.value > caps.maxFps) {
      get().fpsSetting.value = caps.maxFps;
    }
    if (caps.maxZoom && get().zoom.value > caps.maxZoom) {
      get().zoom.value = caps.maxZoom;
    }
    if (caps.minZoom && get().zoom.value < caps.minZoom) {
      get().zoom.value = caps.minZoom;
    }
    set((state) => ({
      capabilities: {
        ...state.capabilities,
        ...caps,
      }
    }));
  },
}));

let changeListener: ((paramName?: string) => void) | null = null;
export const setBodyStoreListener = (l: (paramName?: string) => void) => { changeListener = l; };
export const notifyBodyStoreListener = (paramName?: string) => { changeListener?.(paramName); };


